## Redis tests

In [1]:
import redis 
import json
import time

In [2]:
redis_client = redis.StrictRedis(host="127.0.0.1", port=6379, decode_responses=True)

In [17]:
redis_client.keys()

['thread:shadaabsweden@outlook.com:unnhytbbtslv8ts',
 'thread:shadaabsweden@outlook.com:tslv8ts',
 'thread:shadaabsweden@outlook.com:tjcislv8ts']

In [4]:
thread_id = 'shadaabsweden@outlook.com:tjcislv8ts'

In [ ]:
redis.hset('thread:shadaabsweden@outlook.com:tjcislv8ts', mapping={'address' : 'Teknigringen 10B'})

In [5]:
user_message = 'What will be the CO2 saved in this process on rennovation of my building Teknigringen 10B? '
thread_name = f"thread:{thread_id}"
message_data = json.dumps({
    "content": user_message, 
    "role": "user" , 
    "timestamp": time.time() , 
    "added_to_database" : 0 , 
    "classification": None,
    "agent_answered": None
    })
redis_client.rpush(thread_name, message_data)

# Notify Redis queue manager to process the message
event_data = json.dumps({"event": "message", "thread_name": thread_id})
redis_client.publish("thread_events", event_data)

print(f"Message added to Redis for thread: {thread_id}")

Message added to Redis for thread: shadaabsweden@outlook.com:tjcislv8ts

In [5]:
user_message = 'what should I do to increase the energy rating of '

# user_message = 'what is EKR ? '
thread_name = f"thread:{thread_id}"
message_data = json.dumps({
    "content": user_message, 
    "role": "user" , 
    "timestamp": time.time() , 
    "added_to_database" : 0 , 
    "classification": None,
    "agent_answered": None
    })
redis_client.rpush(thread_name, message_data)

# Notify Redis queue manager to process the message
event_data = json.dumps({"event": "message", "thread_name": thread_id})
redis_client.publish("thread_events", event_data)

print(f"Message added to Redis for thread: {thread_id}")

Message added to Redis for thread: shadaabsweden@outlook.com:tslv8ts

In [120]:
user_message = 'What will be the CO2 saved in this process ?'

message_data = json.dumps({"content": user_message, "role": "user" , "timestamp": time.time() , "added_to_database" : 0})
redis_client.rpush(thread_name, message_data)

# Notify Redis queue manager to process the message
event_data = json.dumps({"event": "message_added", "thread_name": thread_name})
redis_client.publish("thread_events", event_data)

1

In [10]:
messages = redis_client.lrange(thread_name, 0, -1)

In [12]:
messages = redis_client.lrange(thread_name, 0, -1)
thread_content_updated = [json.loads(i) for i in messages]

In [13]:
print(thread_content_updated[-1])

{'role': 'assistant', 'timestamp': 1753869894.8313646, 'added_to_database': 0, 'content': 'To determine the CO2 savings from the measures described in your context for BRF EnERgIEFFEKTI v22, we need to know specific details such as the current energy consumption, the type of heating system in use, and the total area of the building. \n\nHowever, based on the information provided, reducing the indoor temperature by one degree Celsius can lead to a reduction in heating costs by approximately 5%. This reduction in heating demand can translate into CO2 savings, but the exact amount would depend on the energy source used for heating (e.g., fossil fuels, biofuels, etc.).\n\nIf you can provide more specific details about your building, such as the type of heating system and current energy consumption, I can help you estimate the CO2 savings more accurately.', 'classification': 'generic', 'agent_answered': 'generic'}

## code test

#####  sql agent test

In [1]:
from src.database.sql_client import SQLClient

In [3]:
sql = SQLClient()

In [4]:
val = sql.building_by_uuid("8fd266c0-56dd-489b-8e08-a0c08a93ec86")

In [5]:
val = sql.building_by_address('Torparmors Väg 42')

In [6]:
val = sql._single_filter("epc_egenatemp", "120", op="eq")

In [10]:
val = sql.buildings_by_single_filter(field='epc_egenantalplan' , value="10" , op="eq")

In [11]:
len(val)

1496

##### router agent test

In [1]:
from src.agents.router_agent import RouterAgent

In [2]:
router_agent_obj = RouterAgent()

In [7]:
a = router_agent_obj.classify_question('what is this')

In [8]:
a

'conversational'

In [6]:
router_agent_obj.classify_question('''{"unique_id": "5ee393b6c9e77c0008ccbd3c_2", "case_id": "5ee393b6c9e77c0008ccbd3c", "wiki_revision_id": "945521881", "label": "REFUTES", "claim": "As of 14 March , 2020 less than 150,000 coronavirus cases had been reported in around 150 countries and territories .", "evidence": "As of 14 March , over 150,000 cases have been reported in around 150 countries and territories ; more than 5,600 people have died from the disease and over 73,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee393b6c9e77c0008ccbd3c_3", "case_id": "5ee393b6c9e77c0008ccbd3c", "wiki_revision_id": "945521881", "label": "NOT ENOUGH INFO", "claim": "As of 14 March , 2020 more than 150,000 coronavirus cases had been reported in around 150 countries and territories .", "evidence": "As of 14 March , over 149,000 cases have been reported in around 150 countries and territories ; more than 5,600 people have died from the disease and over 73,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee393b6c9e77c0008ccbd3c_4", "case_id": "5ee393b6c9e77c0008ccbd3c", "wiki_revision_id": "945521881", "label": "SUPPORTS", "claim": "As of 14 March , 2020 more than 150,000 coronavirus cases had been reported in around 150 countries and territories .", "evidence": "As of 14 March , over 150,000 cases have been reported in around 150 countries and territories ; more than 5,600 people have died from the disease and over 73,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee3932dc9e77c0008ccb67c_1", "case_id": "5ee3932dc9e77c0008ccb67c", "wiki_revision_id": "945602869", "label": "NOT ENOUGH INFO", "claim": "Around 140 countries had reported fewer than 156,000 COVID-19 cases and less than 75,000 recoveries by March 14 .", "evidence": "As of 14 March , over 155,000 cases of COVID-19 have been reported in around 140 countries and territories ; more than 5,800 people have died from the disease and around 74,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee3932dc9e77c0008ccb67c_2", "case_id": "5ee3932dc9e77c0008ccb67c", "wiki_revision_id": "945602869", "label": "REFUTES", "claim": "Around 140 countries had reported fewer than 156,000 COVID-19 cases and less than 75,000 recoveries by March 14 .", "evidence": "As of 14 March , over 156,000 cases of COVID-19 have been reported in around 140 countries and territories ; more than 5,800 people have died from the disease and around 75,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee3932dc9e77c0008ccb67c_3", "case_id": "5ee3932dc9e77c0008ccb67c", "wiki_revision_id": "945602869", "label": "NOT ENOUGH INFO", "claim": "Around 140 countries had reported over 156,000 COVID-19 cases and more than 75,000 recoveries by March 14 , 2020 .", "evidence": "As of 14 March , over 155,000 cases of COVID-19 have been reported in around 140 countries and territories ; more than 5,800 people have died from the disease and around 74,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee3932dc9e77c0008ccb67c_4", "case_id": "5ee3932dc9e77c0008ccb67c", "wiki_revision_id": "945602869", "label": "SUPPORTS", "claim": "Around 140 countries had reported over 156,000 COVID-19 cases and more than 75,000 recoveries by March 14 , 2020 .", "evidence": "As of 14 March , over 156,000 cases of COVID-19 have been reported in around 140 countries and territories ; more than 5,800 people have died from the disease and around 75,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee3932dc9e77c0008ccb4ad_1", "case_id": "5ee3932dc9e77c0008ccb4ad", "wiki_revision_id": "945931184", "label": "NOT ENOUGH INFO", "claim": "Fewer than 78,500 coronavirus recuperations have been recorded around the world .", "evidence": "As of 16 March , more than 182,000 cases of the disease have been reported in over 160 countries and territories , resulting in around 78,000 recoveries and more than 7,100 deaths .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee3932dc9e77c0008ccb4ad_2", "case_id": "5ee3932dc9e77c0008ccb4ad", "wiki_revision_id": "945931184", "label": "REFUTES", "claim": "Fewer than 78,500 coronavirus recuperations have been recorded around the world .", "evidence": "As of 16 March , more than 182,000 cases of the disease have been reported in over 160 countries and territories , resulting in around 79,000 recoveries and more than 7,100 deaths .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
''' , 'generic')

[RouterAgent] Timeout: killing process

'generic'

In [7]:
router_agent_obj.classify_question('''{"unique_id": "5ee393b6c9e77c0008ccbd3c_2", "case_id": "5ee393b6c9e77c0008ccbd3c", "wiki_revision_id": "945521881", "label": "REFUTES", "claim": "As of 14 March , 2020 less than 150,000 coronavirus cases had been reported in around 150 countries and territories .", "evidence": "As of 14 March , over 150,000 cases have been reported in around 150 countries and territories ; more than 5,600 people have died from the disease and over 73,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee393b6c9e77c0008ccbd3c_3", "case_id": "5ee393b6c9e77c0008ccbd3c", "wiki_revision_id": "945521881", "label": "NOT ENOUGH INFO", "claim": "As of 14 March , 2020 more than 150,000 coronavirus cases had been reported in around 150 countries and territories .", "evidence": "As of 14 March , over 149,000 cases have been reported in around 150 countries and territories ; more than 5,600 people have died from the disease and over 73,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee393b6c9e77c0008ccbd3c_4", "case_id": "5ee393b6c9e77c0008ccbd3c", "wiki_revision_id": "945521881", "label": "SUPPORTS", "claim": "As of 14 March , 2020 more than 150,000 coronavirus cases had been reported in around 150 countries and territories .", "evidence": "As of 14 March , over 150,000 cases have been reported in around 150 countries and territories ; more than 5,600 people have died from the disease and over 73,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee3932dc9e77c0008ccb67c_1", "case_id": "5ee3932dc9e77c0008ccb67c", "wiki_revision_id": "945602869", "label": "NOT ENOUGH INFO", "claim": "Around 140 countries had reported fewer than 156,000 COVID-19 cases and less than 75,000 recoveries by March 14 .", "evidence": "As of 14 March , over 155,000 cases of COVID-19 have been reported in around 140 countries and territories ; more than 5,800 people have died from the disease and around 74,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee3932dc9e77c0008ccb67c_2", "case_id": "5ee3932dc9e77c0008ccb67c", "wiki_revision_id": "945602869", "label": "REFUTES", "claim": "Around 140 countries had reported fewer than 156,000 COVID-19 cases and less than 75,000 recoveries by March 14 .", "evidence": "As of 14 March , over 156,000 cases of COVID-19 have been reported in around 140 countries and territories ; more than 5,800 people have died from the disease and around 75,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee3932dc9e77c0008ccb67c_3", "case_id": "5ee3932dc9e77c0008ccb67c", "wiki_revision_id": "945602869", "label": "NOT ENOUGH INFO", "claim": "Around 140 countries had reported over 156,000 COVID-19 cases and more than 75,000 recoveries by March 14 , 2020 .", "evidence": "As of 14 March , over 155,000 cases of COVID-19 have been reported in around 140 countries and territories ; more than 5,800 people have died from the disease and around 74,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee3932dc9e77c0008ccb67c_4", "case_id": "5ee3932dc9e77c0008ccb67c", "wiki_revision_id": "945602869", "label": "SUPPORTS", "claim": "Around 140 countries had reported over 156,000 COVID-19 cases and more than 75,000 recoveries by March 14 , 2020 .", "evidence": "As of 14 March , over 156,000 cases of COVID-19 have been reported in around 140 countries and territories ; more than 5,800 people have died from the disease and around 75,000 have recovered .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee3932dc9e77c0008ccb4ad_1", "case_id": "5ee3932dc9e77c0008ccb4ad", "wiki_revision_id": "945931184", "label": "NOT ENOUGH INFO", "claim": "Fewer than 78,500 coronavirus recuperations have been recorded around the world .", "evidence": "As of 16 March , more than 182,000 cases of the disease have been reported in over 160 countries and territories , resulting in around 78,000 recoveries and more than 7,100 deaths .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
{"unique_id": "5ee3932dc9e77c0008ccb4ad_2", "case_id": "5ee3932dc9e77c0008ccb4ad", "wiki_revision_id": "945931184", "label": "REFUTES", "claim": "Fewer than 78,500 coronavirus recuperations have been recorded around the world .", "evidence": "As of 16 March , more than 182,000 cases of the disease have been reported in over 160 countries and territories , resulting in around 79,000 recoveries and more than 7,100 deaths .", "page": "2019–20 coronavirus pandemic", "revision_type": "real"}
''' , 'building_specific')

[RouterAgent] Timeout: killing process

'building_specific'

##### conversationalist agent test

In [2]:
messages = [
  {
    "role": "user",
    "timestamp": 1718961506.0,
    "added_to_database": 0,
    "content": "Hello, how can I help you today?",
    "classification": "general",
    "agent_answered": "N/A"
  },
  {
    "role": "assistant",
    "timestamp": 1718961506.0,
    "added_to_database": 0,
    "content": "I'm looking for information about the heating system in this building.",
    "classification": "building_specific",
    "agent_answered": "HVAC_Agent"
  },
  {
    "role": "user",
    "timestamp": 1718961506.0,
    "added_to_database": 0,
    "content": "Can you tell me what the current temperature is in conference room A?",
    "classification": "building_specific",
    "agent_answered": "N/A"
  },
  {
    "role": "assistant",
    "timestamp": 1718961506.0,
    "added_to_database": 0,
    "content": "The current temperature in conference room A is 22 degrees Celsius.",
    "classification": "building_specific",
    "agent_answered": "Sensor_Agent"
  },
  {
    "role": "user",
    "timestamp": 1718961506.0,
    "added_to_database": 0,
    "content": "Hi",
    "classification": "general",
    "agent_answered": "N/A"
  }
]

In [3]:
from src.agents.conversationalist_agent import ConversationalAgent

In [4]:
c_obj = ConversationalAgent()

INFO:src.agents.conversationalist_agent:Initializing ConversationalAgent.
INFO:src.agents.conversationalist_agent:Successfully loaded prompt from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\conversational_prompt.txt
INFO:src.agents.conversationalist_agent:ConversationalAgent prompt template loaded from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\conversational_prompt.txt
INFO:src.agents.conversationalist_agent:Conversational Model is gpt-4-32k and the api version is 2025-01-01-preview.
INFO:src.agents.conversationalist_agent:AzureOpenAI client initialized successfully.

In [7]:
res = c_obj.handle_conversational_input('Hi , what is this application', messages)

INFO:src.agents.conversationalist_agent:Received conversational input. Last message: 'Hi , what is this application...'
WARNING:src.agents.conversationalist_agent:Mismatch between 'last_message' ('Hi , what is this application...') and content of the last message in 'message_list' ('Hi...'). Ensuring 'last_message' is appended for the API call.
INFO:src.agents.conversationalist_agent:Sending final message to Azure OpenAI API for completion: 'Hi , what is this application...'
INFO:src.agents.conversationalist_agent:Successfully received response from Azure OpenAI.

Conversational Agent responded in 0.8367445468902588 seconds

In [8]:
res

"Hi there! This app helps you understand and improve your building's energy use. You can ask about heating, cooling, lighting, or other energy-related topics. How can I assist you today?"

#### vector database testing

In [18]:
from src.database.vector_client import VectorClient , VectorClientConfig

In [36]:
config = VectorClientConfig()
client = VectorClient(config)

results = client.query("How can I improve the energy class of a building ?")

Connection to Vector Database established.
Connection to Vector Database established.
✅ VectorClient initialized and connected.

In [37]:
results

[{'page_content': '\ufeffquestion;answer;date;category: Hur kan jag förbättra vår bostads energiklass?;För att förbättra byggnadens energiklass kan du se över om det är möjligt att förbättra byggnadens isolering\nNone: installera energieffektiva fönster och dörrar,uppgradera eller optimera värmesystemet,installera energieffektiva hushållsapparater och belysning,använda smarta hem-system för att styra och optimera energianvändningen,installera förnybara energikällor (t.ex. solceller),se över ventilationssystemet osv. Ett tips är att kolla byggnadens senaste energideklaration. Där får du relevanta förbättringsförslag från en certifierad energiexpert som hjälper dig att sänka energiförbrukningen för din byggnad.  ;2024-03-25;Energideklaration',
  'metadata': {'source': 'C:\\Users\\shada\\Documents\\spara-backend\\temp_folder_download\\qa-ekr.csv',
   'row': 917}},
 {'page_content': 'BRF  EnERgIEFFEKTI v12\n1 tRe Steg mot e FFektiva Re ene Rgianvän Dning\nJämför med andra\nNär man vet hur mycket energi som fastig-\nheten använder årligen är det intressant \natt jämföra energianvändningen med an -\ndra fastigheter för att se om den är ovan -\nligt hög eller låg (se tabell 2). SCB sam -\nmanställer statistik som publiceras årligen \ni en rapport som kan köpas från SCB eller \nhämtas via hemsidan www.scb.se. \nE-nyckeln (www.enyckeln.se) är en \nhemsida där fastighetsägare rapporterar \nsin egen energianvändning och samtidigt \nfår tillgång till ett stort jämförelsematerial \n(se också tabell 2). E-nyckeln kan ge en \nuppfattning om hur byggnaden ligger till \ni jämförelse med andra. \nDen nya lagen om energideklarering \ninnebär att alla ägare till flerbostadshus \nsenast vid utgången av år 2008 måste be -\nskriva sin energianvändning vilket kom -\nmer att underlätta en jämförelse med re -\nferensvärden.\nOm den egna energianvändningen \navviker markant från de genomsnittliga',
  'metadata': {'source': 'C:\\Users\\shada\\Documents\\spara-backend\\temp_folder_download\\EnergiBRFhandbokenSthlm.pdf',
   'page': 13}},
 {'page_content': '•\t\nAntal\tlägenheter\nEtt bra tillfälle att energieffektivisera är när fastigheten renoveras. \nExempel på hur energianvändningen i ett \nmindre flerbostadshus kan vara fördelad1 .',
  'metadata': {'source': 'C:\\Users\\shada\\Documents\\spara-backend\\temp_folder_download\\brfenergieffektiv_2015.pdf',
   'page': 12}},
 {'page_content': 'brf energieffektiv\n22\n2  effektivisera energianvändningen\nvilket medför att takutsprånget minskar, \nfönstren måste flyttas ut eller få bredare \nfönsterbleck och att fasaden hänger ut \növer\tgrunden.\tOm\thuset\ttilläggsisoler\nas\t\nmed\tcirka\t8\tcm\träcker\tdet\tvanligtvis\tmed\t\natt\tåtgärda\tfönstersmygarna.\tI\täldre\thus\t\nmed kulturhistor\niskt värde är det kanske \ninte\tlämpligt\tatt\ttilläggsisoler\na.\tI\tförsta\t\nhand kan man åtgärda gav elfasaderna ef-\ntersom lägenheterna på gaveln ofta är som \nkallast samtidigt som det finns få fönster \ndär.\t Til\nläggsisoleringen\t bör\t utföras\t av\t\nfackmän med g\noda referenser eftersom ett \nfelaktigt utförande kan medföra fuktpro-\nblem.\nFönster\nFönstren släpper in ljus och värme, men \nnär det är kallt ute släpper de även ut \nmycket värme från huset. Med rätt föns-\nter kan man hålla nere kostnaderna för \nenergi samtidigt som man får ett bättre \ninomhusklimat. Hur bra ett fönster isole-\nrar\tanges\tmed\tett\tU-värde\n,\tju\tlägre\tvärde',
  'metadata': {'source': 'C:\\Users\\shada\\Documents\\spara-backend\\temp_folder_download\\brfenergieffektiv_2015.pdf',
   'page': 23}},
 {'page_content': '1 tre steg mot effektivare energianvändning\n0 \n50 \n100 \n150 \n200 \n250 \n300 \n350 \n1980 1985 1990 1995 2000 2005 2010 2015 \nkWh/m2\n60 \nkWh/m2\n230 \nkWh/m2\n Mer än 30 års konsekvent energieffektivisering i BRF Bellman\n6  BRF  EnERgIEFFEKTI v\n•\tInjustering av \nvärme system. \n•\tIsolerat fönster-\nkarm/båge. \n•\tIsolerat rör  \ni källaren.\n•\tBytt pum-\npar och injusterat \nvärmesystemet enligt \nlågflödesmetoden.\n•\tInstallerat \ntermostatventiler. \n•\tReglering av \nfrånluftsfläktar.  \n•\tLågenergilampor.\nByte av \nalla vatten-\nkranar i \nlägen heterna.\nInstallation av \ndatoriserat styr- och \növervakningssystem \nför värme och varm-\nvattenproduktion.\nRenoverat tvätt-\nstugor, tvättmaski-\nnerna har automatik \nför att anpassa \nvattenmängden till \nmängden tvättgods.\nnytt data-\nsystem för styr-\nning av värme \noch varmvatten-\nproduktion.\nRensning, \nombyggnad \noch injus-\ntering av \nventilations-\nsystemet.\n•\tny ytter-\nbelysning med \nhögtrycks-\nnatriumlampor.\n•\tBytt garage-\nportar och \nmonterat \nmellanväggar i',
  'metadata': {'source': 'C:\\Users\\shada\\Documents\\spara-backend\\temp_folder_download\\brfenergieffektiv_2015.pdf',
   'page': 7}}]

In [10]:
results

[{'page_content': 'BRF  EnERgIEFFEKTI v22\n2 eFFektivi SeRa ene Rgianvän Dningen\nGenom att mäta upp inomhustempera -\nturen under uppvärmningssäsongen i ett \nantal lägenheter i olika delar av huset kan \nman avgöra om man har godtagbar balans \ni systemet. Man bör samtidigt se över om \nman håller en onödigt hög inomhustem -\nperatur. Genom att minska inomhustem-\nperaturen med en grad (exempelvis 21°C i \nstället för 22°C) minskar värmekostnader-\nna med cirka 5%. Om elementen (kallas \nradiatorer av fackfolk) i lägenheterna för-\nses med termostatventiler känner dessa av \nom det finns andra värmekällor och stry -\nper värmetillförseln. På så sätt kan man ta \ntill vara värmen från solinstrålning eller \nom det är många människor på besök i \nlägenheten.\nÅtgärda ventilationen\nVentilationen i ett hus ska bland annat \nvädra ut fukt och matos och tillföra frisk \nluft utan att ge drag. Det finns flera olika \ntyper av ventilationssystem som använts \nunder olika tidsepoker. Äldre hus har ofta',
  'metadata': {'source': 'C:\\Users\\shada\\Documents\\spara-backend\\temp_folder_download\\EnergiBRFhandbokenSthlm.pdf',
   'page': 23}},
 {'page_content': 'BRF Energieffektiv är en handbok för bostadsrätts-\nföreningar i flerbostadshus och mindre fastighetsägare som \nvill minska energikostnaderna och miljöpåverkan från sin \nenergianvändning.\nRing energirådgivaren i din kommun och få kostnadsfri råd-\ngivning om byte av uppvärmningsform och effektiva åtgärder!\nEnergirådgivningen är ett samarbete om opartisk \noch kostnadsfri rådgivning mellan 25 kommuner i \nStockholmsregionen. Verksamheten samordnas av KSL, \nKommunförbundet Stockholms Län.\nRing Energirådgivningen!',
  'metadata': {'source': 'C:\\Users\\shada\\Documents\\spara-backend\\temp_folder_download\\EnergiBRFhandbokenSthlm.pdf',
   'page': 63}},
 {'page_content': 'BRF  EnERgIEFFEKTI v40\n3 Byt ti LL BättRe väRmeSyStem\nbetalar för levererad mängd värme. Väljs \nett sådant alternativ består ”driften” av \nadministrativa uppgifter som att fördela \nvärmekostnaderna och ansvara för avtalet \nmed värmeleverantören. \nEn av de viktigaste frågorna för en bio-\nbränsleeldad anläggning är att säkerställa \nleverans av bränsle till rätt kvalitet. Ett \nlångsiktigt avtal om bränsleleverans med \nen uthållig leverantör kan vara ett sätt \natt säkerställa detta. Att skriva ett bräns -\nleleveransavtal för köp och leverans av \nbiobränslen är ett arbete som kräver kun -\nskaper om biobränslen och en god insikt \ni problematiken. Är man några stycken \nmindre bostadsföreningar som tillsam -\nmans tecknar ett större bränsleavtal kan \nman troligen pressa priserna. \nVid förbränning ombildas ungefär 1% \nav biobränslet till aska. Askutmatningen \nfrån pannan kan vara automatiserad. Om \nvärmeanläggningen har stoftavskiljning är \ndet en stor fördel om både stoft och bot -',
  'metadata': {'source': 'C:\\Users\\shada\\Documents\\spara-backend\\temp_folder_download\\EnergiBRFhandbokenSthlm.pdf',
   'page': 41}},
 {'page_content': 'brf energieffektiv\nBilligare och bättre miljö \ntack vare Bellman\nHur lyckades BRF Bellman i Uppsala minska sina ener-\ngikostnader? Det hela började när en av styrelsemed-\nlemmarna konstaterade att elementen var varma mitt i \nsommaren. Då bestämde de sig för att göra något åt för-\neningens energianvändning. Sedan dess har man genom \nett systematiskt arbete sänkt uppvärmningskostnaderna \noch underhållskostnaderna för fastigheterna.\nBostadsrättsföreningen Bellman ligger \ni\tUppsala\toch\tbestår\tav\t17\thus\tmed\tsam-\nmanlagt\t396\tlägenheter.\tHusen\tär\tbyggda\t\n1967–1969\toch\tvärms\tmed\tbergvärme.\tStor\n-\nleken på lägenheterna i föreningen varierar \nfrån\tettor\tpå\t29\tm²\ttill\tfemmor\tpå\t113\tm².\t\nRedan\ti\tbörjan\tav\t1980-talet\tinsåg\tman\t\ni föreningen att man var t\nvungen att göra \nnågot för att minska energikostnaderna \noch med ett långsiktigt arbete har man \nlyckats mycket bra. Föreningen sparar \nca 5,5 miljoner kr per år jämfört med om \nman inte hade genomfört några åtgär-',
  'metadata': {'source': 'C:\\Users\\shada\\Documents\\spara-backend\\temp_folder_download\\brfenergieffektiv_2015.pdf',
   'page': 5}},
 {'page_content': 'brf energieffektiv\n35\nbyt till bättre värmesystem 3\ntagit fram en frivillig kvalitetsmärkning \nav\tfjärrvär\nmeleverantörerna,\t»Reko\tfjärr-\nvär\nme«.\tFör\tatt\tfå\tanvända\tmärkningen\t\nmåste lev\nerantören leva upp till en rad \nuppsatta krav, bl.a. hur ändringar av priser \nfår genomföras och öppenhet vad gäller \nverksamheten och ekonomin. \nAnslutning\nIdag\tfinns\tfjärrvär\nmen\ti\talla\tstörre\torter\t\noch ut\nbyggnaden håller en stadig takt. \nUngefär\t80%\tav\talla\tflerbostadshus\tvärms\t\nmed fjärrvär\nme. Eftersom kostnader för \nkulvertdragning och värmeförluster ökar \nmed ökande avstånd finns begränsningar \nför hur stort avståndet kan vara mellan \nkunderna.\tKontakta\tdet\tlokala\tfjärrvär\n-\nmebolaget för att få reda på om det finns \nmöjlighet att ansluta huset till fjärrvärme-\nnätet. \nYtbehov\nFjärrvärme är, med undantag för direkt-\nverkande el, det minst utrymmeskrävande \nuppvärmningssättet eftersom den enda \nutrustning som krävs är värmeväxlare för \nvärme och varmvatten, samt styrventiler.',
  'metadata': {'source': 'C:\\Users\\shada\\Documents\\spara-backend\\temp_folder_download\\brfenergieffektiv_2015.pdf',
   'page': 36}}]

In [11]:
content_from_doc = ' '.join(i['page_content'] for i in results)

#### generic agent testing

In [1]:
messages = [
  {
    "role": "user",
    "timestamp": 1718961506.0,
    "added_to_database": 0,
    "content": "Hello, how can I help you today?",
    "classification": "general",
    "agent_answered": "N/A"
  },
  {
    "role": "assistant",
    "timestamp": 1718961506.0,
    "added_to_database": 0,
    "content": "I'm looking for information about the heating system in this building.",
    "classification": "building_specific",
    "agent_answered": "HVAC_Agent"
  },
  {
    "role": "user",
    "timestamp": 1718961506.0,
    "added_to_database": 0,
    "content": "Can you tell me what the current temperature is in conference room A?",
    "classification": "building_specific",
    "agent_answered": "N/A"
  },
  {
    "role": "assistant",
    "timestamp": 1718961506.0,
    "added_to_database": 0,
    "content": "The current temperature in conference room A is 22 degrees Celsius.",
    "classification": "building_specific",
    "agent_answered": "Sensor_Agent"
  },
  {
    "role": "user",
    "timestamp": 1718961506.0,
    "added_to_database": 0,
    "content": "what is energy class?",
    "classification": "general",
    "agent_answered": "N/A"
  }
]

In [2]:
from src.agents.generic_agent import GenericAgent

In [3]:
last_message = 'what is energy class?'

In [4]:
ga_obj = GenericAgent()

2025-06-21 16:17:10,675 - azure.core.pipeline.policies.http_logging_policy - INFO - Request URL: 'https://sparaknowledgebase.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.9.0 Python/3.12.7 (Windows-11-10.0.26100-SP0)'
No body was attached to the request
2025-06-21 16:17:10,853 - azure.core.pipeline.policies.http_logging_policy - INFO - Response status: 200
Response headers:
    'Content-Length': '1709'
    'Date': 'Sat, 21 Jun 2025 14:17:01 GMT'
    'Content-Type': 'application/json'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-gatewayversion': 'REDACTED'
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'Content-Location': 'REDACTED'
2025-06-21 16:17:11,492 - azure.core.pipeline.policies.http_logging_policy - INFO - Request URL: 'https://sparaknowledgebase-swedencentral.documents.azure.com:443/dbs/SPARA/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-consistency-level': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.9.0 Python/3.12.7 (Windows-11-10.0.26100-SP0)'
No body was attached to the request
2025-06-21 16:17:11,684 - azure.core.pipeline.policies.http_logging_policy - INFO - Response status: 200
Response headers:
    'Content-Length': '160'
    'Date': 'Sat, 21 Jun 2025 14:17:02 GMT'
    'Content-Type': 'application/json'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-gatewayversion': 'REDACTED'
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-activity-id': 'REDACTED'
    'x-ms-last-state-change-utc': 'REDACTED'
    'etag': '"00002a06-0000-4700-0000-685045ec0000"'
    'x-ms-resource-quota': 'REDACTED'
    'x-ms-resource-usage': 'REDACTED'
    'x-ms-schemaversion': 'REDACTED'
    'lsn': 'REDACTED'
    'x-ms-request-charge': 'REDACTED'
    'x-ms-xp-role': 'REDACTED'
    'x-ms-global-Committed-lsn': 'REDACTED'
    'x-ms-number-of-read-regions': 'REDACTED'
    'x-ms-item-lsn': 'REDACTED'
    'x-ms-transport-request-id': 'REDACTED'
    'x-ms-cosmos-llsn': 'REDACTED'
    'x-ms-cosmos-item-llsn': 'REDACTED'
    'x-ms-session-token': 'REDACTED'
    'x-ms-request-duration-ms': 'REDACTED'
    'x-ms-serviceversion': 'REDACTED'
    'x-ms-cosmos-internal-partition-id': 'REDACTED'
    'Content-Location': 'REDACTED'
2025-06-21 16:17:11,687 - azure.core.pipeline.policies.http_logging_policy - INFO - Request URL: 'https://sparaknowledgebase-swedencentral.documents.azure.com:443/dbs/SPARA/colls/documentstorage/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-consistency-level': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.9.0 Python/3.12.7 (Windows-11-10.0.26100-SP0)'
No body was attached to the request
2025-06-21 16:17:11,726 - azure.core.pipeline.policies.http_logging_policy - INFO - Response status: 200
Response headers:
    'Content-Length': '864'
    'Date': 'Sat, 21 Jun 2025 14:17:02 GMT'
    'Content-Type': 'application/json'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-gatewayversion': 'REDACTED'
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-activity-id': 'REDACTED'
    'x-ms-last-state-change-utc': 'REDACTED'
    'etag': '"00002c06-0000-4700-0000-685045ec0000"'
    'x-ms-schemaversion': 'REDACTED'
    'collection-partition-index': 'REDACTED'
    'collection-service-index': 'REDACTED'
    'lsn': 'REDACTED'
    'x-ms-request-charge': 'REDACTED'
    'x-ms-alt-content-path': 'REDACTED'
    'x-ms-content-path': 'REDACTED'
    'x-ms-documentdb-partitionkeyrangeid': 'REDACTED'
    'x-ms-xp-role': 'REDACTED'
    'x-ms-global-Committed-lsn': 'REDACTED'
    'x-ms-number-of-read-regions': 'REDACTED'
    'x-ms-item-lsn': 'REDACTED'
    'x-ms-transport-request-id': 'REDACTED'
    'x-ms-cosmos-llsn': 'REDACTED'
    'x-ms-cosmos-item-llsn': 'REDACTED'
    'x-ms-session-token': 'REDACTED'
    'x-ms-request-duration-ms': 'REDACTED'
    'x-ms-serviceversion': 'REDACTED'
    'x-ms-cosmos-physical-partition-id': 'REDACTED'
    'x-ms-cosmos-max-content-length': 'REDACTED'
    'x-ms-cosmos-internal-partition-id': 'REDACTED'
    'Content-Location': 'REDACTED'
2025-06-21 16:17:11,755 - src.agents.generic_agent - INFO - Successfully loaded prompt from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\generic_prompt.txt
2025-06-21 16:17:11,756 - src.agents.generic_agent - INFO - GenericAgent prompt template loaded from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\generic_prompt.txt
2025-06-21 16:17:11,757 - src.agents.generic_agent - INFO - Generic Model is gpt-4o-mini and the api version is 2025-01-01-preview.

Connection to Vector Database established.
✅ VectorClient initialized and connected.

2025-06-21 16:17:12,060 - src.agents.generic_agent - INFO - AzureOpenAI client initialized successfully.

In [5]:
result = ga_obj.handle_generic_input(last_message , messages)

2025-06-21 16:17:12,477 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:12,496 - azure.core.pipeline.policies.http_logging_policy - INFO - Request URL: 'https://sparaknowledgebase-swedencentral.documents.azure.com:443/dbs/SPARA/colls/documentstorage/docs/'
Request method: 'POST'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-consistency-level': 'REDACTED'
    'x-ms-documentdb-isquery': 'REDACTED'
    'Content-Type': 'application/query+json'
    'x-ms-session-token': 'REDACTED'
    'x-ms-documentdb-query-enablecrosspartition': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'x-ms-cosmos-correlated-activityid': 'REDACTED'
    'x-ms-cosmos-intended-collection-rid': 'REDACTED'
    'Content-Length': '66164'
    'User-Agent': 'azsdk-python-cosmos/4.9.0 Python/3.12.7 (Windows-11-10.0.26100-SP0)'
A body is sent with the request
2025-06-21 16:17:12,573 - azure.core.pipeline.policies.http_logging_policy - INFO - Response status: 400
Response headers:
    'Date': 'Sat, 21 Jun 2025 14:17:03 GMT'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'x-ms-activity-id': 'REDACTED'
    'x-ms-substatus': 'REDACTED'
    'Server': 'Compute'
    'x-ms-gatewayversion': 'REDACTED'
2025-06-21 16:17:12,576 - azure.core.pipeline.policies.http_logging_policy - INFO - Request URL: 'https://sparaknowledgebase-swedencentral.documents.azure.com:443/dbs/SPARA/colls/documentstorage/docs/'
Request method: 'POST'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-consistency-level': 'REDACTED'
    'x-ms-documentdb-isquery': 'REDACTED'
    'Content-Type': 'application/json'
    'x-ms-session-token': 'REDACTED'
    'x-ms-cosmos-is-query-plan-request': 'REDACTED'
    'x-ms-cosmos-supported-query-features': 'REDACTED'
    'x-ms-cosmos-query-version': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '66164'
    'User-Agent': 'azsdk-python-cosmos/4.9.0 Python/3.12.7 (Windows-11-10.0.26100-SP0)'
A body is sent with the request
2025-06-21 16:17:12,620 - azure.core.pipeline.policies.http_logging_policy - INFO - Response status: 200
Response headers:
    'Content-Length': '889'
    'Date': 'Sat, 21 Jun 2025 14:17:03 GMT'
    'Content-Type': 'application/json'
    'Server': 'Compute'
    'x-ms-gatewayversion': 'REDACTED'
2025-06-21 16:17:12,622 - azure.core.pipeline.policies.http_logging_policy - INFO - Request URL: 'https://sparaknowledgebase-swedencentral.documents.azure.com:443/dbs/SPARA/colls/documentstorage/pkranges/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-consistency-level': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.9.0 Python/3.12.7 (Windows-11-10.0.26100-SP0)'
No body was attached to the request
2025-06-21 16:17:12,644 - azure.core.pipeline.policies.http_logging_policy - INFO - Response status: 200
Response headers:
    'Content-Length': '392'
    'Date': 'Sat, 21 Jun 2025 14:17:03 GMT'
    'Content-Type': 'application/json'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-gatewayversion': 'REDACTED'
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-activity-id': 'REDACTED'
    'x-ms-last-state-change-utc': 'REDACTED'
    'x-ms-schemaversion': 'REDACTED'
    'lsn': 'REDACTED'
    'x-ms-item-count': 'REDACTED'
    'x-ms-alt-content-path': 'REDACTED'
    'x-ms-content-path': 'REDACTED'
    'x-ms-xp-role': 'REDACTED'
    'x-ms-global-Committed-lsn': 'REDACTED'
    'x-ms-number-of-read-regions': 'REDACTED'
    'x-ms-transport-request-id': 'REDACTED'
    'x-ms-cosmos-llsn': 'REDACTED'
    'x-ms-session-token': 'REDACTED'
    'x-ms-request-duration-ms': 'REDACTED'
    'x-ms-serviceversion': 'REDACTED'
    'x-ms-cosmos-internal-partition-id': 'REDACTED'
    'Content-Location': 'REDACTED'
2025-06-21 16:17:12,646 - azure.core.pipeline.policies.http_logging_policy - INFO - Request URL: 'https://sparaknowledgebase-swedencentral.documents.azure.com:443/dbs/SPARA/colls/documentstorage/docs/'
Request method: 'POST'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-consistency-level': 'REDACTED'
    'x-ms-documentdb-isquery': 'REDACTED'
    'Content-Type': 'application/query+json'
    'x-ms-session-token': 'REDACTED'
    'x-ms-documentdb-query-enablecrosspartition': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'x-ms-documentdb-partitionkeyrangeid': 'REDACTED'
    'x-ms-cosmos-correlated-activityid': 'REDACTED'
    'x-ms-cosmos-intended-collection-rid': 'REDACTED'
    'Content-Length': '66320'
    'User-Agent': 'azsdk-python-cosmos/4.9.0 Python/3.12.7 (Windows-11-10.0.26100-SP0)'
A body is sent with the request
2025-06-21 16:17:14,014 - azure.core.pipeline.policies.http_logging_policy - INFO - Response status: 200
Response headers:
    'Content-Length': '1365817'
    'Date': 'Sat, 21 Jun 2025 14:17:03 GMT'
    'Content-Type': 'application/json'
    'Server': 'Compute'
    'x-ms-gatewayversion': 'REDACTED'
    'x-ms-activity-id': 'REDACTED'
    'x-ms-last-state-change-utc': 'REDACTED'
    'x-ms-resource-quota': 'REDACTED'
    'x-ms-resource-usage': 'REDACTED'
    'x-ms-schemaversion': 'REDACTED'
    'lsn': 'REDACTED'
    'x-ms-item-count': 'REDACTED'
    'x-ms-request-charge': 'REDACTED'
    'x-ms-alt-content-path': 'REDACTED'
    'x-ms-content-path': 'REDACTED'
    'x-ms-documentdb-partitionkeyrangeid': 'REDACTED'
    'x-ms-xp-role': 'REDACTED'
    'x-ms-cosmos-query-execution-info': 'REDACTED'
    'x-ms-global-Committed-lsn': 'REDACTED'
    'x-ms-number-of-read-regions': 'REDACTED'
    'x-ms-transport-request-id': 'REDACTED'
    'x-ms-cosmos-llsn': 'REDACTED'
    'x-ms-session-token': 'REDACTED'
    'x-ms-request-duration-ms': 'REDACTED'
    'x-ms-serviceversion': 'REDACTED'
    'x-ms-cosmos-is-partition-key-delete-pending': 'REDACTED'
    'x-ms-cosmos-physical-partition-id': 'REDACTED'
    'x-ms-cosmos-internal-partition-id': 'REDACTED'
2025-06-21 16:17:14,139 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:14,241 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:14,332 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:14,424 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:14,530 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:14,641 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:14,918 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:15,023 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:15,129 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:15,239 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:15,341 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:15,458 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:15,569 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:15,673 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:15,766 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:15,873 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:15,985 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:16,094 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:16,209 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:16,324 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15 "HTTP/1.1 200 OK"
2025-06-21 16:17:16,353 - src.agents.generic_agent - INFO - Received generic input. Last message: 'what is energy class?...'
2025-06-21 16:17:16,354 - src.agents.generic_agent - INFO - Last message ('what is energy class?...') matches content of last item in message_list.
2025-06-21 16:17:16,354 - src.agents.generic_agent - INFO - Sending final message to Azure OpenAI API for completion: 'what is energy class?...'
2025-06-21 16:17:17,524 - httpx - INFO - HTTP Request: POST https://kthapikey.openai.azure.com/openai/deployments/gpt-4o-mini/chat/completions?api-version=2025-01-01-preview "HTTP/1.1 200 OK"
2025-06-21 16:17:17,539 - src.agents.generic_agent - INFO - Successfully received response from Azure OpenAI.

Generic Agent responded in 5.470415353775024 seconds

In [6]:
result

"Energy class refers to a classification system that indicates the energy efficiency of a building or property. It is often determined based on the building's energy consumption, insulation, heating systems, and other factors that contribute to its overall energy performance. In Sweden, energy classes are part of the Energideklaration, which provides an overview of a building's energy use and helps identify potential improvements for energy efficiency. \n\nFor example, a building with a higher energy class (e.g., A or B) is more energy-efficient compared to one with a lower class (e.g., D or E). This classification can help property owners and tenants understand their energy costs and environmental impact, guiding them in making informed decisions about energy use and potential upgrades."

#### routing agent with llama 2

In [1]:
from azure.ai.inference import ChatCompletionsClient
from azure.ai.inference.models import SystemMessage, UserMessage
from azure.core.credentials import AzureKeyCredential
from typing import Dict, Optional, Union
import os
from dotenv import load_dotenv
import multiprocessing
import sys # Import sys for checking if BaseAgent exists
import time
# Load environment variables from .env file
load_dotenv()

True

In [2]:
import logging

In [3]:
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    # handlers=[
    #     logging.FileHandler("router_agent.log"), # Log to a file
    #     logging.StreamHandler(sys.stdout)       # Log to console
    # ]
)
# Get a specific logger for this module
logger = logging.getLogger(__name__)

In [4]:
required_env_vars = {
    "AZURE_INFERENCE_SDK_ENDPOINT": "Azure OpenAI endpoint",
    "DEPLOYMENT_NAME": "Deployment name for the router model",
    "AZURE_INFERENCE_SDK_KEY": "OpenAI API key"
}

for var, desc in required_env_vars.items():
    if not os.getenv(var):
        logger.error(f"Missing required environment variable: {var} ({desc}). Exiting.")
        # In a real application, you might raise an exception or exit more gracefully.
        # For now, we'll set these to None and handle potential errors in client creation.
        globals()[var.lower()] = None # Set corresponding variable to None
        sys.exit(1) # Exit if critical variables are missing

endpoint = os.getenv("AZURE_INFERENCE_SDK_ENDPOINT")
model_name  = os.getenv("DEPLOYMENT_NAME")
subscription_key = os.getenv("AZURE_INFERENCE_SDK_KEY")
logger.info(f"Router Model is {model_name }")
client = None
try:
    client = ChatCompletionsClient(endpoint=endpoint, credential=AzureKeyCredential(subscription_key))
    logger.info("AzureOpenAI client for RouterAgent initialized successfully.")
except Exception as e:
    logger.critical(f"Failed to initialize Azure client for RouterAgent: {e}")
    # Depending on your application's tolerance for this, you might exit or
    # ensure subsequent calls gracefully handle the missing client.
    sys.exit(1) # Exit if client cannot be initialize

2025-07-23 11:48:19,139 - __main__ - INFO - Router Model is Llama-3.3-70B-Instruct
2025-07-23 11:48:19,592 - __main__ - INFO - AzureOpenAI client for RouterAgent initialized successfully.

In [5]:
prompt_template = '''
You are a classification assistant for a building advice system.  
Classify the user's message into **one** of the following categories:

- **conversational**  
  Messages that are greetings, small‑talk, or asking what the application is/does (not seeking building data).  
  Examples:  
  • “Hi, what is this application?”  
  • “Hello there!”  
  • “Can you tell me who built you?”

- **generic**  
  General energy‑oriented questions not tied to any specific building or group of buildings.  
  Examples:  
  • “What does energy class B mean?”  
  • “How is primary energy calculated in Sweden?”  
  • “Which Swedish law sets the limits for energy classes?”

- **building_specific**  
  Questions or requests about **one** identifiable building (by name, address, BRF, or unique ID).  
  Examples:  
  • “What is the energy class of my building at 123 Main Street?”  
  • “Show the ventilation report for BRF Solgläntan.”  
  • “Estimate heating costs for building UUID abc‑123.”

- **cluster**  
  Questions or requests about **multiple** buildings, a group of buildings, or a defined area.  
  Examples:  
  • “Compare the heating usage of all BRFs in Södermalm.”  
  • “Which buildings built before 1970 in Gothenburg have an A‑grade energy certificate?”  
  • “List the ten worst‑performing buildings in our portfolio.”

**Output → Provide only the category name.**

Example:

Input: What is the energy class of my building at 123 Main Street?  
Output: building_specific

'''

In [6]:
import time

In [7]:
start_time = time.time()

In [8]:
user_message = "How can I improve energy class of my building ?"

In [ ]:
completion = client.complete(
                    messages=[
                        SystemMessage(content=prompt_template),
                        UserMessage(content=user_message)
                    ],
                    temperature=0.01,
                    model = model_name,
                    max_tokens=1000
                    )

2025-07-23 11:49:01,666 - azure.core.pipeline.policies.http_logging_policy - INFO - Request URL: 'https://sparallama.services.ai.azure.com/models/chat/completions?api-version=REDACTED'
Request method: 'POST'
Request headers:
    'Content-Type': 'application/json'
    'Content-Length': '1990'
    'Accept': 'application/json'
    'x-ms-client-request-id': '431e9ee8-67aa-11f0-a33b-9c297600eb63'
    'api-key': 'REDACTED'
    'User-Agent': 'azsdk-python-ai-inference/1.0.0b9 Python/3.12.7 (Windows-11-10.0.26100-SP0)'
    'Authorization': 'REDACTED'
A body is sent with the request

In [18]:
completion.choices[0].message.content

'building_specific'

#### hammarby data integration

In [1]:
pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\shada\documents\envsparabackend\lib\site-packages (2.9.10)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
from src.database.hammarby_data import *

In [2]:
# ---- 1) Basic connectivity ----
info = test_connection()
print("Connection info:", info)

Connection info: {'version': 'PostgreSQL 17.4 on x86_64-windows, compiled by msvc-19.42.34436, 64-bit', 'database': 'hammarbydata'}

In [3]:
df = query_executor("SELECT 1::int AS ok;")
print("SELECT -> DataFrame shape:", getattr(df, "shape", None))
display(df)

SELECT -> DataFrame shape: (1, 1)

c:\Users\shada\Documents\spara-backend\src\database\hammarby_data.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn, params=params)

   ok
0   1

In [2]:
from src.database.hammarby_data import query_executor, test_connection

print("Connection check:", test_connection())

# 3) Find real FK relationships in your DB (non-system schemas)
fk_sql = """
SELECT
  con.conname                               AS constraint_name,
  nsp_f.nspname                              AS fk_schema,
  rel_f.relname                              AS fk_table,
  att_f.attname                              AS fk_column,
  nsp_p.nspname                              AS pk_schema,
  rel_p.relname                              AS pk_table,
  att_p.attname                              AS pk_column,
  rn.ord                                     AS col_order
FROM pg_constraint con
JOIN pg_class rel_f       ON rel_f.oid = con.conrelid
JOIN pg_namespace nsp_f    ON nsp_f.oid = rel_f.relnamespace
JOIN pg_class rel_p       ON rel_p.oid = con.confrelid
JOIN pg_namespace nsp_p    ON nsp_p.oid = rel_p.relnamespace
JOIN LATERAL unnest(con.conkey)  WITH ORDINALITY AS fk(attnum, ord) ON TRUE
JOIN LATERAL unnest(con.confkey) WITH ORDINALITY AS pk(attnum, ord) ON fk.ord = pk.ord
JOIN pg_attribute att_f    ON att_f.attrelid = rel_f.oid AND att_f.attnum = fk.attnum
JOIN pg_attribute att_p    ON att_p.attrelid = rel_p.oid AND att_p.attnum = pk.attnum
JOIN LATERAL (SELECT fk.ord) rn ON TRUE
WHERE con.contype = 'f'
  AND nsp_f.nspname NOT IN ('pg_catalog','information_schema')
  AND nsp_p.nspname NOT IN ('pg_catalog','information_schema')
ORDER BY constraint_name, col_order;
"""
fk_df = query_executor(fk_sql)
print(f"Found FK rows: {0 if fk_df is None else len(fk_df)}")

def qident(*parts):
    """Quote identifiers safely: ("schema","table") -> "schema"."table" """
    return ".".join([f'"{p}"' for p in parts])

def pick_cols(schema, table, n=4):
    sql = """
    SELECT column_name
    FROM information_schema.columns
    WHERE table_schema=%s AND table_name=%s
    ORDER BY ordinal_position
    LIMIT %s;
    """
    cols = query_executor(sql, params=(schema, table, n))
    return [r for r in (cols["column_name"].tolist() if hasattr(cols, "columns") else [])]

if fk_df is not None and len(fk_df) > 0:
    # Group by one FK and build a multi-column join if needed
    grp = fk_df.groupby("constraint_name").head(1000)  # keep shape
    first_fk = grp.iloc[0]["constraint_name"]
    g = fk_df[fk_df["constraint_name"] == first_fk].sort_values("col_order")

    fk_schema = g.iloc[0]["fk_schema"]
    fk_table  = g.iloc[0]["fk_table"]
    pk_schema = g.iloc[0]["pk_schema"]
    pk_table  = g.iloc[0]["pk_table"]

    # Build ON clauses for all columns in this FK
    on_clauses = []
    for _, r in g.iterrows():
        on_clauses.append(f'{qident("f", r["fk_column"])} = {qident("p", r["pk_column"])}')
    on_sql = " AND ".join(on_clauses)

    # Choose a few columns to display from each side
    f_cols = pick_cols(fk_schema, fk_table, 4)
    p_cols = pick_cols(pk_schema, pk_table, 4)
    f_sel  = ", ".join([qident("f", c) + f' AS "f.{c}"' for c in f_cols]) if f_cols else "f.*"
    p_sel  = ", ".join([qident("p", c) + f' AS "p.{c}"' for c in p_cols]) if p_cols else "p.*"

    join_sql = f"""
    SELECT {f_sel}{", " if f_sel and p_sel else ""}{p_sel}
    FROM {qident(fk_schema, fk_table)} AS f
    JOIN {qident(pk_schema, pk_table)} AS p
      ON {on_sql}
    LIMIT 20;
    """
    print("Running JOIN on:", f'{fk_schema}.{fk_table}  →  {pk_schema}.{pk_table}')
    res = query_executor(join_sql)
    display(res)
else:
    # No FKs → sample a user table
    tables_sql = """
    SELECT table_schema, table_name
    FROM information_schema.tables
    WHERE table_schema NOT IN ('pg_catalog','information_schema')
    ORDER BY table_schema, table_name
    LIMIT 1;
    """
    tdf = query_executor(tables_sql)
    if tdf is not None and len(tdf) > 0:
        s, t = tdf.iloc[0]["table_schema"], tdf.iloc[0]["table_name"]
        sample_sql = f'SELECT * FROM {qident(s,t)} LIMIT 20;'
        print("No FKs found. Sampling:", f"{s}.{t}")
        display(query_executor(sample_sql))
    else:
        print("No user tables found in this database.")

Connection check: {'version': 'PostgreSQL 17.4 on x86_64-windows, compiled by msvc-19.42.34436, 64-bit', 'database': 'hammarbydata'}

c:\Users\shada\Documents\spara-backend\src\database\hammarby_data.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn, params=params)
c:\Users\shada\Documents\spara-backend\src\database\hammarby_data.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn, params=params)

Found FK rows: 6
Running JOIN on: dbo.electricity_enduses  →  dbo.buildings

,f.id,f.electricity_used_for_property,f.electricity_used_for_property_heating,f.electricity_used_for_taphotwater,p.building_id,p.numberOfApartments,p.numberOfTenants,p.netAreaResidential
0,1,True,True,True,1,110,8,8755
1,2,True,True,True,2,5,10,500
2,3,True,False,False,3,90,1,9999
3,4,True,True,True,4,50,0,3319
4,5,True,False,False,5,50,35,9999
5,6,True,False,False,6,94,3,9999
6,7,True,False,False,7,37,0,9999
7,8,True,False,False,8,226,10,9999
8,9,True,False,False,9,114,4,12397
9,10,True,False,False,10,100,5,9999
10,11,True,False,False,11,82,0,99999

In [5]:
query_executor('select * from dbo.users')

    user_id                            email       password  building_id
0         1                 leo@locallife.se  LocalLife1234            1
1         3                aram@locallife.se   AramTest1234            2
2         4             hossein@locallife.se         123456            1
3         5              andrew@locallife.se           test            1
4         7  rolf.berglund@brfsjoportalen.se     7696076475            3
5         8           janfranson@outlook.com     7696062533            1
6         9                jimmy@odenholm.se     7696162234            6
7        10        FranssonTomas@hotmail.com     7164390630            4
8        11         rolf.ostman@brfsundet.se     7696070163            7
9        12                      rd@tilde.se     7696291223            8
10       13     deniz.onder@bengtdahlgren.se     7696193809           10
11       14             pnordstrom@stosn.com     7696076459           11
12       15       johan.g.holmberg@gmail.com     7696062913            9
13       16                    oleksi@kth.se         1q2w3e            1

#### Parsed intent testing

In [1]:
from src.agents.parse_intent_agent import ParseIntentAgent

# Create an instance
agent = ParseIntentAgent()

INFO:src.agents.parse_intent_agent:Azure ChatCompletionsClient initialized for ParseIntentAgent.
c:\Users\shada\Documents\spara-backend\src\database\sql_client.py:30: DtypeWarning: Columns (22,80) have mixed types. Specify dtype option on import or set low_memory=False.
  self._df = pd.read_csv(self._path)

Connection to Vector Database established.

INFO:src.agents.openai_agent:Initializing OpenAIResponseAgent.
INFO:src.agents.openai_agent:Prompt loaded successfully from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\openai_response_prompt.txt

Connection to Vector Database established.
✅ VectorClient initialized and connected.

INFO:src.agents.openai_agent:Azure OpenAI client initialized successfully for response agent.
c:\Users\shada\Documents\spara-backend\src\database\hammarby_data.py:95: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('''select address from dbo.buildingaddress ; ''', conn,)['address'].to_list()

In [4]:
state = {
    "messages": [
        {"role": "user", "content": "How can i improve the energy class of my building , Artemisgatan 17 ?"}
    ]
}

In [5]:
updated_state = agent(state)
print(updated_state['context']["parsed_intent"])  # e.g., 'simulations'

INFO:src.agents.parse_intent_agent:LLM classification result: {"parsed_intent":"SQL database ; vector database","address":"Artemisgatan 17","ambigious":false}

SQL database ; vector database

In [6]:
updated_state

{'messages': [{'role': 'user',
   'content': 'How can i improve the energy class of my building , Artemisgatan 17 ?'}],
 'context': {'parsed_intent': 'SQL database ; vector database',
  'address': 'Artemisgatan 17',
  'ambigious': False}}

In [ ]:
state = {
    "messages": [
        {"role": "user", "content": "What will be the saved co2?"}
    ]
}
updated_state = agent(state)
print(updated_state["parsed_intent"])  # e.g., 'simulations'

INFO:src.agents.parse_intent_agent:LLM classification result: intent: simulations

simulations

In [2]:
state = {
    "messages": [
        {"role": "user", "content": "I live in Tknigringen 10B"}
    ]
}
updated_state = agent(state)
print(updated_state["parsed_intent"])  # e.g., 'simulations'

INFO:src.agents.parse_intent_agent:LLM classification result: intent: address

address

#### test_building flow

In [1]:
from src.agents.building_flow_graph import build_building_flow_graph

In [2]:
session_store = {}

def get_session_state(thread_id):
    return session_store.get(thread_id, {"history": []})

def update_session_state(thread_id, session_state):
    session_store[thread_id] = session_state

In [7]:

class BuildingAgent:
    def __init__(self):
        self.graph = build_building_flow_graph()

    def handle_building_query(self, last_message, messages, metadata, thread_id, _session_state=None):
        session_state = _session_state or get_session_state(thread_id)

        initial_state = {
            "thread_id": thread_id,
            "messages": messages,
            "metadata": metadata,
            "last_message": last_message,
            "session_state": session_state,
        }

        try:
            final_state = self.graph.invoke(initial_state)
        except Exception as e:
            return {
                "content": f"An error occurred while handling your building-related request: {e}",
                "agent_answered": "building",
                "classification": "building_specific"
            }

        # Save session_state back to Redis
        new_state = final_state.get("session_state", session_state)
        update_session_state(thread_id, new_state)

        response = (
            final_state.get("final_response")
            or final_state.get("response")
            or final_state.get("prompt")
            or "No output was generated."
        )

        return {
            "content": response,
            "agent_answered": "building",
            "classification": "building_specific" , 
            "response" : response
        }

In [8]:
agent = BuildingAgent()

In [9]:
last_message = "What is the co2 saved?"
messages = [
    {"role": "user", "content": last_message}
]
metadata = {"address": "Teknigringen 10B"}
thread_id = "thread_abc"

# Call the handler
output = agent.handle_building_query(
    last_message=last_message,
    messages=messages,
    metadata=metadata,
    thread_id=thread_id
)

print("Agent response:", output["content"])
print("Session state:", session_store[thread_id])

Entered entry_point
Running understand_context
Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent
Agent response: Summary of: Generic SQL result
Session state: {'history': ['What is the co2 saved?', 'What is the co2 saved?']}

In [10]:
output

{'content': 'Summary of: Generic SQL result',
 'agent_answered': 'building',
 'classification': 'building_specific',
 'response': 'Summary of: Generic SQL result'}

#### test parse agent

In [3]:
from src.agents.building_flow_graph import build_building_flow_graph

def test_understand_context_node():
    graph = build_building_flow_graph()

    # Example test state with a user message
    state = {
        "thread_id": "test_thread_1",
        "messages": [{"role": "user", "content": "What is my building energy class?"}],
        "metadata": {},
        "session_state": {},
        "agent_outputs": [],
    }

    # Run the graph starting from the entry point
    updated_state = graph.invoke(state)

    # Print the context extracted by understand_context_node
    print("Extracted context:")
    print(updated_state.get("context"))

In [4]:
test_understand_context_node()

Entered entry_point

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["building energy class"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Requesting address from user.
Extracted context:
{'intent': 'query generic database', 'entities': ['building energy class'], 'ambiguous': False}

#### test check_address

In [1]:
from src.agents.building_flow_graph import build_building_flow_graph

graph = build_building_flow_graph()

test_cases = [
    # Already in metadata
    {
        "name": "meta_has_address",
        "last_message": "anything",
        "metadata": {"address": "Storgatan 12, Göteborg"},
    },
    # Swedish: "adressen är ..."
    {
        "name": "sv_adressen_ar",
        "last_message": "adressen är Vasagatan 5, Stockholm.",
        "metadata": {},
    },
    # Swedish: "bor på ..."
    {
        "name": "sv_bor_pa",
        "last_message": "Jag bor på Stortorget 1, Malmö",
        "metadata": {},
    },
    # English: "address is ..."
    {
        "name": "en_address_is",
        "last_message": "My address is 221B Baker Street, London",
        "metadata": {},
    },
    # No address given
    {
        "name": "no_address",
        "last_message": "Tell me about my heating",
        "metadata": {},
    },
]

for case in test_cases:
    state = {
        "thread_id": case["name"],
        "messages": [{"role": "user", "content": case["last_message"]}],
        "metadata": case["metadata"],
        "session_state": {},
        "last_message": case["last_message"],
        "agent_outputs": [],
    }

    out = graph.invoke(state)

    print(f"=== {case['name']} ===")
    print("Last message:", case["last_message"])
    print("Detected address:", out.get("metadata", {}).get("address"))
    print("Final response:", out.get("final_response"))
    print("-" * 40)

INFO:src.agents.parse_intent_agent:Azure ChatCompletionsClient initialized for ParseIntentAgent.

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": [], "ambiguous": true}

Routing based on ambiguity
Clarifying...
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent
=== meta_has_address ===
Last message: anything
Detected address: Storgatan 12, Göteborg
Final response: Summary of: Fallback agent result
----------------------------------------
Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "address", "entities": ["Vasagatan 5", "Stockholm"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent
=== sv_adressen_ar ===
Last message: adressen är Vasagatan 5, Stockholm.
Detected address: Vasagatan 5, Stockholm
Final response: Summary of: Fallback agent result
----------------------------------------
Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "address", "entities": ["Stortorget 1", "Malmö"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent
=== sv_bor_pa ===
Last message: Jag bor på Stortorget 1, Malmö
Detected address: Stortorget 1, Malmö
Final response: Summary of: Fallback agent result
----------------------------------------
Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "address", "entities": ["221B Baker Street", "London"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent
=== en_address_is ===
Last message: My address is 221B Baker Street, London
Detected address: 221B Baker Street, London
Final response: Summary of: Fallback agent result
----------------------------------------
Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["heating"], "ambiguous": true}

Routing based on ambiguity
Clarifying...
Maintaining history
Checking for address...
Requesting address from user.
=== no_address ===
Last message: Tell me about my heating
Detected address: None
Final response: Can you please provide the building address?
----------------------------------------

#### augment_data

In [5]:
import pandas as pd
import numpy as np
import random
import string
from pathlib import Path

SRC = Path("../buildings.csv")
AUG = Path("./src/data/buildings_augmented.csv")
MAP = Path("./src/data/username_address_map.csv")

# Robust load (sniffs delimiter; falls back to semicolon)
def load_csv_robust(path: Path) -> pd.DataFrame:
    try:
        return pd.read_csv(path, sep=None, engine="python")
    except Exception:
        return pd.read_csv(path, sep=";")

df = load_csv_robust(SRC)

# Heuristics to find address & building_id columns in your Swedish EPC data
def find_col(df, keys):
    lower_map = {c.lower(): c for c in df.columns}
    for k in keys:
        if k in lower_map:
            return lower_map[k]
    for c in df.columns:
        lc = c.lower()
        for k in keys:
            if k in lc:
                return c
    return None

address_col = find_col(df, ["idadr", "epc_idadr", "address", "gatuadress", "gata", "idadraggregerad"])
building_id_col = find_col(df, ["building_id", "byggnadsid", "uuid", "objektidentitet", "fastighetsbeteckning", "id", "epc_id"])

if address_col is None:
    df["__address__"] = "Unknown address"
    address_col = "__address__"
if building_id_col is None:
    building_id_col = df.columns[0]  # fallback

# Create varied usernames (≈55% emails, 45% 20-char IDs)
def random_email():
    first = ''.join(random.choices(string.ascii_lowercase, k=random.randint(5,9)))
    last = ''.join(random.choices(string.ascii_lowercase, k=random.randint(5,9)))
    domain = random.choice(["example.com", "mail.com", "energy.org", "brf.se", "kth.se"])
    return f"{first}.{last}@{domain}"

def random_id(n=20):
    alphabet = string.ascii_letters + string.digits
    return ''.join(random.choices(alphabet, k=n))

n = len(df)
mask = np.random.rand(n) < 0.55
usernames = [random_email() if mask[i] else random_id(20) for i in range(n)]
df["username"] = usernames

# thread_id = "<username>:<session>"
def random_session():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=12))
df["thread_id"] = [f"{u}:{random_session()}" for u in df["username"]]

# Save augmented data
df.to_csv(AUG, index=False)

# Quick username→address map (handy for tests)
map_df = df[["username", "thread_id", building_id_col, address_col]].copy()
map_df.columns = ["username", "thread_id", "building_id", "address"]
map_df.to_csv(MAP, index=False)

print("Augmented CSV saved:", AUG)
print("Username→Address map saved:", MAP)
print("Detected columns -> building_id:", building_id_col, "| address:", address_col)
df.head(3)

Augmented CSV saved: src\data\buildings_augmented.csv
Username→Address map saved: src\data\username_address_map.csv
Detected columns -> building_id: ID | address: IdAdr

,AntalByggDek_calc,AntalGamlaDek_calc,EgenAntalBolgh,EgenAntalKallarplan,EgenAntalPlan,EgenAntalTrapphus,EgenAtemp,EgenAtempBad,EgenAtempBostad,EgenAtempButik,...,InspLuftUndAvtalEgipres,InspLuftUndSysFastStyr,InspLuftUndFunkOverReglBost,EgiSpecifikEnergianvandning,VentGruppUtanAnm,ExpertGruppHosUppdragsgivare,EgiEnergianvandning_Eindex_calc,IdAdrAggregerad,username,thread_id
0,1,1,NaN,NaN,NaN,NaN,159,NaN,100.0,NaN,...,NaN,NaN,NaN,38.0,NaN,NaN,6042.0,Karin Larssons Väg 79,ebpuetk.vtdyrjiz@kth.se,ebpuetk.vtdyrjiz@kth.se:nrgr3d9szhpk
1,1,2,16.0,1.0,3.0,1.0,1422,0.0,94.0,0.0,...,NaN,NaN,NaN,222.0,1.0,NaN,315342.0,Hauptvägen 76,m27Sb5FCWcuNICAUVDFN,m27Sb5FCWcuNICAUVDFN:jin12tfwbkz7
2,1,1,NaN,NaN,NaN,NaN,176,NaN,100.0,NaN,...,NaN,NaN,NaN,183.0,NaN,NaN,32148.0,Flötviksvägen 45A,cvmjdx.hjxyjrpmm@mail.com,cvmjdx.hjxyjrpmm@mail.com:zbjiatwl2d7s

#### test genric module

In [1]:
# Diverse end-to-end tests for the generic SQL path (Jupyter)
from src.agents.building_flow_graph import build_building_flow_graph
from src.agents.parse_intent_agent import ParseIntentAgent
from src.agents.generic_sql_layer import SQL_Mapper_Layer
import pandas as pd
from pathlib import Path
import numpy as np

AUG = Path("./src/data/buildings_augmented.csv")
assert AUG.exists(), "Augmented CSV not found at ./src/data/buildings_augmented.csv"
aug = pd.read_csv(AUG, low_memory=False)

# Column picking helpers
def pick_col(df, prefer):
    lower = {c.lower(): c for c in df.columns}
    for k in prefer:
        if k in lower: return lower[k]
    for c in df.columns:
        lc = c.lower()
        if any(k in lc for k in prefer): return c
    return df.columns[0]

addr_col = pick_col(aug, ["address", "epc_idadr", "idadr", "raw_address", "addr", "idadraggregerad"])
bid_col  = pick_col(aug, ["building_id", "uuid", "id", "objektidentitet", "id"])
tid_col  = pick_col(aug, ["thread_id"])
print("Detected:", {"address_col": addr_col, "building_id_col": bid_col, "thread_id_col": tid_col})

# Prefer rows that have useful values for our key fields to make results obvious
key_cols = {
    "energy_class": "EgiEnergiklass2020_calc",
    "el_calc": "El_calc",
    "varme_calc": "EgiVarme_calc",
    "primary_heat": "HuvudsakligUppvarmning_calc",
    "basement": "EgenAntalKallarplan",
    "stairs": "EgenAntalTrapphus",
}
def rows_with_any_signal(df, n=3):
    mask = np.zeros(len(df), dtype=bool)
    for col in key_cols.values():
        if col in df.columns:
            mask |= df[col].notna()
    cand = df[mask]
    if len(cand) >= n:
        return cand.sample(n, random_state=42)
    return df.sample(n, random_state=42)

samples = rows_with_any_signal(aug, n=3).reset_index(drop=True)

# Test prompts covering many topics (English+Swedish)
TESTS = [
    ("energy_class",       lambda a: f"I live at {a}. What is the energy class of my building?"),
    ("energy_class_sv",    lambda a: f"Jag bor på {a}. Vad är energiklass för min byggnad?"),
    ("electricity_usage",  lambda a: f"For {a}, how many kWh of electricity do we use?"),
    ("electricity_usage_sv",lambda a: f"För {a}, hur många kWh el använder vi?"),
    ("heating_usage",      lambda a: f"For {a}, what is the heating kWh (värmeanvändning)?"),
    ("primary_heating_sv", lambda a: f"På {a}, vad är den huvudsakliga uppvärmningen?"),
    ("heated_area",        lambda a: f"At {a}, how many square meters (heated area / Atemp) does the building have?"),
    ("basement_count_sv",  lambda a: f"På {a}, hur många källarplan finns det?"),
    ("stairs_count_sv",    lambda a: f"På {a}, hur många trapphus finns det?"),
    ("tariff_sv",          lambda a: f"Gällande {a}, vad är nätavgiften för min byggnad?"),
]

# Build once
graph = build_building_flow_graph()
parser = ParseIntentAgent()
mapper = SQL_Mapper_Layer()

def pretty(x):
    if x is None: return "None"
    try:
        import math, numpy as np
        if isinstance(x, float) and (math.isnan(x) or x is None): return "None"
        if isinstance(x, np.floating) and np.isnan(x): return "None"
    except Exception:
        pass
    return x

def run_case(test_id, test_name, last_message, row):
    addr = str(row[addr_col])
    tid  = str(row[tid_col]) if tid_col in row else "user@example.com:session123"
    bid  = str(row[bid_col])

    # State (graph will re-classify intent; we also classify explicitly for logging)
    state = {
        "thread_id": tid,
        "messages": [{"role": "user", "content": last_message}],
        "metadata": {"address": addr},  # pre-provide address so we skip prompt
        "session_state": {},
        "last_message": last_message,
        "agent_outputs": [],
    }

    # Classify for visibility
    _classified = parser(state)  # updates context
    intent = (_classified.get("context", {}) or {}).get("intent")
    entities = (_classified.get("context", {}) or {}).get("entities")
    ambiguous = bool((_classified.get("context", {}) or {}).get("ambiguous"))

    # Ask the mapper what op it will choose (for visibility)
    op, kwargs = mapper.route(_classified)

    # Run the graph end-to-end
    out = graph.invoke(state)

    # Try to show the raw row values for key fields (from final building_id if present)
    final_bid = out.get("metadata", {}).get("building_id") or bid
    payload = mapper.sql.fetch_building_data(final_bid)
    highlight = {}
    if isinstance(payload, dict):
        for label, col in key_cols.items():
            if col in payload:
                highlight[col] = payload.get(col)

    print(f"\n=== [{test_id}] {test_name} ===")
    print("Address:", addr)
    print("Thread ID:", tid)
    print("Building ID (pre):", bid)
    print("Detected intent:", intent, "| entities:", entities, "| ambiguous:", ambiguous)
    print("Mapper routed op:", op, "| kwargs:", kwargs)
    print("Graph metadata.building_id (post):", out.get("metadata", {}).get("building_id"))
    print("Final response:", out.get("final_response"))
    print("Agent outputs:\n", "\n---\n".join(out.get("agent_outputs", [])) or None)
    if highlight:
        print("Raw CSV highlights for this building_id:")
        for k, v in highlight.items():
            print(f"  {k}: {pretty(v)}")
    print("-" * 80)

# Run over a few diverse rows and prompts
test_counter = 1
for i in range(len(samples)):
    row = samples.iloc[i]
    addr = str(row[addr_col])
    print(f"\n########## SAMPLE {i+1} / {len(samples)} :: {addr} ##########")
    for name, prompt_fn in TESTS:
        run_case(test_counter, name, prompt_fn(addr), row)
        test_counter += 1

INFO:src.agents.parse_intent_agent:Azure ChatCompletionsClient initialized for ParseIntentAgent.
c:\Users\shada\Documents\spara-backend\src\database\sql_client.py:30: DtypeWarning: Columns (22,80) have mixed types. Specify dtype option on import or set low_memory=False.
  self._df = pd.read_csv(self._path)

Detected: {'address_col': 'IdAdr', 'building_id_col': 'ID', 'thread_id_col': 'thread_id'}

c:\Users\shada\Documents\spara-backend\src\database\sql_client.py:30: DtypeWarning: Columns (22,80) have mixed types. Specify dtype option on import or set low_memory=False.
  self._df = pd.read_csv(self._path)

########## SAMPLE 1 / 3 :: Rindögatan 42 ##########

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [1] energy_class ===
Address: Rindögatan 42
Thread ID: FW1tBNQ9RLrz2Y7zmiSQ:a3du40sylty1
Building ID (pre): 01-80-VERKSTADSKLUBBEN25
Detected intent: query generic database | entities: ['Rindögatan 42'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Rindögatan 42'}
Graph metadata.building_id (post): 1
Final response: Summary of: energy_class: C
Agent outputs:
 energy_class: C
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "energiklass"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "energiklass"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [2] energy_class_sv ===
Address: Rindögatan 42
Thread ID: FW1tBNQ9RLrz2Y7zmiSQ:a3du40sylty1
Building ID (pre): 01-80-VERKSTADSKLUBBEN25
Detected intent: query generic database | entities: ['Rindögatan 42', 'energiklass'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Rindögatan 42'}
Graph metadata.building_id (post): 1
Final response: Summary of: energy_class: C
Agent outputs:
 energy_class: C
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

WARNING:src.agents.parse_intent_agent:Intent classification timed out.

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "kWh", "electricity"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [3] electricity_usage ===
Address: Rindögatan 42
Thread ID: FW1tBNQ9RLrz2Y7zmiSQ:a3du40sylty1
Building ID (pre): 01-80-VERKSTADSKLUBBEN25
Detected intent: unknown | entities: [] | ambiguous: False
Mapper routed op: noop | kwargs: {}
Graph metadata.building_id (post): 1
Final response: Summary of: el_calc: 5976
Agent outputs:
 el_calc: 5976
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "kWh el"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "kWh el"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [4] electricity_usage_sv ===
Address: Rindögatan 42
Thread ID: FW1tBNQ9RLrz2Y7zmiSQ:a3du40sylty1
Building ID (pre): 01-80-VERKSTADSKLUBBEN25
Detected intent: query generic database | entities: ['Rindögatan 42', 'kWh el'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Rindögatan 42'}
Graph metadata.building_id (post): 1
Final response: Summary of: el_calc: 5976
Agent outputs:
 el_calc: 5976
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "heating kWh", "värmeanvändning"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "heating kWh", "värmeanvändning"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [5] heating_usage ===
Address: Rindögatan 42
Thread ID: FW1tBNQ9RLrz2Y7zmiSQ:a3du40sylty1
Building ID (pre): 01-80-VERKSTADSKLUBBEN25
Detected intent: query generic database | entities: ['Rindögatan 42', 'heating kWh', 'värmeanvändning'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Rindögatan 42'}
Graph metadata.building_id (post): 1
Final response: Summary of: varme_calc: 5500
Agent outputs:
 varme_calc: 5500
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "huvudsakliga uppvärmningen"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "huvudsakliga uppvärmningen"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [6] primary_heating_sv ===
Address: Rindögatan 42
Thread ID: FW1tBNQ9RLrz2Y7zmiSQ:a3du40sylty1
Building ID (pre): 01-80-VERKSTADSKLUBBEN25
Detected intent: query generic database | entities: ['Rindögatan 42', 'huvudsakliga uppvärmningen'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Rindögatan 42'}
Graph metadata.building_id (post): 1
Final response: Summary of: AntalByggDek_calc: 1
AntalGamlaDek_calc: 1
EgenAntalBolgh: nan
EgenAntalKallarplan: nan
EgenAntalPlan: nan
EgenAntalTrapphus: nan
EgenAtemp: 159
EgenAtempBad: nan
EgenAtempBostad: 100.0
EgenAtempButik: nan
EgenAtempHotell: nan
EgenAtempKontor: nan
EgenAtempKopcentrum: nan
EgenAtempLivsmedel: nan
EgenAtempOvrig: nan
EgenAtempOvrigaVad: nan
EgenAtempRestaurang: nan
EgenAtempSkolor: nan
EgenAtempSumma: 100
EgenAtempTeater: nan
EgenAtempVard: nan
EgenAtempVardDag: nan
EgenAvarmgarage: nan
EgenBOA: nan
EgenBRA: nan
EgenBTA: nan
EgenByggnadsKat: En- och tvåbostadshus
EgenByggnadsKatKrav2020_calc: 90
EgenByggnadsTyp: Friliggande
EgenGruppAtemp: Mätt
EgenInstEleffektStorre: Ja
EgenKomplexitet: Enkel
EgenLOA: nan
EgenNybyggAr: 2016
EgenProjVentFlode: nan
EgenSarskiltVardefull: Nej
EgenSkyddadByggnad: Nej
EgenSkyddadEllerVardefull: nan
EgenSmaLagenheter: Nej
EgenTypkod: 220
EgenTypkod_typ: 220 - Småhusenhet, bebyggd
EgiBerElProduktion: nan
EgiBerEngProduktion: nan
EgiBeraknatVarde: Ja
EgiElDirekt: 0.0
EgiElDirektUPPV: 0
EgiElLuft: 0.0
EgiElLuftUPPV: 0
EgiElVV: 1280
EgiElVatten: 0.0
EgiElVattenUPPV: 0
EgiEnergiPrestanda: 38
EgiEnergianvandning: nan
EgiEnergianvandning_Eindex_calc: 6042.0
EgiEnergianvandning_calc: 6042
EgiEnergiklass: B
EgiEnergiklass2016_calc: B
EgiEnergiklass2020_calc: C
EgiFastighet: 476
EgiFgeo_calc: 1
EgiFjarrkyla: 0
EgiFjarrvarme: 0.0
EgiFjarrvarmeUPPV: 0
EgiFjarrvarmeVV: 0
EgiFlis: 0.0
EgiFlisUPPV: 0
EgiFlisVV: 0
EgiForstaArManad: nan
EgiGas: 0.0
EgiGasUPPV: 0
EgiGasVV: 0
EgiGruppElDirekt: nan
EgiGruppElLuft: nan
EgiGruppElVatten: nan
EgiGruppFastighet: nan
EgiGruppFjarrkyla: nan
EgiGruppFjarrvarme: nan
EgiGruppFlis: nan
EgiGruppGas: nan
EgiGruppHushall: nan
EgiGruppKomfort: nan
EgiGruppOlja: nan
EgiGruppOvrBiobransle: nan
EgiGruppPumpFranluft: nan
EgiGruppPumpLuftLuft: nan
EgiGruppPumpLuftVatten: nan
EgiGruppPumpMark: nan
EgiGruppSolcell: Nej
EgiGruppSolvarme: Nej
EgiGruppVVBered: nan
EgiGruppVed: nan
EgiGruppVerksamhet: nan
EgiHushall: 0
EgiKomfort: 0
EgiKomfortTillagg: 0
EgiNormKorrEI: nan
EgiNormKorrGD: nan
EgiOlja: 0.0
EgiOljaUPPV: 0
EgiOljaVV: 0
EgiOvrBiobransle: 0.0
EgiOvrBiobransleUPPV: 0
EgiOvrBiobransleVV: 0
EgiPrimarenergianvandning: nan
EgiPrimarenergianvandning2020_calc: 10876
EgiPrimarenergital: nan
EgiPrimarenergital2019: nan
EgiPrimarenergital2020: nan
EgiPrimarenergital2020_calc: 68
EgiPumpFranluft: 5500.0
EgiPumpFranluftUPPV: 4220
EgiPumpLuftLuft: 0.0
EgiPumpLuftLuftUPPV: 0
EgiPumpLuftVatten: 0.0
EgiPumpLuftVattenUPPV: 0
EgiPumpMark: 0.0
EgiPumpMarkUPPV: 0
EgiRefvarde1: 55
EgiRefvarde2Max: 106
EgiRefvarde2Min: 86.0
EgiRefvarde3: nan
EgiSistaArManad: nan
EgiSolcell: nan
EgiSolvarme: nan
EgiSpecifikEnergianvandning: 38.0
EgiSpecifikEnergianvandning_Eindex_calc: 38.0
EgiSpecifikEnergianvandning_calc: 38
EgiStationEI: nan
EgiStationGD: nan
EgiSumma1: 5500.0
EgiSumma2: 5976
EgiSumma3: 5976.0
EgiSumma4: 5976.0
EgiTappvarmvatten_calc: 1280
EgiUppvarmning_calc: 4220
EgiVVBered: 1280.0
EgiVaravEl: 38.0
EgiVarme_calc: 5500
EgiVed: 0.0
EgiVedUPPV: 0
EgiVedVV: 0
EgiVerksamhet: 0
EgiVersion: 2015
El_calc: 5976
EnergiIndex_calc: 1.014055
ExpertGruppHosUppdragsgivare: nan
FjarrvarmeNatNamn_calc: nan
FormularId: 752340
Godkand: 2016-12-29
HuvudsakligUppvarmning_calc: PumpFranluft
ID: 01-80-GASKEN2
IdAdr: Karin Larssons Väg 79
IdAdrAggregerad: Karin Larssons Väg 79
IdEgnaHem: 1
IdFastBet: Gasken 2
IdHusnr: 1
IdHuvudadress: Ja
IdKommun: Stockholm
IdKommunkod: 80
IdLan: Stockholms län
IdLankod: 1
IdPostnr: 12863
IdPostort: Sköndal
IdRapportLM: nan
InspLuftAngeNomEffekt: nan
InspLuftAngeNomEffektYta: nan
InspLuftBedomningNomEffekt: nan
InspLuftGruppInspSkyldighet: nan
InspLuftGruppLamplig: nan
InspLuftGruppNomStorre: nan
InspLuftLampligKommentar: nan
InspLuftUndAvtalEgipres: nan
InspLuftUndFunkOverReglBost: nan
InspLuftUndSysFastStyr: nan
InspUppvAngeNomEffekt: nan
InspUppvAngeNomEffektYta: nan
InspUppvBedomningNomEffekt: nan
InspUppvGruppInspSkyldighet: nan
InspUppvGruppLamplig: nan
InspUppvGruppNomStorre: nan
InspUppvLampligKommentar: nan
InspUppvUndAvtalEgipres: nan
InspUppvUndFunkOverReglBost: nan
InspUppvUndSysFastStyr: nan
LocalVersion_calc: 1
LuftGruppFinnsluft: Nej
SourceVersion_calc: 14.1
VentDelvisProcent: nan
VentGruppGodkand: nan
VentGruppKrav: Nej
VentGruppUtanAnm: nan
VentTypF: Nej
VentTypFT: Nej
VentTypFTX: Nej
VentTypFmed: Ja
VentTypSjalvdrag: Nej
Version: 2.4
VersionOrder_calc: 0
thread_id: ebpuetk.vtdyrjiz@kth.se:nrgr3d9szhpk
username: ebpuetk.vtdyrjiz@kth.se
Agent outputs:
 AntalByggDek_calc: 1
AntalGamlaDek_calc: 1
EgenAntalBolgh: nan
EgenAntalKallarplan: nan
EgenAntalPlan: nan
EgenAntalTrapphus: nan
EgenAtemp: 159
EgenAtempBad: nan
EgenAtempBostad: 100.0
EgenAtempButik: nan
EgenAtempHotell: nan
EgenAtempKontor: nan
EgenAtempKopcentrum: nan
EgenAtempLivsmedel: nan
EgenAtempOvrig: nan
EgenAtempOvrigaVad: nan
EgenAtempRestaurang: nan
EgenAtempSkolor: nan
EgenAtempSumma: 100
EgenAtempTeater: nan
EgenAtempVard: nan
EgenAtempVardDag: nan
EgenAvarmgarage: nan
EgenBOA: nan
EgenBRA: nan
EgenBTA: nan
EgenByggnadsKat: En- och tvåbostadshus
EgenByggnadsKatKrav2020_calc: 90
EgenByggnadsTyp: Friliggande
EgenGruppAtemp: Mätt
EgenInstEleffektStorre: Ja
EgenKomplexitet: Enkel
EgenLOA: nan
EgenNybyggAr: 2016
EgenProjVentFlode: nan
EgenSarskiltVardefull: Nej
EgenSkyddadByggnad: Nej
EgenSkyddadEllerVardefull: nan
EgenSmaLagenheter: Nej
EgenTypkod: 220
EgenTypkod_typ: 220 - Småhusenhet, bebyggd
EgiBerElProduktion: nan
EgiBerEngProduktion: nan
EgiBeraknatVarde: Ja
EgiElDirekt: 0.0
EgiElDirektUPPV: 0
EgiElLuft: 0.0
EgiElLuftUPPV: 0
EgiElVV: 1280
EgiElVatten: 0.0
EgiElVattenUPPV: 0
EgiEnergiPrestanda: 38
EgiEnergianvandning: nan
EgiEnergianvandning_Eindex_calc: 6042.0
EgiEnergianvandning_calc: 6042
EgiEnergiklass: B
EgiEnergiklass2016_calc: B
EgiEnergiklass2020_calc: C
EgiFastighet: 476
EgiFgeo_calc: 1
EgiFjarrkyla: 0
EgiFjarrvarme: 0.0
EgiFjarrvarmeUPPV: 0
EgiFjarrvarmeVV: 0
EgiFlis: 0.0
EgiFlisUPPV: 0
EgiFlisVV: 0
EgiForstaArManad: nan
EgiGas: 0.0
EgiGasUPPV: 0
EgiGasVV: 0
EgiGruppElDirekt: nan
EgiGruppElLuft: nan
EgiGruppElVatten: nan
EgiGruppFastighet: nan
EgiGruppFjarrkyla: nan
EgiGruppFjarrvarme: nan
EgiGruppFlis: nan
EgiGruppGas: nan
EgiGruppHushall: nan
EgiGruppKomfort: nan
EgiGruppOlja: nan
EgiGruppOvrBiobransle: nan
EgiGruppPumpFranluft: nan
EgiGruppPumpLuftLuft: nan
EgiGruppPumpLuftVatten: nan
EgiGruppPumpMark: nan
EgiGruppSolcell: Nej
EgiGruppSolvarme: Nej
EgiGruppVVBered: nan
EgiGruppVed: nan
EgiGruppVerksamhet: nan
EgiHushall: 0
EgiKomfort: 0
EgiKomfortTillagg: 0
EgiNormKorrEI: nan
EgiNormKorrGD: nan
EgiOlja: 0.0
EgiOljaUPPV: 0
EgiOljaVV: 0
EgiOvrBiobransle: 0.0
EgiOvrBiobransleUPPV: 0
EgiOvrBiobransleVV: 0
EgiPrimarenergianvandning: nan
EgiPrimarenergianvandning2020_calc: 10876
EgiPrimarenergital: nan
EgiPrimarenergital2019: nan
EgiPrimarenergital2020: nan
EgiPrimarenergital2020_calc: 68
EgiPumpFranluft: 5500.0
EgiPumpFranluftUPPV: 4220
EgiPumpLuftLuft: 0.0
EgiPumpLuftLuftUPPV: 0
EgiPumpLuftVatten: 0.0
EgiPumpLuftVattenUPPV: 0
EgiPumpMark: 0.0
EgiPumpMarkUPPV: 0
EgiRefvarde1: 55
EgiRefvarde2Max: 106
EgiRefvarde2Min: 86.0
EgiRefvarde3: nan
EgiSistaArManad: nan
EgiSolcell: nan
EgiSolvarme: nan
EgiSpecifikEnergianvandning: 38.0
EgiSpecifikEnergianvandning_Eindex_calc: 38.0
EgiSpecifikEnergianvandning_calc: 38
EgiStationEI: nan
EgiStationGD: nan
EgiSumma1: 5500.0
EgiSumma2: 5976
EgiSumma3: 5976.0
EgiSumma4: 5976.0
EgiTappvarmvatten_calc: 1280
EgiUppvarmning_calc: 4220
EgiVVBered: 1280.0
EgiVaravEl: 38.0
EgiVarme_calc: 5500
EgiVed: 0.0
EgiVedUPPV: 0
EgiVedVV: 0
EgiVerksamhet: 0
EgiVersion: 2015
El_calc: 5976
EnergiIndex_calc: 1.014055
ExpertGruppHosUppdragsgivare: nan
FjarrvarmeNatNamn_calc: nan
FormularId: 752340
Godkand: 2016-12-29
HuvudsakligUppvarmning_calc: PumpFranluft
ID: 01-80-GASKEN2
IdAdr: Karin Larssons Väg 79
IdAdrAggregerad: Karin Larssons Väg 79
IdEgnaHem: 1
IdFastBet: Gasken 2
IdHusnr: 1
IdHuvudadress: Ja
IdKommun: Stockholm
IdKommunkod: 80
IdLan: Stockholms län
IdLankod: 1
IdPostnr: 12863
IdPostort: Sköndal
IdRapportLM: nan
InspLuftAngeNomEffekt: nan
InspLuftAngeNomEffektYta: nan
InspLuftBedomningNomEffekt: nan
InspLuftGruppInspSkyldighet: nan
InspLuftGruppLamplig: nan
InspLuftGruppNomStorre: nan
InspLuftLampligKommentar: nan
InspLuftUndAvtalEgipres: nan
InspLuftUndFunkOverReglBost: nan
InspLuftUndSysFastStyr: nan
InspUppvAngeNomEffekt: nan
InspUppvAngeNomEffektYta: nan
InspUppvBedomningNomEffekt: nan
InspUppvGruppInspSkyldighet: nan
InspUppvGruppLamplig: nan
InspUppvGruppNomStorre: nan
InspUppvLampligKommentar: nan
InspUppvUndAvtalEgipres: nan
InspUppvUndFunkOverReglBost: nan
InspUppvUndSysFastStyr: nan
LocalVersion_calc: 1
LuftGruppFinnsluft: Nej
SourceVersion_calc: 14.1
VentDelvisProcent: nan
VentGruppGodkand: nan
VentGruppKrav: Nej
VentGruppUtanAnm: nan
VentTypF: Nej
VentTypFT: Nej
VentTypFTX: Nej
VentTypFmed: Ja
VentTypSjalvdrag: Nej
Version: 2.4
VersionOrder_calc: 0
thread_id: ebpuetk.vtdyrjiz@kth.se:nrgr3d9szhpk
username: ebpuetk.vtdyrjiz@kth.se
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

WARNING:src.agents.parse_intent_agent:Intent classification timed out.

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "heated area", "Atemp"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [7] heated_area ===
Address: Rindögatan 42
Thread ID: FW1tBNQ9RLrz2Y7zmiSQ:a3du40sylty1
Building ID (pre): 01-80-VERKSTADSKLUBBEN25
Detected intent: unknown | entities: [] | ambiguous: False
Mapper routed op: noop | kwargs: {}
Graph metadata.building_id (post): 1
Final response: Summary of: AntalByggDek_calc: 1
AntalGamlaDek_calc: 1
EgenAntalBolgh: nan
EgenAntalKallarplan: nan
EgenAntalPlan: nan
EgenAntalTrapphus: nan
EgenAtemp: 159
EgenAtempBad: nan
EgenAtempBostad: 100.0
EgenAtempButik: nan
EgenAtempHotell: nan
EgenAtempKontor: nan
EgenAtempKopcentrum: nan
EgenAtempLivsmedel: nan
EgenAtempOvrig: nan
EgenAtempOvrigaVad: nan
EgenAtempRestaurang: nan
EgenAtempSkolor: nan
EgenAtempSumma: 100
EgenAtempTeater: nan
EgenAtempVard: nan
EgenAtempVardDag: nan
EgenAvarmgarage: nan
EgenBOA: nan
EgenBRA: nan
EgenBTA: nan
EgenByggnadsKat: En- och tvåbostadshus
EgenByggnadsKatKrav2020_calc: 90
EgenByggnadsTyp: Friliggande
EgenGruppAtemp: Mätt
EgenInstEleffektStorre: Ja
EgenKomplexitet: Enkel
EgenLOA: nan
EgenNybyggAr: 2016
EgenProjVentFlode: nan
EgenSarskiltVardefull: Nej
EgenSkyddadByggnad: Nej
EgenSkyddadEllerVardefull: nan
EgenSmaLagenheter: Nej
EgenTypkod: 220
EgenTypkod_typ: 220 - Småhusenhet, bebyggd
EgiBerElProduktion: nan
EgiBerEngProduktion: nan
EgiBeraknatVarde: Ja
EgiElDirekt: 0.0
EgiElDirektUPPV: 0
EgiElLuft: 0.0
EgiElLuftUPPV: 0
EgiElVV: 1280
EgiElVatten: 0.0
EgiElVattenUPPV: 0
EgiEnergiPrestanda: 38
EgiEnergianvandning: nan
EgiEnergianvandning_Eindex_calc: 6042.0
EgiEnergianvandning_calc: 6042
EgiEnergiklass: B
EgiEnergiklass2016_calc: B
EgiEnergiklass2020_calc: C
EgiFastighet: 476
EgiFgeo_calc: 1
EgiFjarrkyla: 0
EgiFjarrvarme: 0.0
EgiFjarrvarmeUPPV: 0
EgiFjarrvarmeVV: 0
EgiFlis: 0.0
EgiFlisUPPV: 0
EgiFlisVV: 0
EgiForstaArManad: nan
EgiGas: 0.0
EgiGasUPPV: 0
EgiGasVV: 0
EgiGruppElDirekt: nan
EgiGruppElLuft: nan
EgiGruppElVatten: nan
EgiGruppFastighet: nan
EgiGruppFjarrkyla: nan
EgiGruppFjarrvarme: nan
EgiGruppFlis: nan
EgiGruppGas: nan
EgiGruppHushall: nan
EgiGruppKomfort: nan
EgiGruppOlja: nan
EgiGruppOvrBiobransle: nan
EgiGruppPumpFranluft: nan
EgiGruppPumpLuftLuft: nan
EgiGruppPumpLuftVatten: nan
EgiGruppPumpMark: nan
EgiGruppSolcell: Nej
EgiGruppSolvarme: Nej
EgiGruppVVBered: nan
EgiGruppVed: nan
EgiGruppVerksamhet: nan
EgiHushall: 0
EgiKomfort: 0
EgiKomfortTillagg: 0
EgiNormKorrEI: nan
EgiNormKorrGD: nan
EgiOlja: 0.0
EgiOljaUPPV: 0
EgiOljaVV: 0
EgiOvrBiobransle: 0.0
EgiOvrBiobransleUPPV: 0
EgiOvrBiobransleVV: 0
EgiPrimarenergianvandning: nan
EgiPrimarenergianvandning2020_calc: 10876
EgiPrimarenergital: nan
EgiPrimarenergital2019: nan
EgiPrimarenergital2020: nan
EgiPrimarenergital2020_calc: 68
EgiPumpFranluft: 5500.0
EgiPumpFranluftUPPV: 4220
EgiPumpLuftLuft: 0.0
EgiPumpLuftLuftUPPV: 0
EgiPumpLuftVatten: 0.0
EgiPumpLuftVattenUPPV: 0
EgiPumpMark: 0.0
EgiPumpMarkUPPV: 0
EgiRefvarde1: 55
EgiRefvarde2Max: 106
EgiRefvarde2Min: 86.0
EgiRefvarde3: nan
EgiSistaArManad: nan
EgiSolcell: nan
EgiSolvarme: nan
EgiSpecifikEnergianvandning: 38.0
EgiSpecifikEnergianvandning_Eindex_calc: 38.0
EgiSpecifikEnergianvandning_calc: 38
EgiStationEI: nan
EgiStationGD: nan
EgiSumma1: 5500.0
EgiSumma2: 5976
EgiSumma3: 5976.0
EgiSumma4: 5976.0
EgiTappvarmvatten_calc: 1280
EgiUppvarmning_calc: 4220
EgiVVBered: 1280.0
EgiVaravEl: 38.0
EgiVarme_calc: 5500
EgiVed: 0.0
EgiVedUPPV: 0
EgiVedVV: 0
EgiVerksamhet: 0
EgiVersion: 2015
El_calc: 5976
EnergiIndex_calc: 1.014055
ExpertGruppHosUppdragsgivare: nan
FjarrvarmeNatNamn_calc: nan
FormularId: 752340
Godkand: 2016-12-29
HuvudsakligUppvarmning_calc: PumpFranluft
ID: 01-80-GASKEN2
IdAdr: Karin Larssons Väg 79
IdAdrAggregerad: Karin Larssons Väg 79
IdEgnaHem: 1
IdFastBet: Gasken 2
IdHusnr: 1
IdHuvudadress: Ja
IdKommun: Stockholm
IdKommunkod: 80
IdLan: Stockholms län
IdLankod: 1
IdPostnr: 12863
IdPostort: Sköndal
IdRapportLM: nan
InspLuftAngeNomEffekt: nan
InspLuftAngeNomEffektYta: nan
InspLuftBedomningNomEffekt: nan
InspLuftGruppInspSkyldighet: nan
InspLuftGruppLamplig: nan
InspLuftGruppNomStorre: nan
InspLuftLampligKommentar: nan
InspLuftUndAvtalEgipres: nan
InspLuftUndFunkOverReglBost: nan
InspLuftUndSysFastStyr: nan
InspUppvAngeNomEffekt: nan
InspUppvAngeNomEffektYta: nan
InspUppvBedomningNomEffekt: nan
InspUppvGruppInspSkyldighet: nan
InspUppvGruppLamplig: nan
InspUppvGruppNomStorre: nan
InspUppvLampligKommentar: nan
InspUppvUndAvtalEgipres: nan
InspUppvUndFunkOverReglBost: nan
InspUppvUndSysFastStyr: nan
LocalVersion_calc: 1
LuftGruppFinnsluft: Nej
SourceVersion_calc: 14.1
VentDelvisProcent: nan
VentGruppGodkand: nan
VentGruppKrav: Nej
VentGruppUtanAnm: nan
VentTypF: Nej
VentTypFT: Nej
VentTypFTX: Nej
VentTypFmed: Ja
VentTypSjalvdrag: Nej
Version: 2.4
VersionOrder_calc: 0
thread_id: ebpuetk.vtdyrjiz@kth.se:nrgr3d9szhpk
username: ebpuetk.vtdyrjiz@kth.se
Agent outputs:
 AntalByggDek_calc: 1
AntalGamlaDek_calc: 1
EgenAntalBolgh: nan
EgenAntalKallarplan: nan
EgenAntalPlan: nan
EgenAntalTrapphus: nan
EgenAtemp: 159
EgenAtempBad: nan
EgenAtempBostad: 100.0
EgenAtempButik: nan
EgenAtempHotell: nan
EgenAtempKontor: nan
EgenAtempKopcentrum: nan
EgenAtempLivsmedel: nan
EgenAtempOvrig: nan
EgenAtempOvrigaVad: nan
EgenAtempRestaurang: nan
EgenAtempSkolor: nan
EgenAtempSumma: 100
EgenAtempTeater: nan
EgenAtempVard: nan
EgenAtempVardDag: nan
EgenAvarmgarage: nan
EgenBOA: nan
EgenBRA: nan
EgenBTA: nan
EgenByggnadsKat: En- och tvåbostadshus
EgenByggnadsKatKrav2020_calc: 90
EgenByggnadsTyp: Friliggande
EgenGruppAtemp: Mätt
EgenInstEleffektStorre: Ja
EgenKomplexitet: Enkel
EgenLOA: nan
EgenNybyggAr: 2016
EgenProjVentFlode: nan
EgenSarskiltVardefull: Nej
EgenSkyddadByggnad: Nej
EgenSkyddadEllerVardefull: nan
EgenSmaLagenheter: Nej
EgenTypkod: 220
EgenTypkod_typ: 220 - Småhusenhet, bebyggd
EgiBerElProduktion: nan
EgiBerEngProduktion: nan
EgiBeraknatVarde: Ja
EgiElDirekt: 0.0
EgiElDirektUPPV: 0
EgiElLuft: 0.0
EgiElLuftUPPV: 0
EgiElVV: 1280
EgiElVatten: 0.0
EgiElVattenUPPV: 0
EgiEnergiPrestanda: 38
EgiEnergianvandning: nan
EgiEnergianvandning_Eindex_calc: 6042.0
EgiEnergianvandning_calc: 6042
EgiEnergiklass: B
EgiEnergiklass2016_calc: B
EgiEnergiklass2020_calc: C
EgiFastighet: 476
EgiFgeo_calc: 1
EgiFjarrkyla: 0
EgiFjarrvarme: 0.0
EgiFjarrvarmeUPPV: 0
EgiFjarrvarmeVV: 0
EgiFlis: 0.0
EgiFlisUPPV: 0
EgiFlisVV: 0
EgiForstaArManad: nan
EgiGas: 0.0
EgiGasUPPV: 0
EgiGasVV: 0
EgiGruppElDirekt: nan
EgiGruppElLuft: nan
EgiGruppElVatten: nan
EgiGruppFastighet: nan
EgiGruppFjarrkyla: nan
EgiGruppFjarrvarme: nan
EgiGruppFlis: nan
EgiGruppGas: nan
EgiGruppHushall: nan
EgiGruppKomfort: nan
EgiGruppOlja: nan
EgiGruppOvrBiobransle: nan
EgiGruppPumpFranluft: nan
EgiGruppPumpLuftLuft: nan
EgiGruppPumpLuftVatten: nan
EgiGruppPumpMark: nan
EgiGruppSolcell: Nej
EgiGruppSolvarme: Nej
EgiGruppVVBered: nan
EgiGruppVed: nan
EgiGruppVerksamhet: nan
EgiHushall: 0
EgiKomfort: 0
EgiKomfortTillagg: 0
EgiNormKorrEI: nan
EgiNormKorrGD: nan
EgiOlja: 0.0
EgiOljaUPPV: 0
EgiOljaVV: 0
EgiOvrBiobransle: 0.0
EgiOvrBiobransleUPPV: 0
EgiOvrBiobransleVV: 0
EgiPrimarenergianvandning: nan
EgiPrimarenergianvandning2020_calc: 10876
EgiPrimarenergital: nan
EgiPrimarenergital2019: nan
EgiPrimarenergital2020: nan
EgiPrimarenergital2020_calc: 68
EgiPumpFranluft: 5500.0
EgiPumpFranluftUPPV: 4220
EgiPumpLuftLuft: 0.0
EgiPumpLuftLuftUPPV: 0
EgiPumpLuftVatten: 0.0
EgiPumpLuftVattenUPPV: 0
EgiPumpMark: 0.0
EgiPumpMarkUPPV: 0
EgiRefvarde1: 55
EgiRefvarde2Max: 106
EgiRefvarde2Min: 86.0
EgiRefvarde3: nan
EgiSistaArManad: nan
EgiSolcell: nan
EgiSolvarme: nan
EgiSpecifikEnergianvandning: 38.0
EgiSpecifikEnergianvandning_Eindex_calc: 38.0
EgiSpecifikEnergianvandning_calc: 38
EgiStationEI: nan
EgiStationGD: nan
EgiSumma1: 5500.0
EgiSumma2: 5976
EgiSumma3: 5976.0
EgiSumma4: 5976.0
EgiTappvarmvatten_calc: 1280
EgiUppvarmning_calc: 4220
EgiVVBered: 1280.0
EgiVaravEl: 38.0
EgiVarme_calc: 5500
EgiVed: 0.0
EgiVedUPPV: 0
EgiVedVV: 0
EgiVerksamhet: 0
EgiVersion: 2015
El_calc: 5976
EnergiIndex_calc: 1.014055
ExpertGruppHosUppdragsgivare: nan
FjarrvarmeNatNamn_calc: nan
FormularId: 752340
Godkand: 2016-12-29
HuvudsakligUppvarmning_calc: PumpFranluft
ID: 01-80-GASKEN2
IdAdr: Karin Larssons Väg 79
IdAdrAggregerad: Karin Larssons Väg 79
IdEgnaHem: 1
IdFastBet: Gasken 2
IdHusnr: 1
IdHuvudadress: Ja
IdKommun: Stockholm
IdKommunkod: 80
IdLan: Stockholms län
IdLankod: 1
IdPostnr: 12863
IdPostort: Sköndal
IdRapportLM: nan
InspLuftAngeNomEffekt: nan
InspLuftAngeNomEffektYta: nan
InspLuftBedomningNomEffekt: nan
InspLuftGruppInspSkyldighet: nan
InspLuftGruppLamplig: nan
InspLuftGruppNomStorre: nan
InspLuftLampligKommentar: nan
InspLuftUndAvtalEgipres: nan
InspLuftUndFunkOverReglBost: nan
InspLuftUndSysFastStyr: nan
InspUppvAngeNomEffekt: nan
InspUppvAngeNomEffektYta: nan
InspUppvBedomningNomEffekt: nan
InspUppvGruppInspSkyldighet: nan
InspUppvGruppLamplig: nan
InspUppvGruppNomStorre: nan
InspUppvLampligKommentar: nan
InspUppvUndAvtalEgipres: nan
InspUppvUndFunkOverReglBost: nan
InspUppvUndSysFastStyr: nan
LocalVersion_calc: 1
LuftGruppFinnsluft: Nej
SourceVersion_calc: 14.1
VentDelvisProcent: nan
VentGruppGodkand: nan
VentGruppKrav: Nej
VentGruppUtanAnm: nan
VentTypF: Nej
VentTypFT: Nej
VentTypFTX: Nej
VentTypFmed: Ja
VentTypSjalvdrag: Nej
Version: 2.4
VersionOrder_calc: 0
thread_id: ebpuetk.vtdyrjiz@kth.se:nrgr3d9szhpk
username: ebpuetk.vtdyrjiz@kth.se
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "källarplan"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "källarplan"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [8] basement_count_sv ===
Address: Rindögatan 42
Thread ID: FW1tBNQ9RLrz2Y7zmiSQ:a3du40sylty1
Building ID (pre): 01-80-VERKSTADSKLUBBEN25
Detected intent: query generic database | entities: ['Rindögatan 42', 'källarplan'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Rindögatan 42'}
Graph metadata.building_id (post): 1
Final response: Summary of: basement_count: nan
Agent outputs:
 basement_count: nan
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "trapphus"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "trapphus"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [9] stairs_count_sv ===
Address: Rindögatan 42
Thread ID: FW1tBNQ9RLrz2Y7zmiSQ:a3du40sylty1
Building ID (pre): 01-80-VERKSTADSKLUBBEN25
Detected intent: query generic database | entities: ['Rindögatan 42', 'trapphus'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Rindögatan 42'}
Graph metadata.building_id (post): 1
Final response: Summary of: stairs_count: nan
Agent outputs:
 stairs_count: nan
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "nätavgiften", "min byggnad"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "nätavgiften", "byggnad"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [10] tariff_sv ===
Address: Rindögatan 42
Thread ID: FW1tBNQ9RLrz2Y7zmiSQ:a3du40sylty1
Building ID (pre): 01-80-VERKSTADSKLUBBEN25
Detected intent: query generic database | entities: ['Rindögatan 42', 'nätavgiften', 'min byggnad'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Rindögatan 42'}
Graph metadata.building_id (post): 1
Final response: Summary of: tariff_name: None
Agent outputs:
 tariff_name: None
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

########## SAMPLE 2 / 3 :: Danderydsgatan 8 ##########

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "energy class"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "energy class"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [11] energy_class ===
Address: Danderydsgatan 8
Thread ID: jmEJBwCFlQPfEiKqaxpW:ogd0d3c1f5n5
Building ID (pre): 01-80-NAEKTERGALEN17
Detected intent: query generic database | entities: ['Danderydsgatan 8', 'energy class'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Danderydsgatan 8'}
Graph metadata.building_id (post): 1
Final response: Summary of: energy_class: C
Agent outputs:
 energy_class: C
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "energiklass"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "energiklass"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [12] energy_class_sv ===
Address: Danderydsgatan 8
Thread ID: jmEJBwCFlQPfEiKqaxpW:ogd0d3c1f5n5
Building ID (pre): 01-80-NAEKTERGALEN17
Detected intent: query generic database | entities: ['Danderydsgatan 8', 'energiklass'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Danderydsgatan 8'}
Graph metadata.building_id (post): 1
Final response: Summary of: energy_class: C
Agent outputs:
 energy_class: C
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "kWh", "electricity"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "kWh", "electricity"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [13] electricity_usage ===
Address: Danderydsgatan 8
Thread ID: jmEJBwCFlQPfEiKqaxpW:ogd0d3c1f5n5
Building ID (pre): 01-80-NAEKTERGALEN17
Detected intent: query generic database | entities: ['Danderydsgatan 8', 'kWh', 'electricity'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Danderydsgatan 8'}
Graph metadata.building_id (post): 1
Final response: Summary of: el_calc: 5976
Agent outputs:
 el_calc: 5976
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "kWh el"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "kWh el"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [14] electricity_usage_sv ===
Address: Danderydsgatan 8
Thread ID: jmEJBwCFlQPfEiKqaxpW:ogd0d3c1f5n5
Building ID (pre): 01-80-NAEKTERGALEN17
Detected intent: query generic database | entities: ['Danderydsgatan 8', 'kWh el'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Danderydsgatan 8'}
Graph metadata.building_id (post): 1
Final response: Summary of: el_calc: 5976
Agent outputs:
 el_calc: 5976
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "heating kWh", "värmeanvändning"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "heating kWh", "värmeanvändning"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [15] heating_usage ===
Address: Danderydsgatan 8
Thread ID: jmEJBwCFlQPfEiKqaxpW:ogd0d3c1f5n5
Building ID (pre): 01-80-NAEKTERGALEN17
Detected intent: query generic database | entities: ['Danderydsgatan 8', 'heating kWh', 'värmeanvändning'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Danderydsgatan 8'}
Graph metadata.building_id (post): 1
Final response: Summary of: varme_calc: 5500
Agent outputs:
 varme_calc: 5500
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "huvudsaklig uppvärmning"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "huvudsakliga uppvärmningen"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [16] primary_heating_sv ===
Address: Danderydsgatan 8
Thread ID: jmEJBwCFlQPfEiKqaxpW:ogd0d3c1f5n5
Building ID (pre): 01-80-NAEKTERGALEN17
Detected intent: query generic database | entities: ['Danderydsgatan 8', 'huvudsaklig uppvärmning'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Danderydsgatan 8'}
Graph metadata.building_id (post): 1
Final response: Summary of: AntalByggDek_calc: 1
AntalGamlaDek_calc: 1
EgenAntalBolgh: nan
EgenAntalKallarplan: nan
EgenAntalPlan: nan
EgenAntalTrapphus: nan
EgenAtemp: 159
EgenAtempBad: nan
EgenAtempBostad: 100.0
EgenAtempButik: nan
EgenAtempHotell: nan
EgenAtempKontor: nan
EgenAtempKopcentrum: nan
EgenAtempLivsmedel: nan
EgenAtempOvrig: nan
EgenAtempOvrigaVad: nan
EgenAtempRestaurang: nan
EgenAtempSkolor: nan
EgenAtempSumma: 100
EgenAtempTeater: nan
EgenAtempVard: nan
EgenAtempVardDag: nan
EgenAvarmgarage: nan
EgenBOA: nan
EgenBRA: nan
EgenBTA: nan
EgenByggnadsKat: En- och tvåbostadshus
EgenByggnadsKatKrav2020_calc: 90
EgenByggnadsTyp: Friliggande
EgenGruppAtemp: Mätt
EgenInstEleffektStorre: Ja
EgenKomplexitet: Enkel
EgenLOA: nan
EgenNybyggAr: 2016
EgenProjVentFlode: nan
EgenSarskiltVardefull: Nej
EgenSkyddadByggnad: Nej
EgenSkyddadEllerVardefull: nan
EgenSmaLagenheter: Nej
EgenTypkod: 220
EgenTypkod_typ: 220 - Småhusenhet, bebyggd
EgiBerElProduktion: nan
EgiBerEngProduktion: nan
EgiBeraknatVarde: Ja
EgiElDirekt: 0.0
EgiElDirektUPPV: 0
EgiElLuft: 0.0
EgiElLuftUPPV: 0
EgiElVV: 1280
EgiElVatten: 0.0
EgiElVattenUPPV: 0
EgiEnergiPrestanda: 38
EgiEnergianvandning: nan
EgiEnergianvandning_Eindex_calc: 6042.0
EgiEnergianvandning_calc: 6042
EgiEnergiklass: B
EgiEnergiklass2016_calc: B
EgiEnergiklass2020_calc: C
EgiFastighet: 476
EgiFgeo_calc: 1
EgiFjarrkyla: 0
EgiFjarrvarme: 0.0
EgiFjarrvarmeUPPV: 0
EgiFjarrvarmeVV: 0
EgiFlis: 0.0
EgiFlisUPPV: 0
EgiFlisVV: 0
EgiForstaArManad: nan
EgiGas: 0.0
EgiGasUPPV: 0
EgiGasVV: 0
EgiGruppElDirekt: nan
EgiGruppElLuft: nan
EgiGruppElVatten: nan
EgiGruppFastighet: nan
EgiGruppFjarrkyla: nan
EgiGruppFjarrvarme: nan
EgiGruppFlis: nan
EgiGruppGas: nan
EgiGruppHushall: nan
EgiGruppKomfort: nan
EgiGruppOlja: nan
EgiGruppOvrBiobransle: nan
EgiGruppPumpFranluft: nan
EgiGruppPumpLuftLuft: nan
EgiGruppPumpLuftVatten: nan
EgiGruppPumpMark: nan
EgiGruppSolcell: Nej
EgiGruppSolvarme: Nej
EgiGruppVVBered: nan
EgiGruppVed: nan
EgiGruppVerksamhet: nan
EgiHushall: 0
EgiKomfort: 0
EgiKomfortTillagg: 0
EgiNormKorrEI: nan
EgiNormKorrGD: nan
EgiOlja: 0.0
EgiOljaUPPV: 0
EgiOljaVV: 0
EgiOvrBiobransle: 0.0
EgiOvrBiobransleUPPV: 0
EgiOvrBiobransleVV: 0
EgiPrimarenergianvandning: nan
EgiPrimarenergianvandning2020_calc: 10876
EgiPrimarenergital: nan
EgiPrimarenergital2019: nan
EgiPrimarenergital2020: nan
EgiPrimarenergital2020_calc: 68
EgiPumpFranluft: 5500.0
EgiPumpFranluftUPPV: 4220
EgiPumpLuftLuft: 0.0
EgiPumpLuftLuftUPPV: 0
EgiPumpLuftVatten: 0.0
EgiPumpLuftVattenUPPV: 0
EgiPumpMark: 0.0
EgiPumpMarkUPPV: 0
EgiRefvarde1: 55
EgiRefvarde2Max: 106
EgiRefvarde2Min: 86.0
EgiRefvarde3: nan
EgiSistaArManad: nan
EgiSolcell: nan
EgiSolvarme: nan
EgiSpecifikEnergianvandning: 38.0
EgiSpecifikEnergianvandning_Eindex_calc: 38.0
EgiSpecifikEnergianvandning_calc: 38
EgiStationEI: nan
EgiStationGD: nan
EgiSumma1: 5500.0
EgiSumma2: 5976
EgiSumma3: 5976.0
EgiSumma4: 5976.0
EgiTappvarmvatten_calc: 1280
EgiUppvarmning_calc: 4220
EgiVVBered: 1280.0
EgiVaravEl: 38.0
EgiVarme_calc: 5500
EgiVed: 0.0
EgiVedUPPV: 0
EgiVedVV: 0
EgiVerksamhet: 0
EgiVersion: 2015
El_calc: 5976
EnergiIndex_calc: 1.014055
ExpertGruppHosUppdragsgivare: nan
FjarrvarmeNatNamn_calc: nan
FormularId: 752340
Godkand: 2016-12-29
HuvudsakligUppvarmning_calc: PumpFranluft
ID: 01-80-GASKEN2
IdAdr: Karin Larssons Väg 79
IdAdrAggregerad: Karin Larssons Väg 79
IdEgnaHem: 1
IdFastBet: Gasken 2
IdHusnr: 1
IdHuvudadress: Ja
IdKommun: Stockholm
IdKommunkod: 80
IdLan: Stockholms län
IdLankod: 1
IdPostnr: 12863
IdPostort: Sköndal
IdRapportLM: nan
InspLuftAngeNomEffekt: nan
InspLuftAngeNomEffektYta: nan
InspLuftBedomningNomEffekt: nan
InspLuftGruppInspSkyldighet: nan
InspLuftGruppLamplig: nan
InspLuftGruppNomStorre: nan
InspLuftLampligKommentar: nan
InspLuftUndAvtalEgipres: nan
InspLuftUndFunkOverReglBost: nan
InspLuftUndSysFastStyr: nan
InspUppvAngeNomEffekt: nan
InspUppvAngeNomEffektYta: nan
InspUppvBedomningNomEffekt: nan
InspUppvGruppInspSkyldighet: nan
InspUppvGruppLamplig: nan
InspUppvGruppNomStorre: nan
InspUppvLampligKommentar: nan
InspUppvUndAvtalEgipres: nan
InspUppvUndFunkOverReglBost: nan
InspUppvUndSysFastStyr: nan
LocalVersion_calc: 1
LuftGruppFinnsluft: Nej
SourceVersion_calc: 14.1
VentDelvisProcent: nan
VentGruppGodkand: nan
VentGruppKrav: Nej
VentGruppUtanAnm: nan
VentTypF: Nej
VentTypFT: Nej
VentTypFTX: Nej
VentTypFmed: Ja
VentTypSjalvdrag: Nej
Version: 2.4
VersionOrder_calc: 0
thread_id: ebpuetk.vtdyrjiz@kth.se:nrgr3d9szhpk
username: ebpuetk.vtdyrjiz@kth.se
Agent outputs:
 AntalByggDek_calc: 1
AntalGamlaDek_calc: 1
EgenAntalBolgh: nan
EgenAntalKallarplan: nan
EgenAntalPlan: nan
EgenAntalTrapphus: nan
EgenAtemp: 159
EgenAtempBad: nan
EgenAtempBostad: 100.0
EgenAtempButik: nan
EgenAtempHotell: nan
EgenAtempKontor: nan
EgenAtempKopcentrum: nan
EgenAtempLivsmedel: nan
EgenAtempOvrig: nan
EgenAtempOvrigaVad: nan
EgenAtempRestaurang: nan
EgenAtempSkolor: nan
EgenAtempSumma: 100
EgenAtempTeater: nan
EgenAtempVard: nan
EgenAtempVardDag: nan
EgenAvarmgarage: nan
EgenBOA: nan
EgenBRA: nan
EgenBTA: nan
EgenByggnadsKat: En- och tvåbostadshus
EgenByggnadsKatKrav2020_calc: 90
EgenByggnadsTyp: Friliggande
EgenGruppAtemp: Mätt
EgenInstEleffektStorre: Ja
EgenKomplexitet: Enkel
EgenLOA: nan
EgenNybyggAr: 2016
EgenProjVentFlode: nan
EgenSarskiltVardefull: Nej
EgenSkyddadByggnad: Nej
EgenSkyddadEllerVardefull: nan
EgenSmaLagenheter: Nej
EgenTypkod: 220
EgenTypkod_typ: 220 - Småhusenhet, bebyggd
EgiBerElProduktion: nan
EgiBerEngProduktion: nan
EgiBeraknatVarde: Ja
EgiElDirekt: 0.0
EgiElDirektUPPV: 0
EgiElLuft: 0.0
EgiElLuftUPPV: 0
EgiElVV: 1280
EgiElVatten: 0.0
EgiElVattenUPPV: 0
EgiEnergiPrestanda: 38
EgiEnergianvandning: nan
EgiEnergianvandning_Eindex_calc: 6042.0
EgiEnergianvandning_calc: 6042
EgiEnergiklass: B
EgiEnergiklass2016_calc: B
EgiEnergiklass2020_calc: C
EgiFastighet: 476
EgiFgeo_calc: 1
EgiFjarrkyla: 0
EgiFjarrvarme: 0.0
EgiFjarrvarmeUPPV: 0
EgiFjarrvarmeVV: 0
EgiFlis: 0.0
EgiFlisUPPV: 0
EgiFlisVV: 0
EgiForstaArManad: nan
EgiGas: 0.0
EgiGasUPPV: 0
EgiGasVV: 0
EgiGruppElDirekt: nan
EgiGruppElLuft: nan
EgiGruppElVatten: nan
EgiGruppFastighet: nan
EgiGruppFjarrkyla: nan
EgiGruppFjarrvarme: nan
EgiGruppFlis: nan
EgiGruppGas: nan
EgiGruppHushall: nan
EgiGruppKomfort: nan
EgiGruppOlja: nan
EgiGruppOvrBiobransle: nan
EgiGruppPumpFranluft: nan
EgiGruppPumpLuftLuft: nan
EgiGruppPumpLuftVatten: nan
EgiGruppPumpMark: nan
EgiGruppSolcell: Nej
EgiGruppSolvarme: Nej
EgiGruppVVBered: nan
EgiGruppVed: nan
EgiGruppVerksamhet: nan
EgiHushall: 0
EgiKomfort: 0
EgiKomfortTillagg: 0
EgiNormKorrEI: nan
EgiNormKorrGD: nan
EgiOlja: 0.0
EgiOljaUPPV: 0
EgiOljaVV: 0
EgiOvrBiobransle: 0.0
EgiOvrBiobransleUPPV: 0
EgiOvrBiobransleVV: 0
EgiPrimarenergianvandning: nan
EgiPrimarenergianvandning2020_calc: 10876
EgiPrimarenergital: nan
EgiPrimarenergital2019: nan
EgiPrimarenergital2020: nan
EgiPrimarenergital2020_calc: 68
EgiPumpFranluft: 5500.0
EgiPumpFranluftUPPV: 4220
EgiPumpLuftLuft: 0.0
EgiPumpLuftLuftUPPV: 0
EgiPumpLuftVatten: 0.0
EgiPumpLuftVattenUPPV: 0
EgiPumpMark: 0.0
EgiPumpMarkUPPV: 0
EgiRefvarde1: 55
EgiRefvarde2Max: 106
EgiRefvarde2Min: 86.0
EgiRefvarde3: nan
EgiSistaArManad: nan
EgiSolcell: nan
EgiSolvarme: nan
EgiSpecifikEnergianvandning: 38.0
EgiSpecifikEnergianvandning_Eindex_calc: 38.0
EgiSpecifikEnergianvandning_calc: 38
EgiStationEI: nan
EgiStationGD: nan
EgiSumma1: 5500.0
EgiSumma2: 5976
EgiSumma3: 5976.0
EgiSumma4: 5976.0
EgiTappvarmvatten_calc: 1280
EgiUppvarmning_calc: 4220
EgiVVBered: 1280.0
EgiVaravEl: 38.0
EgiVarme_calc: 5500
EgiVed: 0.0
EgiVedUPPV: 0
EgiVedVV: 0
EgiVerksamhet: 0
EgiVersion: 2015
El_calc: 5976
EnergiIndex_calc: 1.014055
ExpertGruppHosUppdragsgivare: nan
FjarrvarmeNatNamn_calc: nan
FormularId: 752340
Godkand: 2016-12-29
HuvudsakligUppvarmning_calc: PumpFranluft
ID: 01-80-GASKEN2
IdAdr: Karin Larssons Väg 79
IdAdrAggregerad: Karin Larssons Väg 79
IdEgnaHem: 1
IdFastBet: Gasken 2
IdHusnr: 1
IdHuvudadress: Ja
IdKommun: Stockholm
IdKommunkod: 80
IdLan: Stockholms län
IdLankod: 1
IdPostnr: 12863
IdPostort: Sköndal
IdRapportLM: nan
InspLuftAngeNomEffekt: nan
InspLuftAngeNomEffektYta: nan
InspLuftBedomningNomEffekt: nan
InspLuftGruppInspSkyldighet: nan
InspLuftGruppLamplig: nan
InspLuftGruppNomStorre: nan
InspLuftLampligKommentar: nan
InspLuftUndAvtalEgipres: nan
InspLuftUndFunkOverReglBost: nan
InspLuftUndSysFastStyr: nan
InspUppvAngeNomEffekt: nan
InspUppvAngeNomEffektYta: nan
InspUppvBedomningNomEffekt: nan
InspUppvGruppInspSkyldighet: nan
InspUppvGruppLamplig: nan
InspUppvGruppNomStorre: nan
InspUppvLampligKommentar: nan
InspUppvUndAvtalEgipres: nan
InspUppvUndFunkOverReglBost: nan
InspUppvUndSysFastStyr: nan
LocalVersion_calc: 1
LuftGruppFinnsluft: Nej
SourceVersion_calc: 14.1
VentDelvisProcent: nan
VentGruppGodkand: nan
VentGruppKrav: Nej
VentGruppUtanAnm: nan
VentTypF: Nej
VentTypFT: Nej
VentTypFTX: Nej
VentTypFmed: Ja
VentTypSjalvdrag: Nej
Version: 2.4
VersionOrder_calc: 0
thread_id: ebpuetk.vtdyrjiz@kth.se:nrgr3d9szhpk
username: ebpuetk.vtdyrjiz@kth.se
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "heated area", "Atemp"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "heated area", "Atemp"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [17] heated_area ===
Address: Danderydsgatan 8
Thread ID: jmEJBwCFlQPfEiKqaxpW:ogd0d3c1f5n5
Building ID (pre): 01-80-NAEKTERGALEN17
Detected intent: query generic database | entities: ['Danderydsgatan 8', 'heated area', 'Atemp'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Danderydsgatan 8'}
Graph metadata.building_id (post): 1
Final response: Summary of: AntalByggDek_calc: 1
AntalGamlaDek_calc: 1
EgenAntalBolgh: nan
EgenAntalKallarplan: nan
EgenAntalPlan: nan
EgenAntalTrapphus: nan
EgenAtemp: 159
EgenAtempBad: nan
EgenAtempBostad: 100.0
EgenAtempButik: nan
EgenAtempHotell: nan
EgenAtempKontor: nan
EgenAtempKopcentrum: nan
EgenAtempLivsmedel: nan
EgenAtempOvrig: nan
EgenAtempOvrigaVad: nan
EgenAtempRestaurang: nan
EgenAtempSkolor: nan
EgenAtempSumma: 100
EgenAtempTeater: nan
EgenAtempVard: nan
EgenAtempVardDag: nan
EgenAvarmgarage: nan
EgenBOA: nan
EgenBRA: nan
EgenBTA: nan
EgenByggnadsKat: En- och tvåbostadshus
EgenByggnadsKatKrav2020_calc: 90
EgenByggnadsTyp: Friliggande
EgenGruppAtemp: Mätt
EgenInstEleffektStorre: Ja
EgenKomplexitet: Enkel
EgenLOA: nan
EgenNybyggAr: 2016
EgenProjVentFlode: nan
EgenSarskiltVardefull: Nej
EgenSkyddadByggnad: Nej
EgenSkyddadEllerVardefull: nan
EgenSmaLagenheter: Nej
EgenTypkod: 220
EgenTypkod_typ: 220 - Småhusenhet, bebyggd
EgiBerElProduktion: nan
EgiBerEngProduktion: nan
EgiBeraknatVarde: Ja
EgiElDirekt: 0.0
EgiElDirektUPPV: 0
EgiElLuft: 0.0
EgiElLuftUPPV: 0
EgiElVV: 1280
EgiElVatten: 0.0
EgiElVattenUPPV: 0
EgiEnergiPrestanda: 38
EgiEnergianvandning: nan
EgiEnergianvandning_Eindex_calc: 6042.0
EgiEnergianvandning_calc: 6042
EgiEnergiklass: B
EgiEnergiklass2016_calc: B
EgiEnergiklass2020_calc: C
EgiFastighet: 476
EgiFgeo_calc: 1
EgiFjarrkyla: 0
EgiFjarrvarme: 0.0
EgiFjarrvarmeUPPV: 0
EgiFjarrvarmeVV: 0
EgiFlis: 0.0
EgiFlisUPPV: 0
EgiFlisVV: 0
EgiForstaArManad: nan
EgiGas: 0.0
EgiGasUPPV: 0
EgiGasVV: 0
EgiGruppElDirekt: nan
EgiGruppElLuft: nan
EgiGruppElVatten: nan
EgiGruppFastighet: nan
EgiGruppFjarrkyla: nan
EgiGruppFjarrvarme: nan
EgiGruppFlis: nan
EgiGruppGas: nan
EgiGruppHushall: nan
EgiGruppKomfort: nan
EgiGruppOlja: nan
EgiGruppOvrBiobransle: nan
EgiGruppPumpFranluft: nan
EgiGruppPumpLuftLuft: nan
EgiGruppPumpLuftVatten: nan
EgiGruppPumpMark: nan
EgiGruppSolcell: Nej
EgiGruppSolvarme: Nej
EgiGruppVVBered: nan
EgiGruppVed: nan
EgiGruppVerksamhet: nan
EgiHushall: 0
EgiKomfort: 0
EgiKomfortTillagg: 0
EgiNormKorrEI: nan
EgiNormKorrGD: nan
EgiOlja: 0.0
EgiOljaUPPV: 0
EgiOljaVV: 0
EgiOvrBiobransle: 0.0
EgiOvrBiobransleUPPV: 0
EgiOvrBiobransleVV: 0
EgiPrimarenergianvandning: nan
EgiPrimarenergianvandning2020_calc: 10876
EgiPrimarenergital: nan
EgiPrimarenergital2019: nan
EgiPrimarenergital2020: nan
EgiPrimarenergital2020_calc: 68
EgiPumpFranluft: 5500.0
EgiPumpFranluftUPPV: 4220
EgiPumpLuftLuft: 0.0
EgiPumpLuftLuftUPPV: 0
EgiPumpLuftVatten: 0.0
EgiPumpLuftVattenUPPV: 0
EgiPumpMark: 0.0
EgiPumpMarkUPPV: 0
EgiRefvarde1: 55
EgiRefvarde2Max: 106
EgiRefvarde2Min: 86.0
EgiRefvarde3: nan
EgiSistaArManad: nan
EgiSolcell: nan
EgiSolvarme: nan
EgiSpecifikEnergianvandning: 38.0
EgiSpecifikEnergianvandning_Eindex_calc: 38.0
EgiSpecifikEnergianvandning_calc: 38
EgiStationEI: nan
EgiStationGD: nan
EgiSumma1: 5500.0
EgiSumma2: 5976
EgiSumma3: 5976.0
EgiSumma4: 5976.0
EgiTappvarmvatten_calc: 1280
EgiUppvarmning_calc: 4220
EgiVVBered: 1280.0
EgiVaravEl: 38.0
EgiVarme_calc: 5500
EgiVed: 0.0
EgiVedUPPV: 0
EgiVedVV: 0
EgiVerksamhet: 0
EgiVersion: 2015
El_calc: 5976
EnergiIndex_calc: 1.014055
ExpertGruppHosUppdragsgivare: nan
FjarrvarmeNatNamn_calc: nan
FormularId: 752340
Godkand: 2016-12-29
HuvudsakligUppvarmning_calc: PumpFranluft
ID: 01-80-GASKEN2
IdAdr: Karin Larssons Väg 79
IdAdrAggregerad: Karin Larssons Väg 79
IdEgnaHem: 1
IdFastBet: Gasken 2
IdHusnr: 1
IdHuvudadress: Ja
IdKommun: Stockholm
IdKommunkod: 80
IdLan: Stockholms län
IdLankod: 1
IdPostnr: 12863
IdPostort: Sköndal
IdRapportLM: nan
InspLuftAngeNomEffekt: nan
InspLuftAngeNomEffektYta: nan
InspLuftBedomningNomEffekt: nan
InspLuftGruppInspSkyldighet: nan
InspLuftGruppLamplig: nan
InspLuftGruppNomStorre: nan
InspLuftLampligKommentar: nan
InspLuftUndAvtalEgipres: nan
InspLuftUndFunkOverReglBost: nan
InspLuftUndSysFastStyr: nan
InspUppvAngeNomEffekt: nan
InspUppvAngeNomEffektYta: nan
InspUppvBedomningNomEffekt: nan
InspUppvGruppInspSkyldighet: nan
InspUppvGruppLamplig: nan
InspUppvGruppNomStorre: nan
InspUppvLampligKommentar: nan
InspUppvUndAvtalEgipres: nan
InspUppvUndFunkOverReglBost: nan
InspUppvUndSysFastStyr: nan
LocalVersion_calc: 1
LuftGruppFinnsluft: Nej
SourceVersion_calc: 14.1
VentDelvisProcent: nan
VentGruppGodkand: nan
VentGruppKrav: Nej
VentGruppUtanAnm: nan
VentTypF: Nej
VentTypFT: Nej
VentTypFTX: Nej
VentTypFmed: Ja
VentTypSjalvdrag: Nej
Version: 2.4
VersionOrder_calc: 0
thread_id: ebpuetk.vtdyrjiz@kth.se:nrgr3d9szhpk
username: ebpuetk.vtdyrjiz@kth.se
Agent outputs:
 AntalByggDek_calc: 1
AntalGamlaDek_calc: 1
EgenAntalBolgh: nan
EgenAntalKallarplan: nan
EgenAntalPlan: nan
EgenAntalTrapphus: nan
EgenAtemp: 159
EgenAtempBad: nan
EgenAtempBostad: 100.0
EgenAtempButik: nan
EgenAtempHotell: nan
EgenAtempKontor: nan
EgenAtempKopcentrum: nan
EgenAtempLivsmedel: nan
EgenAtempOvrig: nan
EgenAtempOvrigaVad: nan
EgenAtempRestaurang: nan
EgenAtempSkolor: nan
EgenAtempSumma: 100
EgenAtempTeater: nan
EgenAtempVard: nan
EgenAtempVardDag: nan
EgenAvarmgarage: nan
EgenBOA: nan
EgenBRA: nan
EgenBTA: nan
EgenByggnadsKat: En- och tvåbostadshus
EgenByggnadsKatKrav2020_calc: 90
EgenByggnadsTyp: Friliggande
EgenGruppAtemp: Mätt
EgenInstEleffektStorre: Ja
EgenKomplexitet: Enkel
EgenLOA: nan
EgenNybyggAr: 2016
EgenProjVentFlode: nan
EgenSarskiltVardefull: Nej
EgenSkyddadByggnad: Nej
EgenSkyddadEllerVardefull: nan
EgenSmaLagenheter: Nej
EgenTypkod: 220
EgenTypkod_typ: 220 - Småhusenhet, bebyggd
EgiBerElProduktion: nan
EgiBerEngProduktion: nan
EgiBeraknatVarde: Ja
EgiElDirekt: 0.0
EgiElDirektUPPV: 0
EgiElLuft: 0.0
EgiElLuftUPPV: 0
EgiElVV: 1280
EgiElVatten: 0.0
EgiElVattenUPPV: 0
EgiEnergiPrestanda: 38
EgiEnergianvandning: nan
EgiEnergianvandning_Eindex_calc: 6042.0
EgiEnergianvandning_calc: 6042
EgiEnergiklass: B
EgiEnergiklass2016_calc: B
EgiEnergiklass2020_calc: C
EgiFastighet: 476
EgiFgeo_calc: 1
EgiFjarrkyla: 0
EgiFjarrvarme: 0.0
EgiFjarrvarmeUPPV: 0
EgiFjarrvarmeVV: 0
EgiFlis: 0.0
EgiFlisUPPV: 0
EgiFlisVV: 0
EgiForstaArManad: nan
EgiGas: 0.0
EgiGasUPPV: 0
EgiGasVV: 0
EgiGruppElDirekt: nan
EgiGruppElLuft: nan
EgiGruppElVatten: nan
EgiGruppFastighet: nan
EgiGruppFjarrkyla: nan
EgiGruppFjarrvarme: nan
EgiGruppFlis: nan
EgiGruppGas: nan
EgiGruppHushall: nan
EgiGruppKomfort: nan
EgiGruppOlja: nan
EgiGruppOvrBiobransle: nan
EgiGruppPumpFranluft: nan
EgiGruppPumpLuftLuft: nan
EgiGruppPumpLuftVatten: nan
EgiGruppPumpMark: nan
EgiGruppSolcell: Nej
EgiGruppSolvarme: Nej
EgiGruppVVBered: nan
EgiGruppVed: nan
EgiGruppVerksamhet: nan
EgiHushall: 0
EgiKomfort: 0
EgiKomfortTillagg: 0
EgiNormKorrEI: nan
EgiNormKorrGD: nan
EgiOlja: 0.0
EgiOljaUPPV: 0
EgiOljaVV: 0
EgiOvrBiobransle: 0.0
EgiOvrBiobransleUPPV: 0
EgiOvrBiobransleVV: 0
EgiPrimarenergianvandning: nan
EgiPrimarenergianvandning2020_calc: 10876
EgiPrimarenergital: nan
EgiPrimarenergital2019: nan
EgiPrimarenergital2020: nan
EgiPrimarenergital2020_calc: 68
EgiPumpFranluft: 5500.0
EgiPumpFranluftUPPV: 4220
EgiPumpLuftLuft: 0.0
EgiPumpLuftLuftUPPV: 0
EgiPumpLuftVatten: 0.0
EgiPumpLuftVattenUPPV: 0
EgiPumpMark: 0.0
EgiPumpMarkUPPV: 0
EgiRefvarde1: 55
EgiRefvarde2Max: 106
EgiRefvarde2Min: 86.0
EgiRefvarde3: nan
EgiSistaArManad: nan
EgiSolcell: nan
EgiSolvarme: nan
EgiSpecifikEnergianvandning: 38.0
EgiSpecifikEnergianvandning_Eindex_calc: 38.0
EgiSpecifikEnergianvandning_calc: 38
EgiStationEI: nan
EgiStationGD: nan
EgiSumma1: 5500.0
EgiSumma2: 5976
EgiSumma3: 5976.0
EgiSumma4: 5976.0
EgiTappvarmvatten_calc: 1280
EgiUppvarmning_calc: 4220
EgiVVBered: 1280.0
EgiVaravEl: 38.0
EgiVarme_calc: 5500
EgiVed: 0.0
EgiVedUPPV: 0
EgiVedVV: 0
EgiVerksamhet: 0
EgiVersion: 2015
El_calc: 5976
EnergiIndex_calc: 1.014055
ExpertGruppHosUppdragsgivare: nan
FjarrvarmeNatNamn_calc: nan
FormularId: 752340
Godkand: 2016-12-29
HuvudsakligUppvarmning_calc: PumpFranluft
ID: 01-80-GASKEN2
IdAdr: Karin Larssons Väg 79
IdAdrAggregerad: Karin Larssons Väg 79
IdEgnaHem: 1
IdFastBet: Gasken 2
IdHusnr: 1
IdHuvudadress: Ja
IdKommun: Stockholm
IdKommunkod: 80
IdLan: Stockholms län
IdLankod: 1
IdPostnr: 12863
IdPostort: Sköndal
IdRapportLM: nan
InspLuftAngeNomEffekt: nan
InspLuftAngeNomEffektYta: nan
InspLuftBedomningNomEffekt: nan
InspLuftGruppInspSkyldighet: nan
InspLuftGruppLamplig: nan
InspLuftGruppNomStorre: nan
InspLuftLampligKommentar: nan
InspLuftUndAvtalEgipres: nan
InspLuftUndFunkOverReglBost: nan
InspLuftUndSysFastStyr: nan
InspUppvAngeNomEffekt: nan
InspUppvAngeNomEffektYta: nan
InspUppvBedomningNomEffekt: nan
InspUppvGruppInspSkyldighet: nan
InspUppvGruppLamplig: nan
InspUppvGruppNomStorre: nan
InspUppvLampligKommentar: nan
InspUppvUndAvtalEgipres: nan
InspUppvUndFunkOverReglBost: nan
InspUppvUndSysFastStyr: nan
LocalVersion_calc: 1
LuftGruppFinnsluft: Nej
SourceVersion_calc: 14.1
VentDelvisProcent: nan
VentGruppGodkand: nan
VentGruppKrav: Nej
VentGruppUtanAnm: nan
VentTypF: Nej
VentTypFT: Nej
VentTypFTX: Nej
VentTypFmed: Ja
VentTypSjalvdrag: Nej
Version: 2.4
VersionOrder_calc: 0
thread_id: ebpuetk.vtdyrjiz@kth.se:nrgr3d9szhpk
username: ebpuetk.vtdyrjiz@kth.se
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "källarplan"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "källarplan"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [18] basement_count_sv ===
Address: Danderydsgatan 8
Thread ID: jmEJBwCFlQPfEiKqaxpW:ogd0d3c1f5n5
Building ID (pre): 01-80-NAEKTERGALEN17
Detected intent: query generic database | entities: ['Danderydsgatan 8', 'källarplan'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Danderydsgatan 8'}
Graph metadata.building_id (post): 1
Final response: Summary of: basement_count: nan
Agent outputs:
 basement_count: nan
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "trapphus"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "trapphus"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [19] stairs_count_sv ===
Address: Danderydsgatan 8
Thread ID: jmEJBwCFlQPfEiKqaxpW:ogd0d3c1f5n5
Building ID (pre): 01-80-NAEKTERGALEN17
Detected intent: query generic database | entities: ['Danderydsgatan 8', 'trapphus'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Danderydsgatan 8'}
Graph metadata.building_id (post): 1
Final response: Summary of: stairs_count: nan
Agent outputs:
 stairs_count: nan
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "nätavgiften", "byggnad"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "nätavgiften", "byggnad"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [20] tariff_sv ===
Address: Danderydsgatan 8
Thread ID: jmEJBwCFlQPfEiKqaxpW:ogd0d3c1f5n5
Building ID (pre): 01-80-NAEKTERGALEN17
Detected intent: query generic database | entities: ['Danderydsgatan 8', 'nätavgiften', 'byggnad'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Danderydsgatan 8'}
Graph metadata.building_id (post): 1
Final response: Summary of: tariff_name: None
Agent outputs:
 tariff_name: None
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

########## SAMPLE 3 / 3 :: Skattegränd 4C ##########

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "energy class"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "energy class"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [21] energy_class ===
Address: Skattegränd 4C
Thread ID: Doitd8TOS4UUKolqXVKq:mpopowz4r46k
Building ID (pre): 01-80-OESTEN14
Detected intent: query generic database | entities: ['Skattegränd 4C', 'energy class'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Skattegränd 4C'}
Graph metadata.building_id (post): 1
Final response: Summary of: energy_class: C
Agent outputs:
 energy_class: C
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "address", "entities": ["Skattegränd 4C"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [22] energy_class_sv ===
Address: Skattegränd 4C
Thread ID: Doitd8TOS4UUKolqXVKq:mpopowz4r46k
Building ID (pre): 01-80-OESTEN14
Detected intent: query generic database | entities: ['Skattegränd 4C'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Skattegränd 4C'}
Graph metadata.building_id (post): None
Final response: Summary of: Fallback agent result
Agent outputs:
 Fallback agent result
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "kWh", "electricity"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "kWh", "electricity"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [23] electricity_usage ===
Address: Skattegränd 4C
Thread ID: Doitd8TOS4UUKolqXVKq:mpopowz4r46k
Building ID (pre): 01-80-OESTEN14
Detected intent: query generic database | entities: ['Skattegränd 4C', 'kWh', 'electricity'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Skattegränd 4C'}
Graph metadata.building_id (post): 1
Final response: Summary of: el_calc: 5976
Agent outputs:
 el_calc: 5976
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["För Skattegränd 4C", "kWh el"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["För Skattegränd 4C", "kWh el"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [24] electricity_usage_sv ===
Address: Skattegränd 4C
Thread ID: Doitd8TOS4UUKolqXVKq:mpopowz4r46k
Building ID (pre): 01-80-OESTEN14
Detected intent: query generic database | entities: ['För Skattegränd 4C', 'kWh el'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Skattegränd 4C'}
Graph metadata.building_id (post): 1
Final response: Summary of: el_calc: 5976
Agent outputs:
 el_calc: 5976
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

WARNING:src.agents.parse_intent_agent:Intent classification timed out.

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skaattegränd 4C", "heating kWh", "värmeanvändning"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [25] heating_usage ===
Address: Skattegränd 4C
Thread ID: Doitd8TOS4UUKolqXVKq:mpopowz4r46k
Building ID (pre): 01-80-OESTEN14
Detected intent: unknown | entities: [] | ambiguous: False
Mapper routed op: noop | kwargs: {}
Graph metadata.building_id (post): 1
Final response: Summary of: varme_calc: 5500
Agent outputs:
 varme_calc: 5500
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "huvudsakliga uppvärmningen"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "huvudsakliga uppvärmningen"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [26] primary_heating_sv ===
Address: Skattegränd 4C
Thread ID: Doitd8TOS4UUKolqXVKq:mpopowz4r46k
Building ID (pre): 01-80-OESTEN14
Detected intent: query generic database | entities: ['Skattegränd 4C', 'huvudsakliga uppvärmningen'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Skattegränd 4C'}
Graph metadata.building_id (post): 1
Final response: Summary of: AntalByggDek_calc: 1
AntalGamlaDek_calc: 1
EgenAntalBolgh: nan
EgenAntalKallarplan: nan
EgenAntalPlan: nan
EgenAntalTrapphus: nan
EgenAtemp: 159
EgenAtempBad: nan
EgenAtempBostad: 100.0
EgenAtempButik: nan
EgenAtempHotell: nan
EgenAtempKontor: nan
EgenAtempKopcentrum: nan
EgenAtempLivsmedel: nan
EgenAtempOvrig: nan
EgenAtempOvrigaVad: nan
EgenAtempRestaurang: nan
EgenAtempSkolor: nan
EgenAtempSumma: 100
EgenAtempTeater: nan
EgenAtempVard: nan
EgenAtempVardDag: nan
EgenAvarmgarage: nan
EgenBOA: nan
EgenBRA: nan
EgenBTA: nan
EgenByggnadsKat: En- och tvåbostadshus
EgenByggnadsKatKrav2020_calc: 90
EgenByggnadsTyp: Friliggande
EgenGruppAtemp: Mätt
EgenInstEleffektStorre: Ja
EgenKomplexitet: Enkel
EgenLOA: nan
EgenNybyggAr: 2016
EgenProjVentFlode: nan
EgenSarskiltVardefull: Nej
EgenSkyddadByggnad: Nej
EgenSkyddadEllerVardefull: nan
EgenSmaLagenheter: Nej
EgenTypkod: 220
EgenTypkod_typ: 220 - Småhusenhet, bebyggd
EgiBerElProduktion: nan
EgiBerEngProduktion: nan
EgiBeraknatVarde: Ja
EgiElDirekt: 0.0
EgiElDirektUPPV: 0
EgiElLuft: 0.0
EgiElLuftUPPV: 0
EgiElVV: 1280
EgiElVatten: 0.0
EgiElVattenUPPV: 0
EgiEnergiPrestanda: 38
EgiEnergianvandning: nan
EgiEnergianvandning_Eindex_calc: 6042.0
EgiEnergianvandning_calc: 6042
EgiEnergiklass: B
EgiEnergiklass2016_calc: B
EgiEnergiklass2020_calc: C
EgiFastighet: 476
EgiFgeo_calc: 1
EgiFjarrkyla: 0
EgiFjarrvarme: 0.0
EgiFjarrvarmeUPPV: 0
EgiFjarrvarmeVV: 0
EgiFlis: 0.0
EgiFlisUPPV: 0
EgiFlisVV: 0
EgiForstaArManad: nan
EgiGas: 0.0
EgiGasUPPV: 0
EgiGasVV: 0
EgiGruppElDirekt: nan
EgiGruppElLuft: nan
EgiGruppElVatten: nan
EgiGruppFastighet: nan
EgiGruppFjarrkyla: nan
EgiGruppFjarrvarme: nan
EgiGruppFlis: nan
EgiGruppGas: nan
EgiGruppHushall: nan
EgiGruppKomfort: nan
EgiGruppOlja: nan
EgiGruppOvrBiobransle: nan
EgiGruppPumpFranluft: nan
EgiGruppPumpLuftLuft: nan
EgiGruppPumpLuftVatten: nan
EgiGruppPumpMark: nan
EgiGruppSolcell: Nej
EgiGruppSolvarme: Nej
EgiGruppVVBered: nan
EgiGruppVed: nan
EgiGruppVerksamhet: nan
EgiHushall: 0
EgiKomfort: 0
EgiKomfortTillagg: 0
EgiNormKorrEI: nan
EgiNormKorrGD: nan
EgiOlja: 0.0
EgiOljaUPPV: 0
EgiOljaVV: 0
EgiOvrBiobransle: 0.0
EgiOvrBiobransleUPPV: 0
EgiOvrBiobransleVV: 0
EgiPrimarenergianvandning: nan
EgiPrimarenergianvandning2020_calc: 10876
EgiPrimarenergital: nan
EgiPrimarenergital2019: nan
EgiPrimarenergital2020: nan
EgiPrimarenergital2020_calc: 68
EgiPumpFranluft: 5500.0
EgiPumpFranluftUPPV: 4220
EgiPumpLuftLuft: 0.0
EgiPumpLuftLuftUPPV: 0
EgiPumpLuftVatten: 0.0
EgiPumpLuftVattenUPPV: 0
EgiPumpMark: 0.0
EgiPumpMarkUPPV: 0
EgiRefvarde1: 55
EgiRefvarde2Max: 106
EgiRefvarde2Min: 86.0
EgiRefvarde3: nan
EgiSistaArManad: nan
EgiSolcell: nan
EgiSolvarme: nan
EgiSpecifikEnergianvandning: 38.0
EgiSpecifikEnergianvandning_Eindex_calc: 38.0
EgiSpecifikEnergianvandning_calc: 38
EgiStationEI: nan
EgiStationGD: nan
EgiSumma1: 5500.0
EgiSumma2: 5976
EgiSumma3: 5976.0
EgiSumma4: 5976.0
EgiTappvarmvatten_calc: 1280
EgiUppvarmning_calc: 4220
EgiVVBered: 1280.0
EgiVaravEl: 38.0
EgiVarme_calc: 5500
EgiVed: 0.0
EgiVedUPPV: 0
EgiVedVV: 0
EgiVerksamhet: 0
EgiVersion: 2015
El_calc: 5976
EnergiIndex_calc: 1.014055
ExpertGruppHosUppdragsgivare: nan
FjarrvarmeNatNamn_calc: nan
FormularId: 752340
Godkand: 2016-12-29
HuvudsakligUppvarmning_calc: PumpFranluft
ID: 01-80-GASKEN2
IdAdr: Karin Larssons Väg 79
IdAdrAggregerad: Karin Larssons Väg 79
IdEgnaHem: 1
IdFastBet: Gasken 2
IdHusnr: 1
IdHuvudadress: Ja
IdKommun: Stockholm
IdKommunkod: 80
IdLan: Stockholms län
IdLankod: 1
IdPostnr: 12863
IdPostort: Sköndal
IdRapportLM: nan
InspLuftAngeNomEffekt: nan
InspLuftAngeNomEffektYta: nan
InspLuftBedomningNomEffekt: nan
InspLuftGruppInspSkyldighet: nan
InspLuftGruppLamplig: nan
InspLuftGruppNomStorre: nan
InspLuftLampligKommentar: nan
InspLuftUndAvtalEgipres: nan
InspLuftUndFunkOverReglBost: nan
InspLuftUndSysFastStyr: nan
InspUppvAngeNomEffekt: nan
InspUppvAngeNomEffektYta: nan
InspUppvBedomningNomEffekt: nan
InspUppvGruppInspSkyldighet: nan
InspUppvGruppLamplig: nan
InspUppvGruppNomStorre: nan
InspUppvLampligKommentar: nan
InspUppvUndAvtalEgipres: nan
InspUppvUndFunkOverReglBost: nan
InspUppvUndSysFastStyr: nan
LocalVersion_calc: 1
LuftGruppFinnsluft: Nej
SourceVersion_calc: 14.1
VentDelvisProcent: nan
VentGruppGodkand: nan
VentGruppKrav: Nej
VentGruppUtanAnm: nan
VentTypF: Nej
VentTypFT: Nej
VentTypFTX: Nej
VentTypFmed: Ja
VentTypSjalvdrag: Nej
Version: 2.4
VersionOrder_calc: 0
thread_id: ebpuetk.vtdyrjiz@kth.se:nrgr3d9szhpk
username: ebpuetk.vtdyrjiz@kth.se
Agent outputs:
 AntalByggDek_calc: 1
AntalGamlaDek_calc: 1
EgenAntalBolgh: nan
EgenAntalKallarplan: nan
EgenAntalPlan: nan
EgenAntalTrapphus: nan
EgenAtemp: 159
EgenAtempBad: nan
EgenAtempBostad: 100.0
EgenAtempButik: nan
EgenAtempHotell: nan
EgenAtempKontor: nan
EgenAtempKopcentrum: nan
EgenAtempLivsmedel: nan
EgenAtempOvrig: nan
EgenAtempOvrigaVad: nan
EgenAtempRestaurang: nan
EgenAtempSkolor: nan
EgenAtempSumma: 100
EgenAtempTeater: nan
EgenAtempVard: nan
EgenAtempVardDag: nan
EgenAvarmgarage: nan
EgenBOA: nan
EgenBRA: nan
EgenBTA: nan
EgenByggnadsKat: En- och tvåbostadshus
EgenByggnadsKatKrav2020_calc: 90
EgenByggnadsTyp: Friliggande
EgenGruppAtemp: Mätt
EgenInstEleffektStorre: Ja
EgenKomplexitet: Enkel
EgenLOA: nan
EgenNybyggAr: 2016
EgenProjVentFlode: nan
EgenSarskiltVardefull: Nej
EgenSkyddadByggnad: Nej
EgenSkyddadEllerVardefull: nan
EgenSmaLagenheter: Nej
EgenTypkod: 220
EgenTypkod_typ: 220 - Småhusenhet, bebyggd
EgiBerElProduktion: nan
EgiBerEngProduktion: nan
EgiBeraknatVarde: Ja
EgiElDirekt: 0.0
EgiElDirektUPPV: 0
EgiElLuft: 0.0
EgiElLuftUPPV: 0
EgiElVV: 1280
EgiElVatten: 0.0
EgiElVattenUPPV: 0
EgiEnergiPrestanda: 38
EgiEnergianvandning: nan
EgiEnergianvandning_Eindex_calc: 6042.0
EgiEnergianvandning_calc: 6042
EgiEnergiklass: B
EgiEnergiklass2016_calc: B
EgiEnergiklass2020_calc: C
EgiFastighet: 476
EgiFgeo_calc: 1
EgiFjarrkyla: 0
EgiFjarrvarme: 0.0
EgiFjarrvarmeUPPV: 0
EgiFjarrvarmeVV: 0
EgiFlis: 0.0
EgiFlisUPPV: 0
EgiFlisVV: 0
EgiForstaArManad: nan
EgiGas: 0.0
EgiGasUPPV: 0
EgiGasVV: 0
EgiGruppElDirekt: nan
EgiGruppElLuft: nan
EgiGruppElVatten: nan
EgiGruppFastighet: nan
EgiGruppFjarrkyla: nan
EgiGruppFjarrvarme: nan
EgiGruppFlis: nan
EgiGruppGas: nan
EgiGruppHushall: nan
EgiGruppKomfort: nan
EgiGruppOlja: nan
EgiGruppOvrBiobransle: nan
EgiGruppPumpFranluft: nan
EgiGruppPumpLuftLuft: nan
EgiGruppPumpLuftVatten: nan
EgiGruppPumpMark: nan
EgiGruppSolcell: Nej
EgiGruppSolvarme: Nej
EgiGruppVVBered: nan
EgiGruppVed: nan
EgiGruppVerksamhet: nan
EgiHushall: 0
EgiKomfort: 0
EgiKomfortTillagg: 0
EgiNormKorrEI: nan
EgiNormKorrGD: nan
EgiOlja: 0.0
EgiOljaUPPV: 0
EgiOljaVV: 0
EgiOvrBiobransle: 0.0
EgiOvrBiobransleUPPV: 0
EgiOvrBiobransleVV: 0
EgiPrimarenergianvandning: nan
EgiPrimarenergianvandning2020_calc: 10876
EgiPrimarenergital: nan
EgiPrimarenergital2019: nan
EgiPrimarenergital2020: nan
EgiPrimarenergital2020_calc: 68
EgiPumpFranluft: 5500.0
EgiPumpFranluftUPPV: 4220
EgiPumpLuftLuft: 0.0
EgiPumpLuftLuftUPPV: 0
EgiPumpLuftVatten: 0.0
EgiPumpLuftVattenUPPV: 0
EgiPumpMark: 0.0
EgiPumpMarkUPPV: 0
EgiRefvarde1: 55
EgiRefvarde2Max: 106
EgiRefvarde2Min: 86.0
EgiRefvarde3: nan
EgiSistaArManad: nan
EgiSolcell: nan
EgiSolvarme: nan
EgiSpecifikEnergianvandning: 38.0
EgiSpecifikEnergianvandning_Eindex_calc: 38.0
EgiSpecifikEnergianvandning_calc: 38
EgiStationEI: nan
EgiStationGD: nan
EgiSumma1: 5500.0
EgiSumma2: 5976
EgiSumma3: 5976.0
EgiSumma4: 5976.0
EgiTappvarmvatten_calc: 1280
EgiUppvarmning_calc: 4220
EgiVVBered: 1280.0
EgiVaravEl: 38.0
EgiVarme_calc: 5500
EgiVed: 0.0
EgiVedUPPV: 0
EgiVedVV: 0
EgiVerksamhet: 0
EgiVersion: 2015
El_calc: 5976
EnergiIndex_calc: 1.014055
ExpertGruppHosUppdragsgivare: nan
FjarrvarmeNatNamn_calc: nan
FormularId: 752340
Godkand: 2016-12-29
HuvudsakligUppvarmning_calc: PumpFranluft
ID: 01-80-GASKEN2
IdAdr: Karin Larssons Väg 79
IdAdrAggregerad: Karin Larssons Väg 79
IdEgnaHem: 1
IdFastBet: Gasken 2
IdHusnr: 1
IdHuvudadress: Ja
IdKommun: Stockholm
IdKommunkod: 80
IdLan: Stockholms län
IdLankod: 1
IdPostnr: 12863
IdPostort: Sköndal
IdRapportLM: nan
InspLuftAngeNomEffekt: nan
InspLuftAngeNomEffektYta: nan
InspLuftBedomningNomEffekt: nan
InspLuftGruppInspSkyldighet: nan
InspLuftGruppLamplig: nan
InspLuftGruppNomStorre: nan
InspLuftLampligKommentar: nan
InspLuftUndAvtalEgipres: nan
InspLuftUndFunkOverReglBost: nan
InspLuftUndSysFastStyr: nan
InspUppvAngeNomEffekt: nan
InspUppvAngeNomEffektYta: nan
InspUppvBedomningNomEffekt: nan
InspUppvGruppInspSkyldighet: nan
InspUppvGruppLamplig: nan
InspUppvGruppNomStorre: nan
InspUppvLampligKommentar: nan
InspUppvUndAvtalEgipres: nan
InspUppvUndFunkOverReglBost: nan
InspUppvUndSysFastStyr: nan
LocalVersion_calc: 1
LuftGruppFinnsluft: Nej
SourceVersion_calc: 14.1
VentDelvisProcent: nan
VentGruppGodkand: nan
VentGruppKrav: Nej
VentGruppUtanAnm: nan
VentTypF: Nej
VentTypFT: Nej
VentTypFTX: Nej
VentTypFmed: Ja
VentTypSjalvdrag: Nej
Version: 2.4
VersionOrder_calc: 0
thread_id: ebpuetk.vtdyrjiz@kth.se:nrgr3d9szhpk
username: ebpuetk.vtdyrjiz@kth.se
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "heated area", "Atemp"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "heated area", "Atemp"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [27] heated_area ===
Address: Skattegränd 4C
Thread ID: Doitd8TOS4UUKolqXVKq:mpopowz4r46k
Building ID (pre): 01-80-OESTEN14
Detected intent: query generic database | entities: ['Skattegränd 4C', 'heated area', 'Atemp'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Skattegränd 4C'}
Graph metadata.building_id (post): 1
Final response: Summary of: AntalByggDek_calc: 1
AntalGamlaDek_calc: 1
EgenAntalBolgh: nan
EgenAntalKallarplan: nan
EgenAntalPlan: nan
EgenAntalTrapphus: nan
EgenAtemp: 159
EgenAtempBad: nan
EgenAtempBostad: 100.0
EgenAtempButik: nan
EgenAtempHotell: nan
EgenAtempKontor: nan
EgenAtempKopcentrum: nan
EgenAtempLivsmedel: nan
EgenAtempOvrig: nan
EgenAtempOvrigaVad: nan
EgenAtempRestaurang: nan
EgenAtempSkolor: nan
EgenAtempSumma: 100
EgenAtempTeater: nan
EgenAtempVard: nan
EgenAtempVardDag: nan
EgenAvarmgarage: nan
EgenBOA: nan
EgenBRA: nan
EgenBTA: nan
EgenByggnadsKat: En- och tvåbostadshus
EgenByggnadsKatKrav2020_calc: 90
EgenByggnadsTyp: Friliggande
EgenGruppAtemp: Mätt
EgenInstEleffektStorre: Ja
EgenKomplexitet: Enkel
EgenLOA: nan
EgenNybyggAr: 2016
EgenProjVentFlode: nan
EgenSarskiltVardefull: Nej
EgenSkyddadByggnad: Nej
EgenSkyddadEllerVardefull: nan
EgenSmaLagenheter: Nej
EgenTypkod: 220
EgenTypkod_typ: 220 - Småhusenhet, bebyggd
EgiBerElProduktion: nan
EgiBerEngProduktion: nan
EgiBeraknatVarde: Ja
EgiElDirekt: 0.0
EgiElDirektUPPV: 0
EgiElLuft: 0.0
EgiElLuftUPPV: 0
EgiElVV: 1280
EgiElVatten: 0.0
EgiElVattenUPPV: 0
EgiEnergiPrestanda: 38
EgiEnergianvandning: nan
EgiEnergianvandning_Eindex_calc: 6042.0
EgiEnergianvandning_calc: 6042
EgiEnergiklass: B
EgiEnergiklass2016_calc: B
EgiEnergiklass2020_calc: C
EgiFastighet: 476
EgiFgeo_calc: 1
EgiFjarrkyla: 0
EgiFjarrvarme: 0.0
EgiFjarrvarmeUPPV: 0
EgiFjarrvarmeVV: 0
EgiFlis: 0.0
EgiFlisUPPV: 0
EgiFlisVV: 0
EgiForstaArManad: nan
EgiGas: 0.0
EgiGasUPPV: 0
EgiGasVV: 0
EgiGruppElDirekt: nan
EgiGruppElLuft: nan
EgiGruppElVatten: nan
EgiGruppFastighet: nan
EgiGruppFjarrkyla: nan
EgiGruppFjarrvarme: nan
EgiGruppFlis: nan
EgiGruppGas: nan
EgiGruppHushall: nan
EgiGruppKomfort: nan
EgiGruppOlja: nan
EgiGruppOvrBiobransle: nan
EgiGruppPumpFranluft: nan
EgiGruppPumpLuftLuft: nan
EgiGruppPumpLuftVatten: nan
EgiGruppPumpMark: nan
EgiGruppSolcell: Nej
EgiGruppSolvarme: Nej
EgiGruppVVBered: nan
EgiGruppVed: nan
EgiGruppVerksamhet: nan
EgiHushall: 0
EgiKomfort: 0
EgiKomfortTillagg: 0
EgiNormKorrEI: nan
EgiNormKorrGD: nan
EgiOlja: 0.0
EgiOljaUPPV: 0
EgiOljaVV: 0
EgiOvrBiobransle: 0.0
EgiOvrBiobransleUPPV: 0
EgiOvrBiobransleVV: 0
EgiPrimarenergianvandning: nan
EgiPrimarenergianvandning2020_calc: 10876
EgiPrimarenergital: nan
EgiPrimarenergital2019: nan
EgiPrimarenergital2020: nan
EgiPrimarenergital2020_calc: 68
EgiPumpFranluft: 5500.0
EgiPumpFranluftUPPV: 4220
EgiPumpLuftLuft: 0.0
EgiPumpLuftLuftUPPV: 0
EgiPumpLuftVatten: 0.0
EgiPumpLuftVattenUPPV: 0
EgiPumpMark: 0.0
EgiPumpMarkUPPV: 0
EgiRefvarde1: 55
EgiRefvarde2Max: 106
EgiRefvarde2Min: 86.0
EgiRefvarde3: nan
EgiSistaArManad: nan
EgiSolcell: nan
EgiSolvarme: nan
EgiSpecifikEnergianvandning: 38.0
EgiSpecifikEnergianvandning_Eindex_calc: 38.0
EgiSpecifikEnergianvandning_calc: 38
EgiStationEI: nan
EgiStationGD: nan
EgiSumma1: 5500.0
EgiSumma2: 5976
EgiSumma3: 5976.0
EgiSumma4: 5976.0
EgiTappvarmvatten_calc: 1280
EgiUppvarmning_calc: 4220
EgiVVBered: 1280.0
EgiVaravEl: 38.0
EgiVarme_calc: 5500
EgiVed: 0.0
EgiVedUPPV: 0
EgiVedVV: 0
EgiVerksamhet: 0
EgiVersion: 2015
El_calc: 5976
EnergiIndex_calc: 1.014055
ExpertGruppHosUppdragsgivare: nan
FjarrvarmeNatNamn_calc: nan
FormularId: 752340
Godkand: 2016-12-29
HuvudsakligUppvarmning_calc: PumpFranluft
ID: 01-80-GASKEN2
IdAdr: Karin Larssons Väg 79
IdAdrAggregerad: Karin Larssons Väg 79
IdEgnaHem: 1
IdFastBet: Gasken 2
IdHusnr: 1
IdHuvudadress: Ja
IdKommun: Stockholm
IdKommunkod: 80
IdLan: Stockholms län
IdLankod: 1
IdPostnr: 12863
IdPostort: Sköndal
IdRapportLM: nan
InspLuftAngeNomEffekt: nan
InspLuftAngeNomEffektYta: nan
InspLuftBedomningNomEffekt: nan
InspLuftGruppInspSkyldighet: nan
InspLuftGruppLamplig: nan
InspLuftGruppNomStorre: nan
InspLuftLampligKommentar: nan
InspLuftUndAvtalEgipres: nan
InspLuftUndFunkOverReglBost: nan
InspLuftUndSysFastStyr: nan
InspUppvAngeNomEffekt: nan
InspUppvAngeNomEffektYta: nan
InspUppvBedomningNomEffekt: nan
InspUppvGruppInspSkyldighet: nan
InspUppvGruppLamplig: nan
InspUppvGruppNomStorre: nan
InspUppvLampligKommentar: nan
InspUppvUndAvtalEgipres: nan
InspUppvUndFunkOverReglBost: nan
InspUppvUndSysFastStyr: nan
LocalVersion_calc: 1
LuftGruppFinnsluft: Nej
SourceVersion_calc: 14.1
VentDelvisProcent: nan
VentGruppGodkand: nan
VentGruppKrav: Nej
VentGruppUtanAnm: nan
VentTypF: Nej
VentTypFT: Nej
VentTypFTX: Nej
VentTypFmed: Ja
VentTypSjalvdrag: Nej
Version: 2.4
VersionOrder_calc: 0
thread_id: ebpuetk.vtdyrjiz@kth.se:nrgr3d9szhpk
username: ebpuetk.vtdyrjiz@kth.se
Agent outputs:
 AntalByggDek_calc: 1
AntalGamlaDek_calc: 1
EgenAntalBolgh: nan
EgenAntalKallarplan: nan
EgenAntalPlan: nan
EgenAntalTrapphus: nan
EgenAtemp: 159
EgenAtempBad: nan
EgenAtempBostad: 100.0
EgenAtempButik: nan
EgenAtempHotell: nan
EgenAtempKontor: nan
EgenAtempKopcentrum: nan
EgenAtempLivsmedel: nan
EgenAtempOvrig: nan
EgenAtempOvrigaVad: nan
EgenAtempRestaurang: nan
EgenAtempSkolor: nan
EgenAtempSumma: 100
EgenAtempTeater: nan
EgenAtempVard: nan
EgenAtempVardDag: nan
EgenAvarmgarage: nan
EgenBOA: nan
EgenBRA: nan
EgenBTA: nan
EgenByggnadsKat: En- och tvåbostadshus
EgenByggnadsKatKrav2020_calc: 90
EgenByggnadsTyp: Friliggande
EgenGruppAtemp: Mätt
EgenInstEleffektStorre: Ja
EgenKomplexitet: Enkel
EgenLOA: nan
EgenNybyggAr: 2016
EgenProjVentFlode: nan
EgenSarskiltVardefull: Nej
EgenSkyddadByggnad: Nej
EgenSkyddadEllerVardefull: nan
EgenSmaLagenheter: Nej
EgenTypkod: 220
EgenTypkod_typ: 220 - Småhusenhet, bebyggd
EgiBerElProduktion: nan
EgiBerEngProduktion: nan
EgiBeraknatVarde: Ja
EgiElDirekt: 0.0
EgiElDirektUPPV: 0
EgiElLuft: 0.0
EgiElLuftUPPV: 0
EgiElVV: 1280
EgiElVatten: 0.0
EgiElVattenUPPV: 0
EgiEnergiPrestanda: 38
EgiEnergianvandning: nan
EgiEnergianvandning_Eindex_calc: 6042.0
EgiEnergianvandning_calc: 6042
EgiEnergiklass: B
EgiEnergiklass2016_calc: B
EgiEnergiklass2020_calc: C
EgiFastighet: 476
EgiFgeo_calc: 1
EgiFjarrkyla: 0
EgiFjarrvarme: 0.0
EgiFjarrvarmeUPPV: 0
EgiFjarrvarmeVV: 0
EgiFlis: 0.0
EgiFlisUPPV: 0
EgiFlisVV: 0
EgiForstaArManad: nan
EgiGas: 0.0
EgiGasUPPV: 0
EgiGasVV: 0
EgiGruppElDirekt: nan
EgiGruppElLuft: nan
EgiGruppElVatten: nan
EgiGruppFastighet: nan
EgiGruppFjarrkyla: nan
EgiGruppFjarrvarme: nan
EgiGruppFlis: nan
EgiGruppGas: nan
EgiGruppHushall: nan
EgiGruppKomfort: nan
EgiGruppOlja: nan
EgiGruppOvrBiobransle: nan
EgiGruppPumpFranluft: nan
EgiGruppPumpLuftLuft: nan
EgiGruppPumpLuftVatten: nan
EgiGruppPumpMark: nan
EgiGruppSolcell: Nej
EgiGruppSolvarme: Nej
EgiGruppVVBered: nan
EgiGruppVed: nan
EgiGruppVerksamhet: nan
EgiHushall: 0
EgiKomfort: 0
EgiKomfortTillagg: 0
EgiNormKorrEI: nan
EgiNormKorrGD: nan
EgiOlja: 0.0
EgiOljaUPPV: 0
EgiOljaVV: 0
EgiOvrBiobransle: 0.0
EgiOvrBiobransleUPPV: 0
EgiOvrBiobransleVV: 0
EgiPrimarenergianvandning: nan
EgiPrimarenergianvandning2020_calc: 10876
EgiPrimarenergital: nan
EgiPrimarenergital2019: nan
EgiPrimarenergital2020: nan
EgiPrimarenergital2020_calc: 68
EgiPumpFranluft: 5500.0
EgiPumpFranluftUPPV: 4220
EgiPumpLuftLuft: 0.0
EgiPumpLuftLuftUPPV: 0
EgiPumpLuftVatten: 0.0
EgiPumpLuftVattenUPPV: 0
EgiPumpMark: 0.0
EgiPumpMarkUPPV: 0
EgiRefvarde1: 55
EgiRefvarde2Max: 106
EgiRefvarde2Min: 86.0
EgiRefvarde3: nan
EgiSistaArManad: nan
EgiSolcell: nan
EgiSolvarme: nan
EgiSpecifikEnergianvandning: 38.0
EgiSpecifikEnergianvandning_Eindex_calc: 38.0
EgiSpecifikEnergianvandning_calc: 38
EgiStationEI: nan
EgiStationGD: nan
EgiSumma1: 5500.0
EgiSumma2: 5976
EgiSumma3: 5976.0
EgiSumma4: 5976.0
EgiTappvarmvatten_calc: 1280
EgiUppvarmning_calc: 4220
EgiVVBered: 1280.0
EgiVaravEl: 38.0
EgiVarme_calc: 5500
EgiVed: 0.0
EgiVedUPPV: 0
EgiVedVV: 0
EgiVerksamhet: 0
EgiVersion: 2015
El_calc: 5976
EnergiIndex_calc: 1.014055
ExpertGruppHosUppdragsgivare: nan
FjarrvarmeNatNamn_calc: nan
FormularId: 752340
Godkand: 2016-12-29
HuvudsakligUppvarmning_calc: PumpFranluft
ID: 01-80-GASKEN2
IdAdr: Karin Larssons Väg 79
IdAdrAggregerad: Karin Larssons Väg 79
IdEgnaHem: 1
IdFastBet: Gasken 2
IdHusnr: 1
IdHuvudadress: Ja
IdKommun: Stockholm
IdKommunkod: 80
IdLan: Stockholms län
IdLankod: 1
IdPostnr: 12863
IdPostort: Sköndal
IdRapportLM: nan
InspLuftAngeNomEffekt: nan
InspLuftAngeNomEffektYta: nan
InspLuftBedomningNomEffekt: nan
InspLuftGruppInspSkyldighet: nan
InspLuftGruppLamplig: nan
InspLuftGruppNomStorre: nan
InspLuftLampligKommentar: nan
InspLuftUndAvtalEgipres: nan
InspLuftUndFunkOverReglBost: nan
InspLuftUndSysFastStyr: nan
InspUppvAngeNomEffekt: nan
InspUppvAngeNomEffektYta: nan
InspUppvBedomningNomEffekt: nan
InspUppvGruppInspSkyldighet: nan
InspUppvGruppLamplig: nan
InspUppvGruppNomStorre: nan
InspUppvLampligKommentar: nan
InspUppvUndAvtalEgipres: nan
InspUppvUndFunkOverReglBost: nan
InspUppvUndSysFastStyr: nan
LocalVersion_calc: 1
LuftGruppFinnsluft: Nej
SourceVersion_calc: 14.1
VentDelvisProcent: nan
VentGruppGodkand: nan
VentGruppKrav: Nej
VentGruppUtanAnm: nan
VentTypF: Nej
VentTypFT: Nej
VentTypFTX: Nej
VentTypFmed: Ja
VentTypSjalvdrag: Nej
Version: 2.4
VersionOrder_calc: 0
thread_id: ebpuetk.vtdyrjiz@kth.se:nrgr3d9szhpk
username: ebpuetk.vtdyrjiz@kth.se
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "källarplan"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "källarplan"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [28] basement_count_sv ===
Address: Skattegränd 4C
Thread ID: Doitd8TOS4UUKolqXVKq:mpopowz4r46k
Building ID (pre): 01-80-OESTEN14
Detected intent: query generic database | entities: ['Skattegränd 4C', 'källarplan'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Skattegränd 4C'}
Graph metadata.building_id (post): 1
Final response: Summary of: basement_count: nan
Agent outputs:
 basement_count: nan
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "trapphus"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "trapphus"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [29] stairs_count_sv ===
Address: Skattegränd 4C
Thread ID: Doitd8TOS4UUKolqXVKq:mpopowz4r46k
Building ID (pre): 01-80-OESTEN14
Detected intent: query generic database | entities: ['Skattegränd 4C', 'trapphus'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Skattegränd 4C'}
Graph metadata.building_id (post): 1
Final response: Summary of: stairs_count: nan
Agent outputs:
 stairs_count: nan
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "nätavgiften", "min byggnad"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "nätavgiften", "min byggnad"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

=== [30] tariff_sv ===
Address: Skattegränd 4C
Thread ID: Doitd8TOS4UUKolqXVKq:mpopowz4r46k
Building ID (pre): 01-80-OESTEN14
Detected intent: query generic database | entities: ['Skattegränd 4C', 'nätavgiften', 'min byggnad'] | ambiguous: False
Mapper routed op: building_by_address | kwargs: {'extracted': 'Skattegränd 4C'}
Graph metadata.building_id (post): 1
Final response: Summary of: tariff_name: None
Agent outputs:
 tariff_name: None
Raw CSV highlights for this building_id:
  EgiEnergiklass2020_calc: C
  El_calc: 5976
  EgiVarme_calc: 5500
  HuvudsakligUppvarmning_calc: PumpFranluft
  EgenAntalKallarplan: None
  EgenAntalTrapphus: None
--------------------------------------------------------------------------------

#### SQL + vector database test

In [1]:
# === Mixed SQL + Vector tests (compact) ===
from src.agents.building_flow_graph import build_building_flow_graph
from src.agents.parse_intent_agent import ParseIntentAgent
from src.agents.generic_sql_layer import SQL_Mapper_Layer
import pandas as pd
import numpy as np
from pathlib import Path
import math
import warnings
import os

warnings.filterwarnings("ignore", category=pd.errors.DtypeWarning)

VERBOSE = False  # flip to True only when inspecting

AUG = Path("./src/data/buildings_augmented.csv")
assert AUG.exists(), "Augmented CSV not found at ./src/data/buildings_augmented.csv"
aug = pd.read_csv(AUG, low_memory=False)

# ---------- helpers ----------
def pick_col(df, prefer):
    lower = {c.lower(): c for c in df.columns}
    for k in prefer:
        if k in lower: return lower[k]
    for c in df.columns:
        if any(k in c.lower() for k in prefer):
            return c
    return df.columns[0]

addr_col = pick_col(aug, ["address", "epc_idadr", "idadr", "raw_address", "addr", "idadraggregerad"])
bid_col  = pick_col(aug, ["building_id", "uuid", "id", "objektidentitet"])
tid_col  = pick_col(aug, ["thread_id", "username", "user", "email"])

# Prefer rows that have signals in key columns so results are visible
key_cols = {
    "energy_class": "EgiEnergiklass2020_calc",
    "el_calc": "El_calc",
    "varme_calc": "EgiVarme_calc",
    "primary_heat": "HuvudsakligUppvarmning_calc",
    "basement": "EgenAntalKallarplan",
    "stairs": "EgenAntalTrapphus",
}

def rows_with_any_signal(df, n=3):
    mask = np.zeros(len(df), dtype=bool)
    for col in key_cols.values():
        if col in df.columns:
            mask |= df[col].notna()
    cand = df[mask]
    if len(cand) >= n:
        return cand.sample(n, random_state=42)
    return df.sample(n, random_state=42)

samples = rows_with_any_signal(aug, n=3).reset_index(drop=True)
np.random.seed(42)

def safe_str(x, default=""):
    try:
        s = str(x)
        if s.lower() in ("nan", "none"): return default
        return s
    except Exception:
        return default

def short(s, n=120):
    if s is None: return None
    s = str(s).replace("\n", " ").strip()
    return s if len(s) <= n else s[:n] + "…"

# ---------- build graph + helpers ----------
graph = build_building_flow_graph()
parser = ParseIntentAgent()
mapper = SQL_Mapper_Layer()

def sql_highlights_for_bid(bid):
    payload = mapper.sql.fetch_building_data(safe_str(bid))
    if not isinstance(payload, dict):
        return {}
    out = {}
    for label, col in key_cols.items():
        if col in payload:
            out[col] = payload[col]
    return out

def run_case(idx, name, prompt, metadata=None, provide_addr=False, provide_bid=False, mode_hint=None):
    row = samples.iloc[idx % len(samples)]
    addr = safe_str(row.get(addr_col), "Unknown Address")
    tid  = safe_str(row.get(tid_col), "user@example.com:session123")
    bid  = safe_str(row.get(bid_col), "UNKNOWN-BID")

    md = dict(metadata or {})
    if provide_addr:
        md["address"] = addr
    if provide_bid:
        md["building_id"] = bid

    state = {
        "thread_id": tid,
        "messages": [{"role": "user", "content": prompt}],
        "metadata": md,
        "session_state": {},
        "last_message": prompt,
        "agent_outputs": [],
    }

    classified = parser(state.copy())
    ctx = classified.get("context", {}) or {}
    intent = (ctx.get("intent") or "")
    entities = ctx.get("entities") or []
    path = "VECTOR" if intent.lower() in {"query vector database", "vector_search"} else "SQL/OTHER"
    routed_op, routed_kwargs = mapper.route(classified)

    out = graph.invoke(state)

    post_bid = out.get("metadata", {}).get("building_id")
    vector_sources = out.get("metadata", {}).get("vector_sources") or []
    fr = out.get("final_response")

    # minimal result row
    record = {
        "case": name,
        "path": path,
        "intent": intent,
        "sql_op": routed_op if path != "VECTOR" else None,
        "addr_pre": md.get("address"),
        "bid_pre": md.get("building_id"),
        "bid_post": post_bid,
        "vec_src_count": len(vector_sources) if path == "VECTOR" else 0,
        "first_source": os.path.basename(vector_sources[0]) if vector_sources else None,
        "final": short(fr, 200),
    }

    # add a couple of SQL highlights if we know the bid
    effective_bid = post_bid or md.get("building_id") or bid
    hi = sql_highlights_for_bid(effective_bid)
    # only pick 2-3 easy columns to avoid noise
    for col_key in ["EgiEnergiklass2020_calc", "El_calc", "EgiVarme_calc"]:
        record[col_key] = hi.get(col_key)

    if VERBOSE:
        print(f"\n[{name}] prompt: {prompt}")
        print(record)

    return record

# ---------- TEST CATALOG (mixed SQL + Vector) ----------
SQL_TESTS = [
    ("SQL: energy class",    lambda a: f"What is the energy class of my building at {a}?", True,  False),
    ("SQL: electricity kWh", lambda a: f"For {a}, how many kWh of electricity do we use?", True,  False),
    ("SQL: heating kWh",     lambda a: f"For {a}, what is the heating kWh (värmeanvändning)?", True,  False),
    ("SQL: primary heating", lambda a: f"At {a}, what is the primary heating?", True,  False),
    ("SQL: heated area",     lambda a: f"At {a}, how many square meters (heated area / Atemp) does it have?", True,  False),
    ("SQL: basement count",  lambda a: f"At {a}, how many basement levels are there?", True,  False),
    ("SQL: stairs count",    lambda a: f"At {a}, how many stairwells (trapphus) are there?", True,  False),
    ("SQL: heating type (no address)", lambda a: "What is my heating type?", False, False),  # will purposely ask for address
    ("SQL: energy class (with building_id)", lambda a: "What is the energy class of this building?", False, True),
]

VECTOR_TESTS = [
    ("VECTOR: insulation tips",            lambda a: "How can I improve my building’s insulation?"),
    ("VECTOR: reduce heat loss",           lambda a: "Best ways to reduce heat loss in an old apartment?"),
    ("VECTOR: CO2 reduction",              lambda a: "How can I reduce my building’s CO2 footprint over the next year?"),
    ("VECTOR: ventilation best practices", lambda a: "What are good ventilation best practices to balance air and energy?"),
    ("VECTOR: with address (still vector)",lambda a: f"I live at {a}. How can I improve the insulation?"),
]

# ---------- RUN *ALL* TESTS ----------
rows = []
idx_counter = 0
for r in range(len(samples)):
    addr = safe_str(samples.iloc[r].get(addr_col), "Unknown Address")
    # run ALL SQL tests
    for name, prompt_fn, provide_addr, provide_bid in SQL_TESTS:
        rows.append(run_case(idx_counter, name, prompt_fn(addr),
                             provide_addr=provide_addr, provide_bid=provide_bid, mode_hint="sql"))
        idx_counter += 1
    # run ALL Vector tests
    for name, prompt_fn in VECTOR_TESTS:
        rows.append(run_case(idx_counter, name, prompt_fn(addr),
                             provide_addr=False, provide_bid=False, mode_hint="vector"))
        idx_counter += 1

# ---- Show compact table ----
df = pd.DataFrame(rows, columns=[
    "case", "path", "intent", "sql_op", "addr_pre", "bid_pre", "bid_post",
    "vec_src_count", "first_source", "final",
    "EgiEnergiklass2020_calc", "El_calc", "EgiVarme_calc"
]).fillna("—")
display(df)

INFO:src.agents.parse_intent_agent:Azure ChatCompletionsClient initialized for ParseIntentAgent.
c:\Users\shada\Documents\spara-backend\src\database\sql_client.py:30: DtypeWarning: Columns (22,80) have mixed types. Specify dtype option on import or set low_memory=False.
  self._df = pd.read_csv(self._path)

Connection to Vector Database established.

INFO:src.agents.openai_agent:Initializing OpenAIResponseAgent.
INFO:src.agents.openai_agent:Prompt loaded successfully from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\openai_response_prompt.txt

Connection to Vector Database established.
✅ VectorClient initialized and connected.

INFO:src.agents.openai_agent:Azure OpenAI client initialized successfully for response agent.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "energy class"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "energy class"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "kWh of electricity"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "kWh", "electricity"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "heating kWh", "värmeanvändning"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "heating kWh", "värmeanvändning"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "primary heating"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "heating"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "heated area", "Atemp"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "heated area", "Atemp"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "basement levels"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "basement levels"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "stairwells", "trapphus"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Rindögatan 42", "stairwells", "trapphus"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["heating type"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["heating type"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Requesting address from user.

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["energy class", "building"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["energy class", "this building"], "ambiguous": true}

Routing based on ambiguity
Clarifying...
Maintaining history
Routing after history
Checking for address...
Requesting address from user.

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["building insulation"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["building insulation"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 16.56 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["old apartment", "heat loss"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["old apartment", "heat loss"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 16.65 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["building", "CO2 footprint"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["building", "CO2 footprint"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 17.63 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["ventilation", "air", "energy"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["ventilation", "air", "energy"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 15.74 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["Rindögatan 42", "insulation"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["Rindögatan 42", "insulation"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 18.44 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["energy class", "Danderydsgatan 8"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["building", "Danderydsgatan 8", "energy class"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "kWh", "electricity"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "kWh", "electricity"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "heating kWh", "värmeanvändning"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "heating kWh", "värmeanvändning"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

WARNING:src.agents.parse_intent_agent:Intent classification timed out.

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "primary heating"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "heated area", "Atemp"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "heated area", "Atemp"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "basement levels"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "basement levels"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "stairwells"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Danderydsgatan 8", "stairwells", "trapphus"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["heating type"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["heating type"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Requesting address from user.

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["building", "energy class"], "ambiguous": true}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["energy class", "this building"], "ambiguous": true}

Routing based on ambiguity
Clarifying...
Maintaining history
Routing after history
Checking for address...
Requesting address from user.

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["building insulation"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["building insulation"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 15.73 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["old apartment", "heat loss"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["heat loss", "old apartment"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 14.25 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["CO2 footprint", "building"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["CO2 footprint", "building"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 8.65 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["ventilation", "air", "energy"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["ventilation", "air", "energy"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 13.11 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["Danderydsgatan 8", "insulation"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["Danderydsgatan 8", "insulation"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 13.47 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["energy class", "Skattegränd 4C"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["energy class", "Skattegränd 4C"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "kWh", "electricity"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "kWh of electricity"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "heating kWh", "värmeanvändning"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "heating kWh", "värmeanvändning"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "primary heating"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "primary heating"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "heated area", "Atemp"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "heated area", "Atemp"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "basement levels"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "basement levels"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "stairwells", "trapphus"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["Skattegränd 4C", "stairwells", "trapphus"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Address found, proceeding.
Deciding routing based on intent

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["heating type"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["heating type"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Checking for address...
Requesting address from user.

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["energy class", "this building"], "ambiguous": true}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query generic database", "entities": ["energy class", "building"], "ambiguous": true}

Routing based on ambiguity
Clarifying...
Maintaining history
Routing after history
Checking for address...
Requesting address from user.

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["building insulation"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["building insulation"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 14.39 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["old apartment", "heat loss"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["old apartment", "heat loss"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 15.20 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["CO2 footprint", "building"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["CO2 footprint", "building"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 6.63 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["ventilation", "air", "energy"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["ventilation", "air", "energy"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 13.05 seconds.
INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["Skattegränd 4C", "insulation"], "ambiguous": false}

Entered entry_point
Running understand_context

INFO:src.agents.parse_intent_agent:LLM classification result: {"intent": "query vector database", "entities": ["Skattegränd 4C", "insulation"], "ambiguous": false}

Routing based on ambiguity
Maintaining history
Routing after history
Deciding routing based on intent

INFO:src.agents.openai_agent:Response generated in 17.42 seconds.

,case,path,intent,sql_op,addr_pre,bid_pre,bid_post,vec_src_count,first_source,final,EgiEnergiklass2020_calc,El_calc,EgiVarme_calc
0,SQL: energy class,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,energy_class = C,—,—,—
1,SQL: electricity kWh,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,el_calc = 5976,—,—,—
2,SQL: heating kWh,SQL/OTHER,query generic database,building_by_address,Skattegränd 4C,1,1,0,—,varme_calc = 5500,—,—,—
3,SQL: primary heating,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,heating_type = PumpFranluft,—,—,—
4,SQL: heated area,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,Summary of: AntalByggDek_calc: 1 AntalGamlaDek...,—,—,—
5,SQL: basement count,SQL/OTHER,query generic database,building_by_address,Skattegränd 4C,1,1,0,—,el_calc = 5976,—,—,—
6,SQL: stairs count,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,el_calc = 5976,—,—,—
7,SQL: heating type (no address),SQL/OTHER,query generic database,building_by_address,—,—,—,0,—,Can you please provide the building address?,—,—,—
8,SQL: energy class (with building_id),SQL/OTHER,query generic database,fetch_energy_rating,—,01-80-OESTEN14,01-80-OESTEN14,0,—,Can you please provide the building address?,—,—,—
9,VECTOR: insulation tips,VECTOR,query vector database,—,—,—,—,5,qa-ekr.csv,No content returned from the model.,—,—,—
10,VECTOR: reduce heat loss,VECTOR,query vector database,—,—,—,—,3,qa-ekr.csv,"You’re looking for practical, cost-effective w...",—,—,—
11,VECTOR: CO2 reduction,VECTOR,query vector database,—,—,—,—,2,qa-ekr.csv,No content returned from the model.,—,—,—
12,VECTOR: ventilation best practices,VECTOR,query vector database,—,—,—,—,3,EnergiBRFhandbokenSthlm.pdf,Good ventilation is about supplying enough fre...,—,—,—
13,VECTOR: with address (still vector),VECTOR,query vector database,—,—,—,—,5,qa-ekr.csv,No content returned from the model.,—,—,—
14,SQL: energy class,SQL/OTHER,query generic database,building_by_address,Skattegränd 4C,1,1,0,—,energy_class = C,—,—,—
15,SQL: electricity kWh,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,el_calc = 5976,—,—,—
16,SQL: heating kWh,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,varme_calc = 5500,—,—,—
17,SQL: primary heating,SQL/OTHER,unknown,noop,Skattegränd 4C,1,1,0,—,heating_type = PumpFranluft,—,—,—
18,SQL: heated area,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,Summary of: AntalByggDek_calc: 1 AntalGamlaDek...,—,—,—
19,SQL: basement count,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,el_calc = 5976,—,—,—
20,SQL: stairs count,SQL/OTHER,query generic database,building_by_address,Skattegränd 4C,1,1,0,—,el_calc = 5976,—,—,—
21,SQL: heating type (no address),SQL/OTHER,query generic database,building_by_address,—,—,—,0,—,Can you please provide the building address?,—,—,—
22,SQL: energy class (with building_id),SQL/OTHER,query generic database,fetch_energy_rating,—,01-80-NAEKTERGALEN17,01-80-NAEKTERGALEN17,0,—,Can you please provide the building address?,—,—,—
23,VECTOR: insulation tips,VECTOR,query vector database,—,—,—,—,5,qa-ekr.csv,No content returned from the model.,—,—,—
24,VECTOR: reduce heat loss,VECTOR,query vector database,—,—,—,—,3,qa-ekr.csv,Here are some of the most effective steps you ...,—,—,—
25,VECTOR: CO2 reduction,VECTOR,query vector database,—,—,—,—,2,qa-ekr.csv,No content returned from the model.,—,—,—
26,VECTOR: ventilation best practices,VECTOR,query vector database,—,—,—,—,3,EnergiBRFhandbokenSthlm.pdf,Here are some generally accepted best practice...,—,—,—
27,VECTOR: with address (still vector),VECTOR,query vector database,—,—,—,—,5,qa-ekr.csv,No content returned from the model.,—,—,—
28,SQL: energy class,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,energy_class = C,—,—,—
29,SQL: electricity kWh,SQL/OTHER,query generic database,building_by_address,Skattegränd 4C,1,1,0,—,el_calc = 5976,—,—,—
30,SQL: heating kWh,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,varme_calc = 5500,—,—,—
31,SQL: primary heating,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,heating_type = PumpFranluft,—,—,—
32,SQL: heated area,SQL/OTHER,query generic database,building_by_address,Skattegränd 4C,1,1,0,—,Summary of: AntalByggDek_calc: 1 AntalGamlaDek...,—,—,—
33,SQL: basement count,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,el_calc = 5976,—,—,—
34,SQL: stairs count,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,el_calc = 5976,—,—,—
35,SQL: heating type (no address),SQL/OTHER,query generic database,building_by_address,—,—,—,0,—,Can you please provide the building address?,—,—,—
36,SQL: energy class (with building_id),SQL/OTHER,query generic database,fetch_energy_rating,—,01-80-VERKSTADSKLUBBEN25,01-80-VERKSTADSKLUBBEN25,0,—,Can you please provide the building address?,—,—,—
37,VECTOR: insulation tips,VECTOR,query vector database,—,—,—,—,5,qa-ekr.csv,No content returned from the model.,—,—,—
38,VECTOR: reduce heat loss,VECTOR,query vector database,—,—,—,—,3,qa-ekr.csv,Here are some of the most effective steps you ...,—,—,—
39,VECTOR: CO2 reduction,VECTOR,query vector database,—,—,—,—,2,qa-ekr.csv,Här är en praktisk plan för att minska byggnad...,—,—,—
40,VECTOR: ventilation best practices,VECTOR,query vector database,—,—,—,—,3,EnergiBRFhandbokenSthlm.pdf,No content returned from the model.,—,—,—
41,VECTOR: with address (still vector),VECTOR,query vector database,—,—,—,—,4,qa-ekr.csv,No content returned from the model.,—,—,—

In [2]:
df

,case,path,intent,sql_op,addr_pre,bid_pre,bid_post,vec_src_count,first_source,final,EgiEnergiklass2020_calc,El_calc,EgiVarme_calc
0,SQL: energy class,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,energy_class = C,—,—,—
1,SQL: electricity kWh,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,el_calc = 5976,—,—,—
2,SQL: heating kWh,SQL/OTHER,query generic database,building_by_address,Skattegränd 4C,1,1,0,—,varme_calc = 5500,—,—,—
3,SQL: primary heating,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,heating_type = PumpFranluft,—,—,—
4,SQL: heated area,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,Summary of: AntalByggDek_calc: 1 AntalGamlaDek...,—,—,—
5,SQL: basement count,SQL/OTHER,query generic database,building_by_address,Skattegränd 4C,1,1,0,—,el_calc = 5976,—,—,—
6,SQL: stairs count,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,el_calc = 5976,—,—,—
7,SQL: heating type (no address),SQL/OTHER,query generic database,building_by_address,—,—,—,0,—,Can you please provide the building address?,—,—,—
8,SQL: energy class (with building_id),SQL/OTHER,query generic database,fetch_energy_rating,—,01-80-OESTEN14,01-80-OESTEN14,0,—,Can you please provide the building address?,—,—,—
9,VECTOR: insulation tips,VECTOR,query vector database,—,—,—,—,5,qa-ekr.csv,No content returned from the model.,—,—,—
10,VECTOR: reduce heat loss,VECTOR,query vector database,—,—,—,—,3,qa-ekr.csv,"You’re looking for practical, cost-effective w...",—,—,—
11,VECTOR: CO2 reduction,VECTOR,query vector database,—,—,—,—,2,qa-ekr.csv,No content returned from the model.,—,—,—
12,VECTOR: ventilation best practices,VECTOR,query vector database,—,—,—,—,3,EnergiBRFhandbokenSthlm.pdf,Good ventilation is about supplying enough fre...,—,—,—
13,VECTOR: with address (still vector),VECTOR,query vector database,—,—,—,—,5,qa-ekr.csv,No content returned from the model.,—,—,—
14,SQL: energy class,SQL/OTHER,query generic database,building_by_address,Skattegränd 4C,1,1,0,—,energy_class = C,—,—,—
15,SQL: electricity kWh,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,el_calc = 5976,—,—,—
16,SQL: heating kWh,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,varme_calc = 5500,—,—,—
17,SQL: primary heating,SQL/OTHER,unknown,noop,Skattegränd 4C,1,1,0,—,heating_type = PumpFranluft,—,—,—
18,SQL: heated area,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,Summary of: AntalByggDek_calc: 1 AntalGamlaDek...,—,—,—
19,SQL: basement count,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,el_calc = 5976,—,—,—
20,SQL: stairs count,SQL/OTHER,query generic database,building_by_address,Skattegränd 4C,1,1,0,—,el_calc = 5976,—,—,—
21,SQL: heating type (no address),SQL/OTHER,query generic database,building_by_address,—,—,—,0,—,Can you please provide the building address?,—,—,—
22,SQL: energy class (with building_id),SQL/OTHER,query generic database,fetch_energy_rating,—,01-80-NAEKTERGALEN17,01-80-NAEKTERGALEN17,0,—,Can you please provide the building address?,—,—,—
23,VECTOR: insulation tips,VECTOR,query vector database,—,—,—,—,5,qa-ekr.csv,No content returned from the model.,—,—,—
24,VECTOR: reduce heat loss,VECTOR,query vector database,—,—,—,—,3,qa-ekr.csv,Here are some of the most effective steps you ...,—,—,—
25,VECTOR: CO2 reduction,VECTOR,query vector database,—,—,—,—,2,qa-ekr.csv,No content returned from the model.,—,—,—
26,VECTOR: ventilation best practices,VECTOR,query vector database,—,—,—,—,3,EnergiBRFhandbokenSthlm.pdf,Here are some generally accepted best practice...,—,—,—
27,VECTOR: with address (still vector),VECTOR,query vector database,—,—,—,—,5,qa-ekr.csv,No content returned from the model.,—,—,—
28,SQL: energy class,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,energy_class = C,—,—,—
29,SQL: electricity kWh,SQL/OTHER,query generic database,building_by_address,Skattegränd 4C,1,1,0,—,el_calc = 5976,—,—,—
30,SQL: heating kWh,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,varme_calc = 5500,—,—,—
31,SQL: primary heating,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,heating_type = PumpFranluft,—,—,—
32,SQL: heated area,SQL/OTHER,query generic database,building_by_address,Skattegränd 4C,1,1,0,—,Summary of: AntalByggDek_calc: 1 AntalGamlaDek...,—,—,—
33,SQL: basement count,SQL/OTHER,query generic database,building_by_address,Rindögatan 42,1,1,0,—,el_calc = 5976,—,—,—
34,SQL: stairs count,SQL/OTHER,query generic database,building_by_address,Danderydsgatan 8,1,1,0,—,el_calc = 5976,—,—,—
35,SQL: heating type (no address),SQL/OTHER,query generic database,building_by_address,—,—,—,0,—,Can you please provide the building address?,—,—,—
36,SQL: energy class (with building_id),SQL/OTHER,query generic database,fetch_energy_rating,—,01-80-VERKSTADSKLUBBEN25,01-80-VERKSTADSKLUBBEN25,0,—,Can you please provide the building address?,—,—,—
37,VECTOR: insulation tips,VECTOR,query vector database,—,—,—,—,5,qa-ekr.csv,No content returned from the model.,—,—,—
38,VECTOR: reduce heat loss,VECTOR,query vector database,—,—,—,—,3,qa-ekr.csv,Here are some of the most effective steps you ...,—,—,—
39,VECTOR: CO2 reduction,VECTOR,query vector database,—,—,—,—,2,qa-ekr.csv,Här är en praktisk plan för att minska byggnad...,—,—,—
40,VECTOR: ventilation best practices,VECTOR,query vector database,—,—,—,—,3,EnergiBRFhandbokenSthlm.pdf,No content returned from the model.,—,—,—
41,VECTOR: with address (still vector),VECTOR,query vector database,—,—,—,—,4,qa-ekr.csv,No content returned from the model.,—,—,—

In [3]:
df.to_csv('results.csv', index = False)

#### test with specialised agent code.

In [ ]:
# === Compact 15-case smoke test (5 SQL, 5 Vector, 5 Specialized SQL) ===
# - Notebook-friendly, one cell
# - Suppresses noisy prints/logs during each run
# - Uses a tiny, readable result table
#
# Assumes:
#   - ./src/data/buildings_augmented.csv exists
#   - your modules import correctly
#   - SpecializedSQLLayer is wired in building_flow_graph
#   - AgentRouter returns the normalized schema:
#       { content, classification, agent_answered, intent, agents_used, vector_sources }

import os, io, sys, json, logging, warnings, re
from contextlib import contextmanager
from pathlib import Path
import numpy as np
import pandas as pd

# --- quiet noisy warnings/logs ---
warnings.filterwarnings("ignore", category=pd.errors.DtypeWarning)
logging.basicConfig(level=logging.WARNING)
for noisy in [
    "azure.core.pipeline",
    "azure.core.pipeline.policies.http_logging_policy",
    "azure.ai.inference",
    "httpx",
    "urllib3",
    "src.agents.parse_intent_agent",
    "src.agents.openai_agent",
]:
    logging.getLogger(noisy).setLevel(logging.ERROR)

@contextmanager
def suppress_output(enabled=True):
    if not enabled:
        yield
        return
    old_out, old_err = sys.stdout, sys.stderr
    try:
        sys.stdout, sys.stderr = io.StringIO(), io.StringIO()
        yield
    finally:
        sys.stdout, sys.stderr = old_out, old_err

SUPPRESS_OUTPUT = True
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

# --- data sample ---
AUG_PATH = Path("./src/data/buildings_augmented.csv")
assert AUG_PATH.exists(), "Augmented CSV not found at ./src/data/buildings_augmented.csv"
aug = pd.read_csv(AUG_PATH, low_memory=False)

def pick_col(df: pd.DataFrame, prefer):
    lower = {c.lower(): c for c in df.columns}
    for k in prefer:
        if k in lower: return lower[k]
    for c in df.columns:
        if any(k in c.lower() for k in prefer):
            return c
    return df.columns[0]

addr_col = pick_col(aug, ["address", "epc_idadr", "idadr", "raw_address", "addr", "idadraggregerad"])
bid_col  = pick_col(aug, ["building_id", "uuid", "id", "objektidentitet"])
tid_col  = pick_col(aug, ["thread_id", "username", "user", "email"])

# Prefer rows that have signals in key columns so results are visible
key_cols = {
    "EgiEnergiklass2020_calc": "EgiEnergiklass2020_calc",
    "El_calc": "El_calc",
    "EgiVarme_calc": "EgiVarme_calc",
}

def rows_with_any_signal(df, n=2):
    mask = np.zeros(len(df), dtype=bool)
    for col in key_cols.values():
        if col in df.columns:
            mask |= df[col].notna()
    cand = df[mask]
    return (cand if len(cand) >= n else df).sample(n, random_state=RANDOM_SEED)

samples = rows_with_any_signal(aug, n=2).reset_index(drop=True)

def safe_str(x, default=""):
    try:
        s = str(x)
        if s.lower() in ("nan", "none"): return default
        return s
    except Exception:
        return default

def short(s, n=160):
    if s is None: return None
    s = str(s).replace("\n", " ").strip()
    return s if len(s) <= n else s[:n] + "…"

# --- import pipeline modules ---
import src.agents.building_flow_graph as bfg
from src.pipeline.agent_router import AgentRouter
from src.agents.generic_sql_layer import SQL_Mapper_Layer
from src.agents.parse_intent_agent import ParseIntentAgent

router = AgentRouter()
parser = ParseIntentAgent()
mapper = SQL_Mapper_Layer()

# --- helper to preview a few columns from SQL for a given building_id ---
def sql_highlights_for_bid(bid):
    try:
        payload = mapper.sql.fetch_building_data(safe_str(bid))
        if not isinstance(payload, dict):
            return {}
        out = {}
        for col in key_cols.values():
            if col in payload:
                out[col] = payload[col]
        return out
    except Exception:
        return {}

# Resolve building_id from an address (best-effort; mirrors graph helper)
def resolve_bid_from_address(address: str):
    try:
        res = mapper.execute("building_by_address", {"address": address})
        if res and res.get("ok") and res.get("data"):
            data = res["data"]
            if isinstance(data, dict):
                return data.get("building_id") or data.get("ID") or data.get("id")
            if isinstance(data, list) and data and isinstance(data[0], dict):
                d0 = data[0]
                return d0.get("building_id") or d0.get("ID") or d0.get("id")
    except Exception:
        pass
    return None

# --- force-route parse_intent for specialized/vector/sql when needed ---
class _ForceIntentAgent:
    def __init__(self, forced_intent: str):
        self.forced_intent = forced_intent  # "query specific database" | "query vector database" | "query generic database"
    def __call__(self, state: dict) -> dict:
        # Preserve entities if present; add address if available
        ents = []
        md = state.get("metadata") or {}
        addr = md.get("address")
        if addr:
            ents.append(safe_str(addr))
        # simple entity extraction from prompt for address-like tokens
        m = re.search(r"\b([A-Za-zÅÄÖåäö0-9 ]+\s+\d+[A-Za-z]?)\b", state.get("last_message",""))
        if m: ents.append(m.group(1))
        state = dict(state)
        state["context"] = {"intent": self.forced_intent, "entities": ents, "ambiguous": False}
        return state

@contextmanager
def force_route(intent: str = None):
    """Temporarily replace bfg.parse_intent_agent to force a route inside the graph used by BuildingAgent."""
    if not intent:
        yield
        return
    original = bfg.parse_intent_agent
    try:
        bfg.parse_intent_agent = _ForceIntentAgent(intent)
        yield
    finally:
        bfg.parse_intent_agent = original

# --- tiny catalog of prompts ---
# SQL_TESTS = [
#     ("SQL: energy class",    lambda a: f"What is the energy class of my building at {a}?"),
#     ("SQL: electricity kWh", lambda a: f"For {a}, how many kWh of electricity do we use?"),
#     ("SQL: heating kWh",     lambda a: f"For {a}, what is the heating kWh (värmeanvändning)?"),
#     ("SQL: primary heating", lambda a: f"At {a}, what is the primary heating?"),
#     ("SQL: heated area",     lambda a: f"At {a}, how many square meters (heated area / Atemp) does it have?"),
# ]

# VECTOR_TESTS = [
#     ("VECTOR: insulation tips",            lambda a: "How can I improve my building’s insulation?"),
#     ("VECTOR: reduce heat loss",           lambda a: "Best ways to reduce heat loss in an old apartment?"),
#     ("VECTOR: CO2 reduction",              lambda a: "How can I reduce my building’s CO2 footprint over the next year?"),
#     ("VECTOR: ventilation best practices", lambda a: "What are good ventilation best practices to balance air and energy?"),
#     ("VECTOR: with address context",       lambda a: f"I live at {a}. How can I improve the insulation?"),
# ]

# Choose specialized prompts that DON'T require date ranges to avoid placeholders
SPECIALIZED_TESTS = [
    ("SPEC: HVAC system",          lambda a: f"For {a}, list the HVAC system type(s) and ventilation system."),
    ("SPEC: Energy KPIs",          lambda a: f"For {a}, return energy class and annual electricity/heat kWh if available."),
    ("SPEC: End-use breakdown",    lambda a: f"For {a}, show electricity end-use breakdown by category if available."),
    ("SPEC: Building summary",     lambda a: f"At {a}, show heated area (Atemp), number of stairwells, and basement levels."),
    ("SPEC: Metering recent rows", lambda a: f"For {a}, show a few recent metering rows (date and kWh)."),
]

# --- runner ---
def run_case(addr, prompt, force_intent=None, provide_addr=True, provide_bid=False):
    # pick thread/bid from a sample row associated with this address for realism
    row = samples.sample(1, random_state=np.random.randint(0, 10_000)).iloc[0]
    tid  = safe_str(row.get(tid_col), "user@example.com:session123")
    bid  = safe_str(row.get(bid_col), "UNKNOWN-BID")

    md = {}
    if provide_addr:
        md["address"] = addr
    if provide_bid:
        md["building_id"] = bid

    messages = [{"role": "user", "content": prompt}]
    last_message = prompt

    with suppress_output(SUPPRESS_OUTPUT), force_route(force_intent):
        out = router.route_message(messages=messages, last_message=last_message, metadata=md, thread_id=tid)

    # Extract standardized fields from AgentRouter
    intent = out.get("intent") or (force_intent or "")
    agent_answered = out.get("agent_answered", "unknown")
    agents_used = out.get("agents_used") or []
    vector_sources = out.get("vector_sources") or []
    fr = out.get("content")

    # Path summary (for quick eye-balling)
    path = (
        "SPECIALIZED" if force_intent == "query specific database"
        else "VECTOR" if agent_answered == "vector"
        else "SQL+VECTOR" if agent_answered == "sql+vector"
        else "SQL" if agent_answered == "sql"
        else agent_answered.upper()
    )

    # Try to get SQL highlights. Prefer an explicit bid (md or resolved), otherwise skip.
    effective_bid = md.get("building_id")
    if not effective_bid and md.get("address"):
        effective_bid = resolve_bid_from_address(md["address"])

    hi = sql_highlights_for_bid(effective_bid) if effective_bid else {}

    rec = {
        "case": "",
        "path": path,
        "intent": intent or "—",
        "agent_answered": agent_answered or "—",
        "agents_used": len(agents_used),
        "addr_pre": md.get("address", "—"),
        "bid_pre": md.get("building_id", "—"),
        "bid_resolved": effective_bid or "—",
        "vec_srcs": len(vector_sources),
        "final": short(fr, 200) or "—",
        "EgiEnergiklass2020_calc": hi.get("EgiEnergiklass2020_calc", "—"),
        "El_calc": hi.get("El_calc", "—"),
        "EgiVarme_calc": hi.get("EgiVarme_calc", "—"),
    }
    return rec

# --- build the 15 cases (5 SQL + 5 Vector + 5 Specialized) ---
rows = []
# pick two addresses for variety
addr_list = [safe_str(samples.iloc[i][addr_col], "Unknown Address") for i in range(len(samples))]

# 5 SQL
for i, (name, pf) in enumerate(SQL_TESTS):
    addr = addr_list[i % len(addr_list)]
    r = run_case(addr, pf(addr), force_intent=None, provide_addr=True, provide_bid=False)
    r["case"] = name
    rows.append(r)

# 5 Vector
for i, (name, pf) in enumerate(VECTOR_TESTS):
    addr = addr_list[i % len(addr_list)]
    r = run_case(addr, pf(addr), force_intent=None, provide_addr=False, provide_bid=False)
    r["case"] = name
    rows.append(r)

# 5 Specialized (force route)
for i, (name, pf) in enumerate(SPECIALIZED_TESTS):
    addr = addr_list[i % len(addr_list)]
    r = run_case(addr, pf(addr), force_intent="query specific database", provide_addr=True, provide_bid=False)
    r["case"] = name
    rows.append(r)

# --- show table ---
df = pd.DataFrame(rows, columns=[
    "case", "path", "intent", "agent_answered", "agents_used",
    "addr_pre", "bid_pre", "bid_resolved",
    "vec_srcs", "final", "EgiEnergiklass2020_calc", "El_calc", "EgiVarme_calc"
]).fillna("—")

display(df)

Connection to Vector Database established.
Connection to Vector Database established.
✅ VectorClient initialized and connected.

#### test specialized sql.

In [1]:
# === Compact 9-case smoke test (2 SQL, 2 Vector, 5 Specialized SQL) ===
# - Notebook-friendly, one cell
# - Suppresses noisy prints/logs during each run
# - Uses a tiny, readable result table
#
# Assumes:
#   - ./src/data/buildings_augmented.csv exists
#   - your modules import correctly
#   - SpecializedSQLLayer is wired in building_flow_graph
#   - BuildingAgent returns the normalized schema:
#       { content, classification, agent_answered, intent, agents_used, vector_sources }

import os, io, sys, json, logging, warnings, re
from contextlib import contextmanager
from pathlib import Path
import numpy as np
import pandas as pd

# --- quiet noisy warnings/logs ---
warnings.filterwarnings("ignore", category=pd.errors.DtypeWarning)
logging.basicConfig(level=logging.WARNING)
for noisy in [
    "azure.core.pipeline",
    "azure.core.pipeline.policies.http_logging_policy",
    "azure.ai.inference",
    "httpx",
    "urllib3",
    "src.agents.parse_intent_agent",
    "src.agents.openai_agent",
]:
    logging.getLogger(noisy).setLevel(logging.ERROR)

@contextmanager
def suppress_output(enabled=True):
    if not enabled:
        yield
        return
    old_out, old_err = sys.stdout, sys.stderr
    try:
        sys.stdout, sys.stderr = io.StringIO(), io.StringIO()
        yield
    finally:
        sys.stdout, sys.stderr = old_out, old_err

SUPPRESS_OUTPUT = True
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

# --- data sample ---
AUG_PATH = Path("./src/data/buildings_augmented.csv")
assert AUG_PATH.exists(), "Augmented CSV not found at ./src/data/buildings_augmented.csv"
aug = pd.read_csv(AUG_PATH, low_memory=False)

def pick_col(df: pd.DataFrame, prefer):
    lower = {c.lower(): c for c in df.columns}
    for k in prefer:
        if k in lower: return lower[k]
    for c in df.columns:
        if any(k in c.lower() for k in prefer):
            return c
    return df.columns[0]

addr_col = pick_col(aug, ["address", "epc_idadr", "idadr", "raw_address", "addr", "idadraggregerad"])
bid_col  = pick_col(aug, ["building_id", "uuid", "id", "objektidentitet"])
tid_col  = pick_col(aug, ["thread_id", "username", "user", "email"])

# Prefer rows that have signals in key columns so results are visible
key_cols = {
    "EgiEnergiklass2020_calc": "EgiEnergiklass2020_calc",
    "El_calc": "El_calc",
    "EgiVarme_calc": "EgiVarme_calc",
}

def rows_with_any_signal(df, n=2):
    mask = np.zeros(len(df), dtype=bool)
    for col in key_cols.values():
        if col in df.columns:
            mask |= df[col].notna()
    cand = df[mask]
    return (cand if len(cand) >= n else df).sample(n, random_state=RANDOM_SEED)

samples = rows_with_any_signal(aug, n=2).reset_index(drop=True)

def safe_str(x, default=""):
    try:
        s = str(x)
        if s.lower() in ("nan", "none"): return default
        return s
    except Exception:
        return default

def short(s, n=160):
    if s is None: return None
    s = str(s).replace("\n", " ").strip()
    return s if len(s) <= n else s[:n] + "…"

# --- import pipeline modules ---
import src.agents.building_flow_graph as bfg
from src.agents.generic_sql_layer import SQL_Mapper_Layer
from src.agents.building_agent import BuildingAgent

agent = BuildingAgent()
mapper = SQL_Mapper_Layer()

# --- helper to preview a few columns from SQL for a given building_id ---
def sql_highlights_for_bid(bid):
    try:
        payload = mapper.sql.fetch_building_data(safe_str(bid))
        if not isinstance(payload, dict):
            return {}
        out = {}
        for col in key_cols.values():
            if col in payload:
                out[col] = payload[col]
        return out
    except Exception:
        return {}

# Resolve building_id from an address (best-effort; mirrors graph helper)
def resolve_bid_from_address(address: str):
    try:
        res = mapper.execute("building_by_address", {"address": address})
        if res and res.get("ok") and res.get("data"):
            data = res["data"]
            if isinstance(data, dict):
                return data.get("building_id") or data.get("ID") or data.get("id")
            if isinstance(data, list) and data and isinstance(data[0], dict):
                d0 = data[0]
                return d0.get("building_id") or d0.get("ID") or d0.get("id")
    except Exception:
        pass
    return None

# --- force-route parse_intent for specialized/vector/sql when needed ---
class _ForceIntentAgent:
    def __init__(self, forced_intent: str):
        self.forced_intent = forced_intent  # "query specific database" | "query vector database" | "query generic database"
    def __call__(self, state: dict) -> dict:
        ents = []
        md = state.get("metadata") or {}
        addr = md.get("address")
        if addr:
            ents.append(safe_str(addr))
        m = re.search(r"\b([A-Za-zÅÄÖåäö0-9 ]+\s+\d+[A-Za-z]?)\b", state.get("last_message",""))
        if m: ents.append(m.group(1))
        state = dict(state)
        state["context"] = {"intent": self.forced_intent, "entities": ents, "ambiguous": False}
        return state

@contextmanager
def force_route(intent: str = None):
    """Temporarily replace bfg.parse_intent_agent to force a route inside the graph used by BuildingAgent."""
    if not intent:
        yield
        return
    original = bfg.parse_intent_agent
    try:
        bfg.parse_intent_agent = _ForceIntentAgent(intent)
        yield
    finally:
        bfg.parse_intent_agent = original

# --- tiny catalog of prompts ---

SQL_TESTS = [
    ("SQL: energy class",    lambda a: f"What is the energy class of my building at {a}?"),
    ("SQL: heated area",     lambda a: f"At {a}, how many square meters (heated area / Atemp) does it have?"),
]

VECTOR_TESTS = [
    ("VECTOR: insulation tips",            lambda a: "How can I improve my building’s insulation?"),
    ("VECTOR: ventilation best practices", lambda a: f"I live at {a}. What are good ventilation best practices?"),
]

SPECIALIZED_TESTS = [
    ("SPEC: HVAC system",          lambda a: f"For {a}, list the HVAC system type(s) and ventilation system."),
    ("SPEC: Energy KPIs",          lambda a: f"For {a}, return energy class and annual electricity/heat kWh if available."),
    ("SPEC: End-use breakdown",    lambda a: f"For {a}, show electricity end-use breakdown by category if available."),
    ("SPEC: Building summary",     lambda a: f"At {a}, show heated area (Atemp), number of stairwells, and basement levels."),
    ("SPEC: Metering recent rows", lambda a: f"For {a}, show a few recent metering rows (date and kWh)."),
]

# --- runner ---
def run_case(addr, prompt, force_intent=None, provide_addr=True, provide_bid=False):
    row = samples.sample(1, random_state=np.random.randint(0, 10_000)).iloc[0]
    tid  = safe_str(row.get(tid_col), "user@example.com:session123")
    bid  = safe_str(row.get(bid_col), "UNKNOWN-BID")

    md = {}
    if provide_addr:
        md["address"] = addr
    if provide_bid:
        md["building_id"] = bid

    messages = [{"role": "user", "content": prompt}]
    last_message = prompt

    with suppress_output(SUPPRESS_OUTPUT), force_route(force_intent):
        out = agent.handle_building_query(
            last_message=last_message,
            messages=messages,
            metadata=md,
            thread_id=tid,
        )

    intent = out.get("intent") or (force_intent or "")
    agent_answered = out.get("agent_answered", "unknown")
    agents_used = out.get("agents_used") or []
    vector_sources = out.get("vector_sources") or []
    fr = out.get("content")

    path = (
        "SPECIALIZED" if force_intent == "query specific database"
        else "VECTOR" if agent_answered == "vector"
        else "SQL+VECTOR" if agent_answered == "sql+vector"
        else "SQL" if agent_answered == "sql"
        else agent_answered.upper()
    )

    effective_bid = md.get("building_id")
    if not effective_bid and md.get("address"):
        effective_bid = resolve_bid_from_address(md["address"])

    hi = sql_highlights_for_bid(effective_bid) if effective_bid else {}

    rec = {
        "case": "",
        "path": path,
        "intent": intent or "—",
        "agent_answered": agent_answered or "—",
        "agents_used": len(agents_used),
        "addr_pre": md.get("address", "—"),
        "bid_pre": md.get("building_id", "—"),
        "bid_resolved": effective_bid or "—",
        "vec_srcs": len(vector_sources),
        "final": short(fr, 200) or "—",
        "EgiEnergiklass2020_calc": hi.get("EgiEnergiklass2020_calc", "—"),
        "El_calc": hi.get("El_calc", "—"),
        "EgiVarme_calc": hi.get("EgiVarme_calc", "—"),
    }
    return rec

# --- build the 9 cases (2 SQL + 2 Vector + 5 Specialized) ---
rows = []
addr_list = [safe_str(samples.iloc[i][addr_col], "Unknown Address") for i in range(len(samples))]

# 2 SQL (force intent so it's deterministic)
for i, (name, pf) in enumerate(SQL_TESTS):
    addr = addr_list[i % len(addr_list)]
    r = run_case(addr, pf(addr), force_intent="query generic database", provide_addr=True, provide_bid=False)
    r["case"] = name
    rows.append(r)

# 2 Vector (force intent; vector bypasses address gate)
for i, (name, pf) in enumerate(VECTOR_TESTS):
    addr = addr_list[i % len(addr_list)]
    r = run_case(addr, pf(addr), force_intent="query vector database", provide_addr=False, provide_bid=False)
    r["case"] = name
    rows.append(r)

# 5 Specialized (force route)
for i, (name, pf) in enumerate(SPECIALIZED_TESTS):
    addr = addr_list[i % len(addr_list)]
    r = run_case(addr, pf(addr), force_intent="query specific database", provide_addr=True, provide_bid=False)
    r["case"] = name
    rows.append(r)

# --- show table ---
df = pd.DataFrame(rows, columns=[
    "case", "path", "intent", "agent_answered", "agents_used",
    "addr_pre", "bid_pre", "bid_resolved",
    "vec_srcs", "final", "EgiEnergiklass2020_calc", "El_calc", "EgiVarme_calc"
]).fillna("—")

display(df)

Connection to Vector Database established.
Connection to Vector Database established.
✅ VectorClient initialized and connected.

ERROR:src.agents.specialized_sql_layer:Unexpected error in execute
Traceback (most recent call last):
  File "c:\Users\shada\Documents\spara-backend\src\agents\specialized_sql_layer.py", line 238, in execute
    plan = self._synthesize_sql_plan(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\shada\Documents\spara-backend\src\agents\specialized_sql_layer.py", line 350, in _synthesize_sql_plan
    content = completion.choices[0].message.content or ""
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'choices'
ERROR:src.agents.specialized_sql_layer:Unexpected error in execute
Traceback (most recent call last):
  File "c:\Users\shada\Documents\spara-backend\src\agents\specialized_sql_layer.py", line 238, in execute
    plan = self._synthesize_sql_plan(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\shada\Documents\spara-backend\src\agents\specialized_sql_layer.py", line 350, in _synthesize_sql_plan
    content = completion.choices[0].message.content or ""
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'choices'
ERROR:src.agents.specialized_sql_layer:Unexpected error in execute
Traceback (most recent call last):
  File "c:\Users\shada\Documents\spara-backend\src\agents\specialized_sql_layer.py", line 238, in execute
    plan = self._synthesize_sql_plan(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\shada\Documents\spara-backend\src\agents\specialized_sql_layer.py", line 350, in _synthesize_sql_plan
    content = completion.choices[0].message.content or ""
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'choices'

KeyboardInterrupt:

In [2]:
df = pd.DataFrame(rows, columns=[
    "case", "path", "intent", "agent_answered", "agents_used",
    "addr_pre", "bid_pre", "bid_resolved",
    "vec_srcs", "final", "EgiEnergiklass2020_calc", "El_calc", "EgiVarme_calc"
]).fillna("—")

In [3]:
df

,case,path,intent,agent_answered,agents_used,addr_pre,bid_pre,bid_resolved,vec_srcs,final,EgiEnergiklass2020_calc,El_calc,EgiVarme_calc
0,SQL: energy class,SQL,query generic database,sql,1,Rindögatan 42,1,1,0,energy_class = C,—,—,—
1,SQL: heated area,SQL,query generic database,sql,1,Danderydsgatan 8,1,1,0,Summary of: AntalByggDek_calc: 1 AntalGamlaDek...,—,—,—
2,VECTOR: insulation tips,VECTOR,query vector database,vector,1,—,—,—,5,No content returned from the model.,—,—,—
3,VECTOR: ventilation best practices,VECTOR,query vector database,vector,1,—,—,—,2,No content returned from the model.,—,—,—
4,SPEC: HVAC system,SPECIALIZED,query specific database,unknown,0,Rindögatan 42,—,—,0,Specialized SQL error = unexpected_error: 'Non...,—,—,—
5,SPEC: Energy KPIs,SPECIALIZED,query specific database,unknown,0,Danderydsgatan 8,—,—,0,Specialized SQL error = unexpected_error: 'Non...,—,—,—
6,SPEC: End-use breakdown,SPECIALIZED,query specific database,unknown,0,Rindögatan 42,—,—,0,Specialized SQL error = unexpected_error: 'Non...,—,—,—

#### test hammarby data works or not

In [1]:
# --- run in a notebook or Python REPL from your repo root ---

import json
from src.agents.specialized_sql_layer_fixed import SpecializedSQLLayer

# Initialize the layer — avoid DB queries for now
layer = SpecializedSQLLayer(execute_query=False)  # Set to True when ready to hit DB

# --- Diagnostics ---
print("Client:", "Azure" if layer._conf.is_azure else "OpenAI")
print("Model/Deployment:", layer._conf.model_or_deployment)
print("API Version:", layer._conf.api_version or "n/a")
print("Schema JSON path:", layer.schema_json)
print("System prompt preview:\n", layer._system_prompt[:500], "...\n")

# --- Optional: Override timeout globally for completions (if not already passed) ---
orig_create = layer._client.chat.completions.create
def create_with_timeout(**kwargs):
    kwargs.setdefault("timeout", 30.0)  # Fail fast after 30s
    return orig_create(**kwargs)
layer._client.chat.completions.create = create_with_timeout

# --- Simulate a router call ---
state = {
    "last_message": "Show building name and latest energy KPIs for this building.",
    "context": {"entities": []},
    "metadata": {"building_id": "1", "address": None},
}

# --- Route + Execute ---
op, kwargs = layer.route(state)
print("Operation:", op)
print("Input to model:", kwargs)

result = layer.execute(op, kwargs)

# --- Result ---
print("\n--- Response ---")
print(json.dumps(result, indent=2, ensure_ascii=False))

INFO:src.agents.parse_intent_agent:Azure ChatCompletionsClient initialized for ParseIntentAgent.
c:\Users\shada\Documents\spara-backend\src\database\sql_client.py:30: DtypeWarning: Columns (22,80) have mixed types. Specify dtype option on import or set low_memory=False.
  self._df = pd.read_csv(self._path)

Connection to Vector Database established.

INFO:src.agents.openai_agent:Initializing OpenAIResponseAgent.
INFO:src.agents.openai_agent:Prompt loaded successfully from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\openai_response_prompt.txt

Connection to Vector Database established.
✅ VectorClient initialized and connected.

INFO:src.agents.openai_agent:Azure OpenAI client initialized successfully for response agent.

Client: Azure
Model/Deployment: gpt-4o-mini
API Version: 2023-05-15
Schema JSON path: (not configured)
System prompt preview:
 You are a careful assistant that reads a building-related request, uses provided metadata (like building_id), and returns a concise answer. If the request needs database access, describe exactly what SQL you would run, but do not fabricate results. ...

Operation: chat
Input to model: {'messages': [{'role': 'system', 'content': 'You are a careful assistant that reads a building-related request, uses provided metadata (like building_id), and returns a concise answer. If the request needs database access, describe exactly what SQL you would run, but do not fabricate results.'}, {'role': 'system', 'content': "Context: building_id='1', address=None"}, {'role': 'user', 'content': 'Show building name and latest energy KPIs for this building.'}], 'temperature': 0.1, 'top_p': 0.9, 'max_tokens': 600}

--- Response ---
{
  "ok": true,
  "message": "To retrieve the building name and the latest energy KPIs for building_id '1', I would run the following SQL query:\n\n```sql\nSELECT building_name, energy_kpi\nFROM buildings\nJOIN energy_kpis ON buildings.id = energy_kpis.building_id\nWHERE buildings.id = '1'\nORDER BY energy_kpis.date DESC\nLIMIT 1;\n```\n\nThis query joins the buildings table with the energy_kpis table, filters for the specified building_id, and orders the results by date to get the latest KPI."
}

In [4]:
result['message']

"To retrieve the building name and the latest energy KPIs for building_id '1', I would run the following SQL query:\n\n```sql\nSELECT building_name, energy_kpi\nFROM buildings\nJOIN energy_kpis ON buildings.id = energy_kpis.building_id\nWHERE buildings.id = '1'\nORDER BY energy_kpis.date DESC\nLIMIT 1;\n```\n\nThis query joins the buildings table with the energy_kpis table, filters for the specified building_id, and orders the results by date to get the latest KPI."

In [10]:
# --- run in a notebook or Python REPL from your repo root ---

import json
from src.agents.specialized_sql_layer_fixed import SpecializedSQLLayer

# NOTE: execute_query arg is ignored by the new layer (it always executes)
layer = SpecializedSQLLayer(execute_query=False)

# --- Diagnostics ---
print("Client:", "Azure" if layer._conf.is_azure else "OpenAI")
print("Model/Deployment:", layer._conf.model_or_deployment)
print("API Version:", layer._conf.api_version or "n/a")
print("Schema JSON path:", layer.schema_json)
print("System prompt preview:\n", layer._system_prompt[:300], "...\n")
print("Schema preview:\n", layer._schema_str[:600], "...\n")

# --- Optional: add a default timeout to model calls (remove if your SDK doesn't accept 'timeout') ---
orig_create = layer._client.chat.completions.create
def create_with_timeout(**kwargs):
    kwargs.setdefault("timeout", 30.0)
    return orig_create(**kwargs)
layer._client.chat.completions.create = create_with_timeout

# --- Simulate a router call ---
state = {
    "last_message": "Which buildings have lowest energy usage for August 2022?. give me the building name and energy usage for month of August",
    "context": {"entities": []},
    "metadata": {"building_id": "1", "address": None},
}

# --- Route + Execute ---
op, kwargs = layer.route(state)
print("Operation:", op)
print("Input to model (preview):", {k: v for k, v in kwargs.items()})

result = layer.execute(op, kwargs)

# --- Result ---
print("\n--- Response ---")
print(json.dumps(result, indent=2, ensure_ascii=False , default=str))

# --- Friendly view ---
if result.get("ok") and isinstance(result.get("data"), list):
    rows = result["data"]
    print(f"\nRows returned: {len(rows)} (showing up to 5)")
    for i, r in enumerate(rows[:5], 1):
        print(f"{i:>2}.", r)
else:
    print("\nMessage:", result.get("message"))
print("\nSQL used:\n", result.get("sql"))

Client: Azure
Model/Deployment: gpt-4o-mini
API Version: 2023-05-15
Schema JSON path: src/config/schema.json
System prompt preview:
 You are the SQL brain for the Hammarby energy/building dataset.

GOAL
- Given a natural-language question and optional metadata (like building_id), produce exactly ONE SQL statement that answers or performs the requested operation.

DIALECT & NAMING
- Use **PostgreSQL** syntax.
- Always schema-quali ...

Schema preview:
 dbo.buildings(building_id integer PK, numberOfApartments integer, numberOfTenants integer, netAreaResidential integer, buildingName text, netAreaNonResidential integer, netAreaHeated integer, declaredEnergyClass text, EnergyClassKwhM2 integer)
dbo.electricity_enduses(id integer PK, electricity_used_for_property boolean, electricity_used_for_property_heating boolean, electricity_used_for_taphotwater boolean, electricity_used_for_apartments boolean, electricity_used_for_tenants boolean, building_id integer, electricity_used_for_charging_station boolean)
dbo.hvac_systems(id integer PK, building_i ...

Operation: answer_query
Input to model (preview): {'question': 'Which buildings have lowest energy usage for August 2022?. give me the building name and energy usage for month of August', 'building_id': '1', 'address': None}

--- Response ---
{
  "ok": true,
  "data": [
    {
      "buildingName": "Brf Sundet2",
      "electricity_use_property": 0.0
    },
    {
      "buildingName": "The Village",
      "electricity_use_property": 0.0
    },
    {
      "buildingName": "Wrong building",
      "electricity_use_property": 0.0
    },
    {
      "buildingName": "Brf Hammarby Kaj",
      "electricity_use_property": 0.0
    },
    {
      "buildingName": "Brf Strandkanten",
      "electricity_use_property": 4608.57
    },
    {
      "buildingName": "Brf Sjöstadspiren",
      "electricity_use_property": 10816.01
    },
    {
      "buildingName": "Brf Sjöportalen",
      "electricity_use_property": 10850.0
    },
    {
      "buildingName": "Brf Sjöstaden 2",
      "electricity_use_property": 13110.8
    },
    {
      "buildingName": "Arams test building",
      "electricity_use_property": 13110.82
    },
    {
      "buildingName": "Brf Holmen",
      "electricity_use_property": 19945.92
    },
    {
      "buildingName": "Brf Sjöstadsesplanaden 1 ",
      "electricity_use_property": 47427.76
    }
  ],
  "sql": "SELECT b.\"buildingName\", m.electricity_use_property\nFROM dbo.buildings AS b\nJOIN dbo.meterings AS m\n  ON b.building_id = m.building_id\nWHERE m.year = 2022 AND m.month = 'August'\nORDER BY m.electricity_use_property ASC\nLIMIT 100;"
}

Rows returned: 11 (showing up to 5)
 1. {'buildingName': 'Brf Sundet2', 'electricity_use_property': 0.0}
 2. {'buildingName': 'The Village', 'electricity_use_property': 0.0}
 3. {'buildingName': 'Wrong building', 'electricity_use_property': 0.0}
 4. {'buildingName': 'Brf Hammarby Kaj', 'electricity_use_property': 0.0}
 5. {'buildingName': 'Brf Strandkanten', 'electricity_use_property': 4608.57}

SQL used:
 SELECT b."buildingName", m.electricity_use_property
FROM dbo.buildings AS b
JOIN dbo.meterings AS m
  ON b.building_id = m.building_id
WHERE m.year = 2022 AND m.month = 'August'
ORDER BY m.electricity_use_property ASC
LIMIT 100;

c:\Users\shada\Documents\spara-backend\src\database\hammarby_data.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn, params=params)

In [11]:
result['sql']

'SELECT b."buildingName", m.electricity_use_property\nFROM dbo.buildings AS b\nJOIN dbo.meterings AS m\n  ON b.building_id = m.building_id\nWHERE m.year = 2022 AND m.month = \'August\'\nORDER BY m.electricity_use_property ASC\nLIMIT 100;'

In [13]:
result

{'ok': True,
 'data': [{'buildingName': 'Brf Sundet2', 'electricity_use_property': 0.0},
  {'buildingName': 'The Village', 'electricity_use_property': 0.0},
  {'buildingName': 'Wrong building', 'electricity_use_property': 0.0},
  {'buildingName': 'Brf Hammarby Kaj', 'electricity_use_property': 0.0},
  {'buildingName': 'Brf Strandkanten', 'electricity_use_property': 4608.57},
  {'buildingName': 'Brf Sjöstadspiren', 'electricity_use_property': 10816.01},
  {'buildingName': 'Brf Sjöportalen', 'electricity_use_property': 10850.0},
  {'buildingName': 'Brf Sjöstaden 2', 'electricity_use_property': 13110.8},
  {'buildingName': 'Arams test building',
   'electricity_use_property': 13110.82},
  {'buildingName': 'Brf Holmen', 'electricity_use_property': 19945.92},
  {'buildingName': 'Brf Sjöstadsesplanaden 1 ',
   'electricity_use_property': 47427.76}],
 'sql': 'SELECT b."buildingName", m.electricity_use_property\nFROM dbo.buildings AS b\nJOIN dbo.meterings AS m\n  ON b.building_id = m.building_id\nWHERE m.year = 2022 AND m.month = \'August\'\nORDER BY m.electricity_use_property ASC\nLIMIT 100;'}

#### building flow each node test

In [1]:
state = {
    "thread_id": "ebpuetk.vtdyrjiz@kth.se:liuwbbwqcf9w834svweyyw30cå45vm",

    # Conversation payload
    "messages": [
        {
            "role": "user",
            "content": "How can I improve the energy class of a building ?"
        }
    ],
    "last_message": "How can I improve the energy class of a building ?",

    # Persisted/contextual info carried alongside the session
    "metadata": {
        "address": "Karin Larssons Väg 79"
    }
}

In [2]:
from src.agents.building_flow_graph import *

INFO:src.agents.parse_intent_agent:Azure ChatCompletionsClient initialized for ParseIntentAgent.

Connection to Vector Database established.

INFO:src.agents.openai_agent:Initializing OpenAIResponseAgent.
INFO:src.agents.openai_agent:Prompt loaded successfully from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\openai_response_prompt.txt

Connection to Vector Database established.
✅ VectorClient initialized and connected.

INFO:src.agents.openai_agent:Azure OpenAI client initialized successfully for response agent.
c:\Users\shada\Documents\spara-backend\src\database\hammarby_data.py:95: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('''select address from dbo.buildingaddress ; ''', conn,)['address'].to_list()

In [3]:
VALUE = understand_context_node(state)

INFO:src.agents.parse_intent_agent:LLM classification result: {"parsed_intent":"SQL database ; vector database","address":null,"ambigious":false}

In [4]:
VALUE

{'thread_id': 'ebpuetk.vtdyrjiz@kth.se:liuwbbwqcf9w834svweyyw30cå45vm',
 'messages': [{'role': 'user',
   'content': 'How can I improve the energy class of a building ?'}],
 'last_message': 'How can I improve the energy class of a building ?',
 'metadata': {'address': 'Karin Larssons Väg 79'},
 'context': {'parsed_intent': 'SQL database ; vector database',
  'address': None,
  'ambigious': False,
  'intent_list': ['SQL database', 'vector database']}}

In [5]:
route_message = route_after_ambiguity(VALUE)

In [6]:
route_message

'maintain_history'

In [7]:
output = maintain_history_node(VALUE)

In [8]:
result = decision_router(VALUE)

In [9]:
result

['generic_sql_agent', 'vector_db_agent']

In [10]:
result = generic_sql_agent_node(VALUE)

In [11]:
output = vector_db_agent_node(VALUE)

In [12]:
result

{'done_generic_sql': True,
 'agent_data_generic': [{'byggnadsid': '01-80-GASKEN2-1',
   'epc_fjarrvarmenetworkname_calc': None,
   'epc_egirefvarde1bbr29_calc': 90,
   'epc_egenprojventflode_calc': None,
   'epc_egifgeo_calc': 1.0,
   'epc_egiprimarenergital2020_calc': 68,
   'epc_egiprimarenergianvandning2020_calc': 10876,
   'epc_egisumma2_calc': None,
   'epc_egienergianvandning_eindex_calc': 6042.0,
   'epc_energiindex_calc': 1.014055,
   'epc_egispecifikenergianvandning_calc': 38,
   'epc_egispecifikenergianvandning_eindex_calc': 38.0,
   'epc_egienergianvandning_calc': 6042,
   'epc_egitappvarmvattenperm2_calc': 8.050314465408805,
   'epc_egivarme_calc': 5500,
   'epc_egiuppvarmning_calc': 4220,
   'epc_egitappvarmvatten_calc': 1280,
   'epc_el_calc': 5976,
   'epc_elovr_calc': 476,
   'epc_versionorder_calc': 0,
   '01a_fnr': '010528602',
   '50a_deso': '0180C1240',
   '50a_husnridmerge': '010528602-1',
   '50a_uuid': '8fd266c0-56dd-489b-8e08-a0c08a93ec86',
   'epc_egenantalbolgh': None,
   'epc_egenantalkallarplan': None,
   'epc_egenantalplan': None,
   'epc_egenantaltrapphus': None,
   'epc_egenatemp': 159,
   'epc_egenatempbad': None,
   'epc_egenatempbostad': 100,
   'epc_egenatempbutik': None,
   'epc_egenatemphotell': None,
   'epc_egenatempkontor': None,
   'epc_egenatempkopcentrum': None,
   'epc_egenatemplivsmedel': None,
   'epc_egenatempovrig': None,
   'epc_egenatempovrigavad': None,
   'epc_egenatemprestaurang': None,
   'epc_egenatempskolor': None,
   'epc_egenatempsumma': 100,
   'epc_egenatempteater': None,
   'epc_egenatempvard': None,
   'epc_egenatempvarddag': None,
   'epc_egenavarmgarage': None,
   'epc_egenboa': None,
   'epc_egenbra': None,
   'epc_egenbta': None,
   'epc_egenbyggnadskat': 'En- och tvåbostadshus',
   'epc_egenbyggnadstyp': 'Friliggande',
   'epc_egengruppatemp': 'Mätt',
   'epc_egeninsteleffektstorre': 'Ja',
   'epc_egenkomplexitet': 'Enkel',
   'epc_egenloa': None,
   'epc_egennybyggar': 2016,
   'epc_egenprojventflode': None,
   'epc_egensarskiltvardefull': 'Nej',
   'epc_egenskyddadbyggnad': 'Nej',
   'epc_egenskyddadellervardefull': None,
   'epc_egensmalagenheter': 'Nej',
   'epc_egentypkod': '220',
   'epc_egentypkod_typ': '220 - Småhusenhet, bebyggd',
   'epc_egiberaknatvarde': 'Ja',
   'epc_egiberelproduktion': None,
   'epc_egiberengproduktion': None,
   'epc_egieldirekt': 0,
   'epc_egieldirektuppv': 0,
   'epc_egielluft': 0,
   'epc_egielluftuppv': 0,
   'epc_egielvatten': 0,
   'epc_egielvattenuppv': 0,
   'epc_egielvv': 1280,
   'epc_egienergianvandning': None,
   'epc_egienergiklass': 'B',
   'epc_egienergiprestanda': 38,
   'epc_egifastighet': 476,
   'epc_egifjarrkyla': 0,
   'epc_egifjarrvarme': 0,
   'epc_egifjarrvarmeuppv': 0,
   'epc_egifjarrvarmevv': 0,
   'epc_egiflis': 0,
   'epc_egiflisuppv': 0,
   'epc_egiflisvv': 0,
   'epc_egiforstaarmanad': None,
   'epc_egigas': 0,
   'epc_egigasuppv': 0,
   'epc_egigasvv': 0,
   'epc_egigruppeldirekt': None,
   'epc_egigruppelluft': None,
   'epc_egigruppelvatten': None,
   'epc_egigruppfastighet': None,
   'epc_egigruppfjarrkyla': None,
   'epc_egigruppfjarrvarme': None,
   'epc_egigruppflis': None,
   'epc_egigruppgas': None,
   'epc_egigrupphushall': None,
   'epc_egigruppkomfort': None,
   'epc_egigruppolja': None,
   'epc_egigruppovrbiobransle': None,
   'epc_egigrupppumpfranluft': None,
   'epc_egigrupppumpluftluft': None,
   'epc_egigrupppumpluftvatten': None,
   'epc_egigrupppumpmark': None,
   'epc_egigruppsolcell': 'Nej',
   'epc_egigruppsolvarme': 'Nej',
   'epc_egigruppved': None,
   'epc_egigruppverksamhet': None,
   'epc_egigruppvvbered': None,
   'epc_egihushall': 0,
   'epc_egikomfort': 0,
   'epc_egikomforttillagg': 0,
   'epc_eginormkorrei': None,
   'epc_eginormkorrgd': None,
   'epc_egiolja': 0,
   'epc_egioljauppv': 0,
   'epc_egioljavv': 0,
   'epc_egiovrbiobransle': 0,
   'epc_egiovrbiobransleuppv': 0,
   'epc_egiovrbiobranslevv': 0,
   'epc_egiprimarenergianvandning': None,
   'epc_egiprimarenergital': None,
   'epc_egipumpfranluft': 5500,
   'epc_egipumpfranluftuppv': 4220,
   'epc_egipumpluftluft': 0,
   'epc_egipumpluftluftuppv': 0,
   'epc_egipumpluftvatten': 0,
   'epc_egipumpluftvattenuppv': 0,
   'epc_egipumpmark': 0,
   'epc_egipumpmarkuppv': 0,
   'epc_egirefvarde1': 55,
   'epc_egirefvarde2max': 106,
   'epc_egirefvarde2min': 86,
   'epc_egirefvarde3': None,
   'epc_egisistaarmanad': None,
   'epc_egisolcell': None,
   'epc_egisolvarme': None,
   'epc_egistationei': None,
   'epc_egistationgd': None,
   'epc_egisumma1': 5500,
   'epc_egisumma2': 5976,
   'epc_egisumma3': 5976,
   'epc_egisumma4': 5976,
   'epc_egivaravel': 38,
   'epc_egived': 0,
   'epc_egiveduppv': 0,
   'epc_egivedvv': 0,
   'epc_egiverksamhet': 0,
   'epc_egiversion': '2015',
   'epc_egivvbered': 1280,
   'epc_formularid': '752340',
   'epc_godkand': '2016-12-29',
   'epc_id': '01-80-GASKEN2',
   'epc_idadr': 'Karin Larssons Väg 79',
   'epc_idegnahem': '1',
   'epc_idfastbet': 'Gasken 2',
   'epc_idhusnr': '1',
   'epc_idhuvudadress': 'Ja',
   'epc_idkommun': 'Stockholm',
   'epc_idkommunkod': '80',
   'epc_idlan': 'Stockholms län',
   'epc_idlankod': '01',
   'epc_idpostnr': '12863',
   'epc_idpostort': 'Sköndal',
   'epc_idrapportlm': None,
   'epc_luftgruppfinnsluft': 'Nej',
   'epc_ventdelvisprocent': None,
   'epc_ventgruppgodkand': None,
   'epc_ventgruppkrav': 'Nej',
   'epc_venttypf': 'Nej',
   'epc_venttypfmed': 'Ja',
   'epc_venttypft': 'Nej',
   'epc_venttypftx': 'Nej',
   'epc_venttypsjalvdrag': 'Nej',
   'epc_version': '2.4',
   'epc_egiprimarenergital2019': None,
   'epc_egiprimarenergital2020': None,
   'epc_egispecifikenergianvandning': 38,
   'epc_expertgrupphosuppdragsgivare': None,
   'epc_inspluftangenomeffekt': None,
   'epc_inspluftangenomeffektyta': None,
   'epc_inspluftbedomningnomeffekt': None,
   'epc_inspluftgruppinspskyldighet': None,
   'epc_inspluftgrupplamplig': None,
   'epc_inspluftgruppnomstorre': None,
   'epc_inspluftlampligkommentar': '',
   'epc_inspluftundavtalegipres': None,
   'epc_inspluftundfunkoverreglbost': None,
   'epc_inspluftundsysfaststyr': None,
   'epc_inspuppvangenomeffekt': None,
   'epc_inspuppvangenomeffektyta': None,
   'epc_inspuppvbedomningnomeffekt': None,
   'epc_inspuppvgruppinspskyldighet': None,
   'epc_inspuppvgrupplamplig': None,
   'epc_inspuppvgruppnomstorre': None,
   'epc_inspuppvlampligkommentar': '',
   'epc_inspuppvundavtalegipres': None,
   'epc_inspuppvundfunkoverreglbost': None,
   'epc_inspuppvundsysfaststyr': None,
   'epc_sourceversion_calc': '19',
   'epc_ventgrupputananm': None,
   'epc_radgrupphaltmatt': 'Nej',
   'epc_radtypmatning': None,
   'epc_radmatdatum': None,
   'epc_radhalt': None,
   'epc_antalbyggdek_calc': 1,
   'epc_antalgamladek_calc': 1,
   'epc_localversion_calc': 1,
   'epc_egienergiklass2020_calc': 'C',
   'epc_huvudsakliguppvarmning_calc': 'PumpFranluft',
   'epc_egienergiklass2016_calc': 'B'}],
 'agent_outputs_generic': ['generic_sql: ok']}

In [13]:
output

{'done_vector': True,
 'agent_outputs_vector': ['Vector hits:\n\ufeffquestion;answer;date;category: Hur kan jag förbättra vår bostads energiklass?;För att förbättra byggnadens energiklass kan du se över om det är möjligt att förbättra byggnadens isolering\nNone: installera energieffektiva fönster och dörrar,uppgradera eller optimera värmesystemet,installera energieffektiva hushållsapparater och belysning,använda smarta hem-system för att styra och optimera energianvändningen,installera förnybara energikällor (t.ex. solceller),se över ventilationssystemet osv. Ett tips är att kolla byggnadens senaste energideklaration. Där får du relevanta förbättringsförslag från en certifierad energiexpert som hjälper dig att sänka energiförbrukningen för din byggnad.  ;2024-03-25;Energideklaration BRF  EnERgIEFFEKTI v12\n1 tRe Steg mot e FFektiva Re ene Rgianvän Dning\nJämför med andra\nNär man vet hur mycket energi som fastig-\nheten använder årligen är det intressant \natt jämföra energianvändningen med an -\ndra fastigheter för att se om den är ovan -\nligt hög eller låg (se tabell 2). SCB sam -\nmanställer statistik som publiceras årligen \ni en rapport som kan köpas från SCB eller \nhämtas via hemsidan www.scb.se. \nE-nyckeln (www.enyckeln.se) är en \nhemsida där fastighetsägare rapporterar \nsin egen energianvändning och samtidigt \nfår tillgång till ett stort jämförelsematerial \n(se också tabell 2). E-nyckeln kan ge en \nuppfattning om hur byggnaden ligger till \ni jämförelse med andra. \nDen nya lagen om energideklarering \ninnebär att alla ägare till flerbostadshus \nsenast vid utgången av år 2008 måste be -\nskriva sin energianvändning vilket kom -\nmer att underlätta en jämförelse med re -\nferensvärden.\nOm den egna energianvändningen \navviker markant från de genomsnittliga •\t\nAntal\tlägenheter\nEtt bra tillfälle att energieffektivisera är när fastigheten renoveras. \nExempel på hur energianvändningen i ett \nmindre flerbostadshus kan vara fördelad1 . brf energieffektiv\n22\n2  effektivisera energianvändningen\nvilket medför att takutsprånget minskar, \nfönstren måste flyttas ut eller få bredare \nfönsterbleck och att fasaden hänger ut \növer\tgrunden.\tOm\thuset\ttilläggsisoler\nas\t\nmed\tcirka\t8\tcm\träcker\tdet\tvanligtvis\tmed\t\natt\tåtgärda\tfönstersmygarna.\tI\täldre\thus\t\nmed kulturhistor\niskt värde är det kanske \ninte\tlämpligt\tatt\ttilläggsisoler\na.\tI\tförsta\t\nhand kan man åtgärda gav elfasaderna ef-\ntersom lägenheterna på gaveln ofta är som \nkallast samtidigt som det finns få fönster \ndär.\t Til\nläggsisoleringen\t bör\t utföras\t av\t\nfackmän med g\noda referenser eftersom ett \nfelaktigt utförande kan medföra fuktpro-\nblem.\nFönster\nFönstren släpper in ljus och värme, men \nnär det är kallt ute släpper de även ut \nmycket värme från huset. Med rätt föns-\nter kan man hålla nere kostnaderna för \nenergi samtidigt som man får ett bättre \ninomhusklimat. Hur bra ett fönster isole-\nrar\tanges\tmed\tett\tU-värde\n,\tju\tlägre\tvärde 1 tre steg mot effektivare energianvändning\n0 \n50 \n100 \n150 \n200 \n250 \n300 \n350 \n1980 1985 1990 1995 2000 2005 2010 2015 \nkWh/m2\n60 \nkWh/m2\n230 \nkWh/m2\n Mer än 30 års konsekvent energieffektivisering i BRF Bellman\n6  BRF  EnERgIEFFEKTI v\n•\tInjustering av \nvärme system. \n•\tIsolerat fönster-\nkarm/båge. \n•\tIsolerat rör  \ni källaren.\n•\tBytt pum-\npar och injusterat \nvärmesystemet enligt \nlågflödesmetoden.\n•\tInstallerat \ntermostatventiler. \n•\tReglering av \nfrånluftsfläktar.  \n•\tLågenergilampor.\nByte av \nalla vatten-\nkranar i \nlägen heterna.\nInstallation av \ndatoriserat styr- och \növervakningssystem \nför värme och varm-\nvattenproduktion.\nRenoverat tvätt-\nstugor, tvättmaski-\nnerna har automatik \nför att anpassa \nvattenmängden till \nmängden tvättgods.\nnytt data-\nsystem för styr-\nning av värme \noch varmvatten-\nproduktion.\nRensning, \nombyggnad \noch injus-\ntering av \nventilations-\nsystemet.\n•\tny ytter-\nbelysning med \nhögtrycks-\nnatriumlampor.\n•\tBytt garage-\nportar och \nmonterat \nmellanväggar i']}

#### building flow code

In [1]:
from src.agents.building_flow_graph import build_building_flow_graph

INFO:src.agents.parse_intent_agent:Azure ChatCompletionsClient initialized for ParseIntentAgent.

dbo.buildingaddress(building_id integer PK, building_name text, address text PK)
dbo.buildings(building_id integer PK, numberOfApartments integer, numberOfTenullts integer, netAreaResidential integer, buildingName text, netAreaNonResidential integer, netAreaHeated integer, declaredEnergyClass text, EnergyClassKwhM2 integer)
dbo.electricity_enduses(id integer PK, electricity_used_for_property boolean, electricity_used_for_property_heating boolean, electricity_used_for_taphotwater boolean, electricity_used_for_apartments boolean, electricity_used_for_tenullts boolean, building_id integer, electricity_used_for_charging_station boolean)
dbo.hvac_systems(id integer PK, building_id integer, district_heating boolean, ground_source_heatpump_with_exhaust_air_recovery boolean, ground_source_heatpump_without_exahaust_air_recovery boolean, exhaust_air_recovery boolean, solar_thermal_panels boolean, district_cooling_production boolean, boiler_reserve boolean, cooling_production boolean, hvac_systems_installed_in_tenullts boolean)
dbo.meterings(uuid uuid PK, building_id integer, year integer, month text, electricity_use_property double precision, electricity_use_charging_station integer, electricity_use_lanudry_room double precision, electricity_use_water_heating_and_tap_hot_water double precision, electricity_use_apartments double precision, electricity_produced_pv double precision, electricity_excess_pv double precision, hot_water_produced_solar_thermal integer, electricity_purchased double precision, district_heating_purchased integer, district_cooling_purchased integer, electricity_sold integer)
dbo.normalization_values(id integer PK, building_id integer, indoor_temperature_sep_may double precision, hotwater_consumption_m3 integer, cold_water_consumption_m3 integer, scop_seasonal_coefficient_of_performance double precision, hotwater_source_for_towel_heater boolean, floor_heating_in_number_of_apartments integer)
dbo.results(building_id integer PK, year integer PK, deduction_household_heat_electricity double precision, deduction_household_heat_district_heating double precision, normal_household_eui double precision, tap_hotwater_m3 double precision, heating_constant_kwh_m3 double precision, energy_for_thw double precision, deduction_thw_district_heating double precision, total_property_energy_electricity double precision, deduction_pv double precision, deduction_electricity_indoor_temp double precision, energy_performance double precision, created_at timestamp, updated_at timestamp, deduction_thw_electricity double precision, primary_energy_district_cooling double precision, primary_energy_district_heating double precision, primary_energy_electricity double precision, total_deduction double precision, household_electricity_for_building_heat double precision, difference_household_heat_eui double precision, deduction_district_heating_indoor_temp double precision, deducted_property_district_heating_use double precision)
dbo.users(user_id integer PK, email text, password text, building_id integer)
[init] SpecializedSQLLayer initialized ✓
Connection to Vector Database established.
Connection to Vector Database established.
✅ VectorClient initialized and connected.
[init] VectorClient initialized ✓

INFO:src.agents.openai_agent:Initializing OpenAIResponseAgent.
INFO:src.agents.openai_agent:Prompt loaded successfully from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\openai_response_prompt.txt
INFO:src.agents.openai_agent:Azure OpenAI client initialized successfully for response agent.

[init] OpenAIResponseAgent initialized ✓
[init] Address list loaded: 42 entries

c:\Users\shada\Documents\spara-backend\src\database\hammarby_data.py:95: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('''select address from dbo.buildingaddress ; ''', conn,)['address'].to_list()

In [ ]:
thread_id = 'ebpuetk.vtdyrjiz@kth.se:liuwbbwqc834svweyyw30cå45vm'

In [ ]:
# messages = [
#     {
#         'role' : 'user' , 
#         'content' : 'What is the energy class of my building?'
#     },
#     {
#         'role' : 'assistant' , 
#         'content' : 'Can you please provide the building address?' , 
#         'parsed_intent': 'SQL database' , 
#         'intent_list': ['SQL database']
#     },
#     {
#         'role' : 'user' , 
#         'content' : 'I live in Karin Larssons Väg 79'
#     }
# ]

In [25]:
messages = [
    {
        'role' : 'user' , 
        'content' : 'What is the energy class of my building?'
    }
]

In [26]:

last_message = messages[-1]['content']
metadata = {
   
}

In [27]:
initial_state = {
            "thread_id": thread_id,
            "messages": messages,
            "metadata": metadata,
            "last_message": last_message,
            "session_state": {},
        }

In [28]:
graph = build_building_flow_graph()

[build_graph] wiring graph ...

In [29]:
final_state = graph.invoke(initial_state)

[understand_context] ENTER

INFO:src.agents.parse_intent_agent:LLM classification result: {"parsed_intent":"SQL database","address":null,"ambigious":false}

[understand_context] parsed keys=['last_message', 'messages', 'context']
[understand_context] ctx keys before ensure=['parsed_intent', 'address', 'ambigious', 'intent_list']
[understand_context] parsed_intent='SQL database' intent_list=['SQL database']
[understand_context] EXIT
[route_after_ambiguity] ENTER intents=['sql database'] addr=False single_filter=False ambiguous=False
[route_after_ambiguity] → request_address (sql but no address/filter)
[request_address] ENTER → END

In [30]:
final_state

{'thread_id': 'ebpuetk.vtdyrjiz@kth.se:liuwbbwqcf9w834svweyyw30cå45vm',
 'messages': [{'role': 'user',
   'content': 'What is the energy class of my building?'}],
 'metadata': {},
 'last_message': 'What is the energy class of my building?',
 'session_state': {},
 'context': {'parsed_intent': 'SQL database',
  'address': None,
  'ambigious': False,
  'intent_list': ['SQL database']},
 'final_response': 'Can you please provide the building address?'}

In [17]:
final_state = graph.invoke(initial_state)

[understand_context] ENTER

INFO:src.agents.parse_intent_agent:LLM classification result: {"parsed_intent":"SQL database ; vector database","address":null,"ambigious":false}

[understand_context] parsed keys=['last_message', 'messages', 'context']
[understand_context] ctx keys before ensure=['parsed_intent', 'address', 'ambigious', 'intent_list']
[understand_context] parsed_intent='SQL database ; vector database' intent_list=['SQL database', 'vector database']
[understand_context] EXIT
[route_after_ambiguity] ENTER intents=['sql database', 'vector database'] addr=True single_filter=False ambiguous=False
[route_after_ambiguity] → maintain_history (ready)
[maintain_history] ENTER last_matches=True
[maintain_history] EXIT
[decision_router] ENTER intents_norm=['sql database', 'vector database']
[decision_router] EXIT → ['generic_sql_agent', 'vector_db_agent']
[generic_sql_agent] ENTER addr='Karin Larssons Väg 79'
[vector_db_agent] ENTER q.len=50 entities=0
[vector_db_agent] hits=5
[vector_db_agent] EXIT
[generic_sql_agent] building_by_address ok=True
[generic_sql_agent] SUCCESS rows=1
[generic_sql_agent] EXIT
[wait_for_replies] required=['done_generic_sql', 'done_vector'] missing=[]
[route_after_wait] required=['done_generic_sql', 'done_vector'] all_done=True → aggregator
[aggregator] ENTER
[aggregator] outputs=2 agent_answered=sql+vector
[aggregator] EXIT
[llm_summarizer] ENTER

INFO:src.agents.openai_agent:Response generated in 16.55 seconds.

[llm_summarizer] generate_response ✓
[llm_summarizer] EXIT

In [12]:
final_state.keys()

dict_keys(['thread_id', 'messages', 'metadata', 'last_message', 'session_state', 'context', 'done_generic_sql', 'agent_data_generic', 'agent_outputs_generic', 'done_vector', 'agent_outputs_vector', 'waiting_required_flags', 'waiting_missing_flags', 'ready_to_aggregate', 'aggregated', 'agent_outputs', 'agent_data', 'aggregated_data', 'final_response', 'step_out'])

In [24]:
final_state['metadata']['debug']

{'agent_answered': 'sql+vector',
 'agent_answered_raw': [{'type': 'sql', 'name': 'generic_sql'},
  {'type': 'vector', 'name': 'vector'}]}

In [22]:
final_state['done_generic_sql']

True

In [32]:
print(final_state['final_response'])

Your building (detached single‐family house, erected 2016) currently holds an EPC class “C” in the 2020 calculation (it was class “B” under the 2016 rules). To move up into class B or even A, you must reduce your total primary‐energy demand and delivered energy. Typical measures include:

1. Improve the thermal envelope
   • Add or upgrade insulation in the attic and roof (e.g. increase to ≥ 350 mm mineral wool or equivalent)
   • Insulate external walls (internal retro-fit or external cladding with continuous insulation)
   • Seal and insulate under-floor/crawl-space areas
   • Replace any remaining double-glazed windows with high-performance triple glazing (low-E, argon fill, warm frame)

2. Reduce air leakage and heat losses
   • Perform a blower-door test, seal cracks around service penetrations, doors and windows
   • Install airtight interior membranes or tapes on critical junctions
   • Upgrade or install balanced mechanical ventilation with heat‐recovery (MVHR) to recover up to 85 % of ventilation heat losses

3. Optimize heating and hot water systems
   • Your current air‐source heat pump achieves good COP, but you can look at higher-efficiency models or consider a ground‐source (borehole) heat pump with higher seasonal performance factor (SPF)
   • Add a solar thermal collector for pre-heating domestic hot water, reducing load on the heat pump’s hot-water cycle
   • Fit smart controls (weather compensation, room thermostats, weekly scheduling, demand-based DHW control)

4. Generate on-site renewable electricity
   • Install photovoltaic panels sized to cover household electricity demand and heat-pump electricity (any on-site PV directly offsets your primary‐energy factor for grid electricity)
   • Consider small wind turbines (where locally permitted) or building‐integrated solar if roof orientation is ideal

5. Upgrade lighting and appliances
   • Convert all lighting to LEDs with daylight and presence sensors
   • Replace old appliances with A+++ rated models; use smart-metering to identify standby losses

6. Take advantage of grants and financing
   • In Sweden, check for Klimatklivet, ROT-avdrag (renovation tax credit) and Energimyndigheten’s support schemes for heat-pump upgrades and attic insulation
   • Combining several measures in a single project often unlocks higher subsidy levels

By systematically tightening the building envelope, recovering ventilation heat, upgrading your heat‐pump system and adding on-site renewables, you can drive your specific energy use well below the class B threshold and even aim for class A. Start with a professional energy audit to quantify each measure’s cost, energy savings and payback time.

#### building_agent

In [1]:
from src.agents.building_agent import BuildingAgent

INFO:src.agents.parse_intent_agent:Azure ChatCompletionsClient initialized for ParseIntentAgent.

dbo.buildingaddress(building_id integer PK, building_name text, address text PK)
dbo.buildings(building_id integer PK, numberOfApartments integer, numberOfTenullts integer, netAreaResidential integer, buildingName text, netAreaNonResidential integer, netAreaHeated integer, declaredEnergyClass text, EnergyClassKwhM2 integer)
dbo.electricity_enduses(id integer PK, electricity_used_for_property boolean, electricity_used_for_property_heating boolean, electricity_used_for_taphotwater boolean, electricity_used_for_apartments boolean, electricity_used_for_tenullts boolean, building_id integer, electricity_used_for_charging_station boolean)
dbo.hvac_systems(id integer PK, building_id integer, district_heating boolean, ground_source_heatpump_with_exhaust_air_recovery boolean, ground_source_heatpump_without_exahaust_air_recovery boolean, exhaust_air_recovery boolean, solar_thermal_panels boolean, district_cooling_production boolean, boiler_reserve boolean, cooling_production boolean, hvac_systems_installed_in_tenullts boolean)
dbo.meterings(uuid uuid PK, building_id integer, year integer, month text, electricity_use_property double precision, electricity_use_charging_station integer, electricity_use_lanudry_room double precision, electricity_use_water_heating_and_tap_hot_water double precision, electricity_use_apartments double precision, electricity_produced_pv double precision, electricity_excess_pv double precision, hot_water_produced_solar_thermal integer, electricity_purchased double precision, district_heating_purchased integer, district_cooling_purchased integer, electricity_sold integer)
dbo.normalization_values(id integer PK, building_id integer, indoor_temperature_sep_may double precision, hotwater_consumption_m3 integer, cold_water_consumption_m3 integer, scop_seasonal_coefficient_of_performance double precision, hotwater_source_for_towel_heater boolean, floor_heating_in_number_of_apartments integer)
dbo.results(building_id integer PK, year integer PK, deduction_household_heat_electricity double precision, deduction_household_heat_district_heating double precision, normal_household_eui double precision, tap_hotwater_m3 double precision, heating_constant_kwh_m3 double precision, energy_for_thw double precision, deduction_thw_district_heating double precision, total_property_energy_electricity double precision, deduction_pv double precision, deduction_electricity_indoor_temp double precision, energy_performance double precision, created_at timestamp, updated_at timestamp, deduction_thw_electricity double precision, primary_energy_district_cooling double precision, primary_energy_district_heating double precision, primary_energy_electricity double precision, total_deduction double precision, household_electricity_for_building_heat double precision, difference_household_heat_eui double precision, deduction_district_heating_indoor_temp double precision, deducted_property_district_heating_use double precision)
dbo.users(user_id integer PK, email text, password text, building_id integer)
[init] SpecializedSQLLayer initialized ✓
Connection to Vector Database established.
Connection to Vector Database established.
✅ VectorClient initialized and connected.
[init] VectorClient initialized ✓

INFO:src.agents.openai_agent:Initializing OpenAIResponseAgent.
INFO:src.agents.openai_agent:Prompt loaded successfully from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\openai_response_prompt.txt
INFO:src.agents.openai_agent:Azure OpenAI client initialized successfully for response agent.

[init] OpenAIResponseAgent initialized ✓
[init] Address list loaded: 42 entries

c:\Users\shada\Documents\spara-backend\src\database\hammarby_data.py:95: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('''select address from dbo.buildingaddress ; ''', conn,)['address'].to_list()

In [2]:
ba = BuildingAgent()

In [9]:
messages = [
    {
        'role' : 'user' , 
        'content' : 'How can i improve energy class of my building?'
    }, 
    {'content': 'Can you please provide the building address?',
 'agent_answered': '',
 'classification': 'building_specific',
 'parsed_intent': 'SQL database ; vector database',
 'intent_list': ['SQL database', 'vector database'],
 'agents_used': []}, 
    {'content':'i live in Teknigringen 10' , 'role' : 'user'}
]

In [10]:
metadata = {
}

In [11]:
value , metadata_updated = ba.handle_building_query(last_message = messages[-1]['content'] , messages=messages ,
                                 thread_id = 'ebpuetk.vtdyrjiz@kth.se:liuwbbwqc834svweyyw30cå45vm', metadata = metadata)

[build_graph] wiring graph ...
[understand_context] ENTER

INFO:src.agents.parse_intent_agent:LLM classification result: {"parsed_intent":"","address":"Teknigringen 10","ambigious":true}

[understand_context] parsed keys=['last_message', 'messages', 'context']
[understand_context] ctx keys before ensure=['parsed_intent', 'address', 'ambigious', 'intent_list']
[understand_context] restore intent failed: 'parsed_intent'
[understand_context] address set in metadata: 'Teknigringen 10'
[understand_context] parsed_intent='' intent_list=[]
[understand_context] EXIT
[route_after_ambiguity] ENTER intents=[] addr=True single_filter=False ambiguous=True
[route_after_ambiguity] → maintain_history (ambiguous but address/filter present)
[maintain_history] ENTER last_matches=True
[maintain_history] EXIT
[decision_router] ENTER intents_norm=[]
[decision_router] FALLBACK → ['generic_sql_agent'] (address/filter present)
[generic_sql_agent] ENTER addr='Teknigringen 10'
[generic_sql_agent] building_by_address ok=False
[generic_sql_agent] NO DATA
[generic_sql_agent] EXIT
[wait_for_replies] required=[] missing=[]
[route_after_wait] required=[] all_done=True → aggregator
[aggregator] ENTER
[aggregator] outputs=1 agent_answered=sql
[aggregator] EXIT
[llm_summarizer] ENTER

WARNING:src.agents.openai_agent:Skipping malformed message: {'content': 'Can you please provide the building address?', 'agent_answered': '', 'classification': 'building_specific', 'parsed_intent': 'SQL database ; vector database', 'intent_list': ['SQL database', 'vector database'], 'agents_used': []}
INFO:src.agents.openai_agent:Response generated in 7.00 seconds.

[llm_summarizer] generate_response ✓
[llm_summarizer] EXIT

In [14]:
value

{'content': 'Improving your building’s energy class is best managed in stages. Since we don’t yet have your current EPC rating for Teknigringen 10, the first step is to commission or review a valid Energy Performance Certificate (EPC). Once you know your existing class (e.g., D, E, F), you can target the most cost-effective upgrades. Typical measures include:\n\n1. Envelope Improvements  \n   • Loft and cavity‐wall insulation (or external wall insulation where needed)  \n   • Replacement or upgrade of windows to high‐performance double or triple glazing  \n   • Sealing of air leaks around doors, windows and service penetrations  \n\n2. Heating and Hot Water Upgrades  \n   • High-efficiency condensing boiler or air‐/ground-source heat pump  \n   • Smart controls and thermostatic radiator valves for zoning and reduced standby losses  \n   • Well-insulated hot-water cylinder or on-demand (tankless) water heater  \n\n3. Ventilation with Heat Recovery  \n   • Install a mechanical ventilation system with heat recovery (MVHR) to improve indoor air quality without heat loss  \n\n4. Renewable Technologies  \n   • Roof-mounted solar photovoltaic (PV) panels  \n   • Solar thermal collectors for pre-heating domestic hot water  \n   • Battery storage or smart export controls (where feasible)  \n\n5. Lighting and Appliances  \n   • Replace all lighting with LED fixtures and smart controls (motion sensors, daylight dimming)  \n   • Choose A+++ rated appliances and office equipment  \n\n6. Energy Management and Behavior  \n   • Install smart meters and building-management systems to monitor consumption in real time  \n   • Educate occupants on simple measures (e.g., thermostat setbacks, turning off unused equipment)  \n\nNext Steps  \na. Arrange for a qualified energy auditor or certified EPC assessor to survey your property.  \nb. Review their report to identify which measures yield the greatest return on investment and raise your EPC class.  \nc. Check available grants, subsidies or tax incentives for energy-efficiency upgrades in your municipality or country.  \n\nBy following a structured audit and prioritizing high-impact upgrades, you can raise your building’s energy class, lower running costs and improve comfort.',
 'agent_answered': 'sql',
 'classification': 'building_specific',
 'parsed_intent': '',
 'intent_list': [],
 'agents_used': ['ODEN API']}

In [15]:
metadata_updated

{}

In [16]:
from src.redis.redis_session_store import get_session_state

In [17]:
get_session_state('ebpuetk.vtdyrjiz@kth.se:liuwbbwqc834svweyyw30cå45vm')

[{'thread_id': 'ebpuetk.vtdyrjiz@kth.se:liuwbbwqc834svweyyw30cå45vm',
  'messages': [{'role': 'user',
    'content': 'How can i improve energy class of my building?'},
   {'content': 'Can you please provide the building address?',
    'agent_answered': '',
    'classification': 'building_specific',
    'parsed_intent': 'SQL database ; vector database',
    'intent_list': ['SQL database', 'vector database'],
    'agents_used': []},
   {'content': 'i live in Karin Larssons Väg 79', 'role': 'user'}],
  'metadata': {'address': 'Karin Larssons Väg 79',
   'address_from_user': 'Karin Larssons Väg 79',
   'debug': {'agent_answered': 'sql',
    'agent_answered_raw': [{'type': 'sql', 'name': 'generic_sql'}]}},
  'last_message': 'i live in Karin Larssons Väg 79',
  'session_state': {'last_intent_list': []},
  'context': {'parsed_intent': '',
   'address': 'Karin Larssons Väg 79',
   'ambigious': True,
   'intent_list': []},
  'done_generic_sql': True,
  'agent_data_generic': [{'byggnadsid': '01-80-GASKEN2-1',
    'epc_fjarrvarmenetworkname_calc': None,
    'epc_egirefvarde1bbr29_calc': 90,
    'epc_egenprojventflode_calc': None,
    'epc_egifgeo_calc': 1.0,
    'epc_egiprimarenergital2020_calc': 68,
    'epc_egiprimarenergianvandning2020_calc': 10876,
    'epc_egisumma2_calc': None,
    'epc_egienergianvandning_eindex_calc': 6042.0,
    'epc_energiindex_calc': 1.014055,
    'epc_egispecifikenergianvandning_calc': 38,
    'epc_egispecifikenergianvandning_eindex_calc': 38.0,
    'epc_egienergianvandning_calc': 6042,
    'epc_egitappvarmvattenperm2_calc': 8.050314465408805,
    'epc_egivarme_calc': 5500,
    'epc_egiuppvarmning_calc': 4220,
    'epc_egitappvarmvatten_calc': 1280,
    'epc_el_calc': 5976,
    'epc_elovr_calc': 476,
    'epc_versionorder_calc': 0,
    '01a_fnr': '010528602',
    '50a_deso': '0180C1240',
    '50a_husnridmerge': '010528602-1',
    '50a_uuid': '8fd266c0-56dd-489b-8e08-a0c08a93ec86',
    'epc_egenantalbolgh': None,
    'epc_egenantalkallarplan': None,
    'epc_egenantalplan': None,
    'epc_egenantaltrapphus': None,
    'epc_egenatemp': 159,
    'epc_egenatempbad': None,
    'epc_egenatempbostad': 100,
    'epc_egenatempbutik': None,
    'epc_egenatemphotell': None,
    'epc_egenatempkontor': None,
    'epc_egenatempkopcentrum': None,
    'epc_egenatemplivsmedel': None,
    'epc_egenatempovrig': None,
    'epc_egenatempovrigavad': None,
    'epc_egenatemprestaurang': None,
    'epc_egenatempskolor': None,
    'epc_egenatempsumma': 100,
    'epc_egenatempteater': None,
    'epc_egenatempvard': None,
    'epc_egenatempvarddag': None,
    'epc_egenavarmgarage': None,
    'epc_egenboa': None,
    'epc_egenbra': None,
    'epc_egenbta': None,
    'epc_egenbyggnadskat': 'En- och tvåbostadshus',
    'epc_egenbyggnadstyp': 'Friliggande',
    'epc_egengruppatemp': 'Mätt',
    'epc_egeninsteleffektstorre': 'Ja',
    'epc_egenkomplexitet': 'Enkel',
    'epc_egenloa': None,
    'epc_egennybyggar': 2016,
    'epc_egenprojventflode': None,
    'epc_egensarskiltvardefull': 'Nej',
    'epc_egenskyddadbyggnad': 'Nej',
    'epc_egenskyddadellervardefull': None,
    'epc_egensmalagenheter': 'Nej',
    'epc_egentypkod': '220',
    'epc_egentypkod_typ': '220 - Småhusenhet, bebyggd',
    'epc_egiberaknatvarde': 'Ja',
    'epc_egiberelproduktion': None,
    'epc_egiberengproduktion': None,
    'epc_egieldirekt': 0,
    'epc_egieldirektuppv': 0,
    'epc_egielluft': 0,
    'epc_egielluftuppv': 0,
    'epc_egielvatten': 0,
    'epc_egielvattenuppv': 0,
    'epc_egielvv': 1280,
    'epc_egienergianvandning': None,
    'epc_egienergiklass': 'B',
    'epc_egienergiprestanda': 38,
    'epc_egifastighet': 476,
    'epc_egifjarrkyla': 0,
    'epc_egifjarrvarme': 0,
    'epc_egifjarrvarmeuppv': 0,
    'epc_egifjarrvarmevv': 0,
    'epc_egiflis': 0,
    'epc_egiflisuppv': 0,
    'epc_egiflisvv': 0,
    'epc_egiforstaarmanad': None,
    'epc_egigas': 0,
    'epc_egigasuppv': 0,
    'epc_egigasvv': 0,
    'epc_egigruppeldirekt': None,
    'epc_egigruppelluft': None,
    'epc_egigruppelvatten': None,
    'epc_egigruppfastighet': None,
    'epc_egigruppfjarrkyla': None,
    'epc_egigruppfjarrvarme': None,
    'epc_egigruppflis': None,
    'epc_egigruppgas': None,
    'epc_egigrupphushall': None,
    'epc_egigruppkomfort': None,
    'epc_egigruppolja': None,
    'epc_egigruppovrbiobransle': None,
    'epc_egigrupppumpfranluft': None,
    'epc_egigrupppumpluftluft': None,
    'epc_egigrupppumpluftvatten': None,
    'epc_egigrupppumpmark': None,
    'epc_egigruppsolcell': 'Nej',
    'epc_egigruppsolvarme': 'Nej',
    'epc_egigruppved': None,
    'epc_egigruppverksamhet': None,
    'epc_egigruppvvbered': None,
    'epc_egihushall': 0,
    'epc_egikomfort': 0,
    'epc_egikomforttillagg': 0,
    'epc_eginormkorrei': None,
    'epc_eginormkorrgd': None,
    'epc_egiolja': 0,
    'epc_egioljauppv': 0,
    'epc_egioljavv': 0,
    'epc_egiovrbiobransle': 0,
    'epc_egiovrbiobransleuppv': 0,
    'epc_egiovrbiobranslevv': 0,
    'epc_egiprimarenergianvandning': None,
    'epc_egiprimarenergital': None,
    'epc_egipumpfranluft': 5500,
    'epc_egipumpfranluftuppv': 4220,
    'epc_egipumpluftluft': 0,
    'epc_egipumpluftluftuppv': 0,
    'epc_egipumpluftvatten': 0,
    'epc_egipumpluftvattenuppv': 0,
    'epc_egipumpmark': 0,
    'epc_egipumpmarkuppv': 0,
    'epc_egirefvarde1': 55,
    'epc_egirefvarde2max': 106,
    'epc_egirefvarde2min': 86,
    'epc_egirefvarde3': None,
    'epc_egisistaarmanad': None,
    'epc_egisolcell': None,
    'epc_egisolvarme': None,
    'epc_egistationei': None,
    'epc_egistationgd': None,
    'epc_egisumma1': 5500,
    'epc_egisumma2': 5976,
    'epc_egisumma3': 5976,
    'epc_egisumma4': 5976,
    'epc_egivaravel': 38,
    'epc_egived': 0,
    'epc_egiveduppv': 0,
    'epc_egivedvv': 0,
    'epc_egiverksamhet': 0,
    'epc_egiversion': '2015',
    'epc_egivvbered': 1280,
    'epc_formularid': '752340',
    'epc_godkand': '2016-12-29',
    'epc_id': '01-80-GASKEN2',
    'epc_idadr': 'Karin Larssons Väg 79',
    'epc_idegnahem': '1',
    'epc_idfastbet': 'Gasken 2',
    'epc_idhusnr': '1',
    'epc_idhuvudadress': 'Ja',
    'epc_idkommun': 'Stockholm',
    'epc_idkommunkod': '80',
    'epc_idlan': 'Stockholms län',
    'epc_idlankod': '01',
    'epc_idpostnr': '12863',
    'epc_idpostort': 'Sköndal',
    'epc_idrapportlm': None,
    'epc_luftgruppfinnsluft': 'Nej',
    'epc_ventdelvisprocent': None,
    'epc_ventgruppgodkand': None,
    'epc_ventgruppkrav': 'Nej',
    'epc_venttypf': 'Nej',
    'epc_venttypfmed': 'Ja',
    'epc_venttypft': 'Nej',
    'epc_venttypftx': 'Nej',
    'epc_venttypsjalvdrag': 'Nej',
    'epc_version': '2.4',
    'epc_egiprimarenergital2019': None,
    'epc_egiprimarenergital2020': None,
    'epc_egispecifikenergianvandning': 38,
    'epc_expertgrupphosuppdragsgivare': None,
    'epc_inspluftangenomeffekt': None,
    'epc_inspluftangenomeffektyta': None,
    'epc_inspluftbedomningnomeffekt': None,
    'epc_inspluftgruppinspskyldighet': None,
    'epc_inspluftgrupplamplig': None,
    'epc_inspluftgruppnomstorre': None,
    'epc_inspluftlampligkommentar': '',
    'epc_inspluftundavtalegipres': None,
    'epc_inspluftundfunkoverreglbost': None,
    'epc_inspluftundsysfaststyr': None,
    'epc_inspuppvangenomeffekt': None,
    'epc_inspuppvangenomeffektyta': None,
    'epc_inspuppvbedomningnomeffekt': None,
    'epc_inspuppvgruppinspskyldighet': None,
    'epc_inspuppvgrupplamplig': None,
    'epc_inspuppvgruppnomstorre': None,
    'epc_inspuppvlampligkommentar': '',
    'epc_inspuppvundavtalegipres': None,
    'epc_inspuppvundfunkoverreglbost': None,
    'epc_inspuppvundsysfaststyr': None,
    'epc_sourceversion_calc': '19',
    'epc_ventgrupputananm': None,
    'epc_radgrupphaltmatt': 'Nej',
    'epc_radtypmatning': None,
    'epc_radmatdatum': None,
    'epc_radhalt': None,
    'epc_antalbyggdek_calc': 1,
    'epc_antalgamladek_calc': 1,
    'epc_localversion_calc': 1,
    'epc_egienergiklass2020_calc': 'C',
    'epc_huvudsakliguppvarmning_calc': 'PumpFranluft',
    'epc_egienergiklass2016_calc': 'B'}],
  'agent_outputs_generic': ['generic_sql: ok'],
  'waiting_required_flags': [],
  'waiting_missing_flags': [],
  'ready_to_aggregate': True,
  'aggregated': 'generic_sql: ok',
  'agent_outputs': ['generic_sql: ok'],
  'agent_data': {'generic_sql': [{'byggnadsid': '01-80-GASKEN2-1',
     'epc_fjarrvarmenetworkname_calc': None,
     'epc_egirefvarde1bbr29_calc': 90,
     'epc_egenprojventflode_calc': None,
     'epc_egifgeo_calc': 1.0,
     'epc_egiprimarenergital2020_calc': 68,
     'epc_egiprimarenergianvandning2020_calc': 10876,
     'epc_egisumma2_calc': None,
     'epc_egienergianvandning_eindex_calc': 6042.0,
     'epc_energiindex_calc': 1.014055,
     'epc_egispecifikenergianvandning_calc': 38,
     'epc_egispecifikenergianvandning_eindex_calc': 38.0,
     'epc_egienergianvandning_calc': 6042,
     'epc_egitappvarmvattenperm2_calc': 8.050314465408805,
     'epc_egivarme_calc': 5500,
     'epc_egiuppvarmning_calc': 4220,
     'epc_egitappvarmvatten_calc': 1280,
     'epc_el_calc': 5976,
     'epc_elovr_calc': 476,
     'epc_versionorder_calc': 0,
     '01a_fnr': '010528602',
     '50a_deso': '0180C1240',
     '50a_husnridmerge': '010528602-1',
     '50a_uuid': '8fd266c0-56dd-489b-8e08-a0c08a93ec86',
     'epc_egenantalbolgh': None,
     'epc_egenantalkallarplan': None,
     'epc_egenantalplan': None,
     'epc_egenantaltrapphus': None,
     'epc_egenatemp': 159,
     'epc_egenatempbad': None,
     'epc_egenatempbostad': 100,
     'epc_egenatempbutik': None,
     'epc_egenatemphotell': None,
     'epc_egenatempkontor': None,
     'epc_egenatempkopcentrum': None,
     'epc_egenatemplivsmedel': None,
     'epc_egenatempovrig': None,
     'epc_egenatempovrigavad': None,
     'epc_egenatemprestaurang': None,
     'epc_egenatempskolor': None,
     'epc_egenatempsumma': 100,
     'epc_egenatempteater': None,
     'epc_egenatempvard': None,
     'epc_egenatempvarddag': None,
     'epc_egenavarmgarage': None,
     'epc_egenboa': None,
     'epc_egenbra': None,
     'epc_egenbta': None,
     'epc_egenbyggnadskat': 'En- och tvåbostadshus',
     'epc_egenbyggnadstyp': 'Friliggande',
     'epc_egengruppatemp': 'Mätt',
     'epc_egeninsteleffektstorre': 'Ja',
     'epc_egenkomplexitet': 'Enkel',
     'epc_egenloa': None,
     'epc_egennybyggar': 2016,
     'epc_egenprojventflode': None,
     'epc_egensarskiltvardefull': 'Nej',
     'epc_egenskyddadbyggnad': 'Nej',
     'epc_egenskyddadellervardefull': None,
     'epc_egensmalagenheter': 'Nej',
     'epc_egentypkod': '220',
     'epc_egentypkod_typ': '220 - Småhusenhet, bebyggd',
     'epc_egiberaknatvarde': 'Ja',
     'epc_egiberelproduktion': None,
     'epc_egiberengproduktion': None,
     'epc_egieldirekt': 0,
     'epc_egieldirektuppv': 0,
     'epc_egielluft': 0,
     'epc_egielluftuppv': 0,
     'epc_egielvatten': 0,
     'epc_egielvattenuppv': 0,
     'epc_egielvv': 1280,
     'epc_egienergianvandning': None,
     'epc_egienergiklass': 'B',
     'epc_egienergiprestanda': 38,
     'epc_egifastighet': 476,
     'epc_egifjarrkyla': 0,
     'epc_egifjarrvarme': 0,
     'epc_egifjarrvarmeuppv': 0,
     'epc_egifjarrvarmevv': 0,
     'epc_egiflis': 0,
     'epc_egiflisuppv': 0,
     'epc_egiflisvv': 0,
     'epc_egiforstaarmanad': None,
     'epc_egigas': 0,
     'epc_egigasuppv': 0,
     'epc_egigasvv': 0,
     'epc_egigruppeldirekt': None,
     'epc_egigruppelluft': None,
     'epc_egigruppelvatten': None,
     'epc_egigruppfastighet': None,
     'epc_egigruppfjarrkyla': None,
     'epc_egigruppfjarrvarme': None,
     'epc_egigruppflis': None,
     'epc_egigruppgas': None,
     'epc_egigrupphushall': None,
     'epc_egigruppkomfort': None,
     'epc_egigruppolja': None,
     'epc_egigruppovrbiobransle': None,
     'epc_egigrupppumpfranluft': None,
     'epc_egigrupppumpluftluft': None,
     'epc_egigrupppumpluftvatten': None,
     'epc_egigrupppumpmark': None,
     'epc_egigruppsolcell': 'Nej',
     'epc_egigruppsolvarme': 'Nej',
     'epc_egigruppved': None,
     'epc_egigruppverksamhet': None,
     'epc_egigruppvvbered': None,
     'epc_egihushall': 0,
     'epc_egikomfort': 0,
     'epc_egikomforttillagg': 0,
     'epc_eginormkorrei': None,
     'epc_eginormkorrgd': None,
     'epc_egiolja': 0,
     'epc_egioljauppv': 0,
     'epc_egioljavv': 0,
     'epc_egiovrbiobransle': 0,
     'epc_egiovrbiobransleuppv': 0,
     'epc_egiovrbiobranslevv': 0,
     'epc_egiprimarenergianvandning': None,
     'epc_egiprimarenergital': None,
     'epc_egipumpfranluft': 5500,
     'epc_egipumpfranluftuppv': 4220,
     'epc_egipumpluftluft': 0,
     'epc_egipumpluftluftuppv': 0,
     'epc_egipumpluftvatten': 0,
     'epc_egipumpluftvattenuppv': 0,
     'epc_egipumpmark': 0,
     'epc_egipumpmarkuppv': 0,
     'epc_egirefvarde1': 55,
     'epc_egirefvarde2max': 106,
     'epc_egirefvarde2min': 86,
     'epc_egirefvarde3': None,
     'epc_egisistaarmanad': None,
     'epc_egisolcell': None,
     'epc_egisolvarme': None,
     'epc_egistationei': None,
     'epc_egistationgd': None,
     'epc_egisumma1': 5500,
     'epc_egisumma2': 5976,
     'epc_egisumma3': 5976,
     'epc_egisumma4': 5976,
     'epc_egivaravel': 38,
     'epc_egived': 0,
     'epc_egiveduppv': 0,
     'epc_egivedvv': 0,
     'epc_egiverksamhet': 0,
     'epc_egiversion': '2015',
     'epc_egivvbered': 1280,
     'epc_formularid': '752340',
     'epc_godkand': '2016-12-29',
     'epc_id': '01-80-GASKEN2',
     'epc_idadr': 'Karin Larssons Väg 79',
     'epc_idegnahem': '1',
     'epc_idfastbet': 'Gasken 2',
     'epc_idhusnr': '1',
     'epc_idhuvudadress': 'Ja',
     'epc_idkommun': 'Stockholm',
     'epc_idkommunkod': '80',
     'epc_idlan': 'Stockholms län',
     'epc_idlankod': '01',
     'epc_idpostnr': '12863',
     'epc_idpostort': 'Sköndal',
     'epc_idrapportlm': None,
     'epc_luftgruppfinnsluft': 'Nej',
     'epc_ventdelvisprocent': None,
     'epc_ventgruppgodkand': None,
     'epc_ventgruppkrav': 'Nej',
     'epc_venttypf': 'Nej',
     'epc_venttypfmed': 'Ja',
     'epc_venttypft': 'Nej',
     'epc_venttypftx': 'Nej',
     'epc_venttypsjalvdrag': 'Nej',
     'epc_version': '2.4',
     'epc_egiprimarenergital2019': None,
     'epc_egiprimarenergital2020': None,
     'epc_egispecifikenergianvandning': 38,
     'epc_expertgrupphosuppdragsgivare': None,
     'epc_inspluftangenomeffekt': None,
     'epc_inspluftangenomeffektyta': None,
     'epc_inspluftbedomningnomeffekt': None,
     'epc_inspluftgruppinspskyldighet': None,
     'epc_inspluftgrupplamplig': None,
     'epc_inspluftgruppnomstorre': None,
     'epc_inspluftlampligkommentar': '',
     'epc_inspluftundavtalegipres': None,
     'epc_inspluftundfunkoverreglbost': None,
     'epc_inspluftundsysfaststyr': None,
     'epc_inspuppvangenomeffekt': None,
     'epc_inspuppvangenomeffektyta': None,
     'epc_inspuppvbedomningnomeffekt': None,
     'epc_inspuppvgruppinspskyldighet': None,
     'epc_inspuppvgrupplamplig': None,
     'epc_inspuppvgruppnomstorre': None,
     'epc_inspuppvlampligkommentar': '',
     'epc_inspuppvundavtalegipres': None,
     'epc_inspuppvundfunkoverreglbost': None,
     'epc_inspuppvundsysfaststyr': None,
     'epc_sourceversion_calc': '19',
     'epc_ventgrupputananm': None,
     'epc_radgrupphaltmatt': 'Nej',
     'epc_radtypmatning': None,
     'epc_radmatdatum': None,
     'epc_radhalt': None,
     'epc_antalbyggdek_calc': 1,
     'epc_antalgamladek_calc': 1,
     'epc_localversion_calc': 1,
     'epc_egienergiklass2020_calc': 'C',
     'epc_huvudsakliguppvarmning_calc': 'PumpFranluft',
     'epc_egienergiklass2016_calc': 'B'}]},
  'aggregated_data': {'generic_sql': [{'byggnadsid': '01-80-GASKEN2-1',
     'epc_fjarrvarmenetworkname_calc': None,
     'epc_egirefvarde1bbr29_calc': 90,
     'epc_egenprojventflode_calc': None,
     'epc_egifgeo_calc': 1.0,
     'epc_egiprimarenergital2020_calc': 68,
     'epc_egiprimarenergianvandning2020_calc': 10876,
     'epc_egisumma2_calc': None,
     'epc_egienergianvandning_eindex_calc': 6042.0,
     'epc_energiindex_calc': 1.014055,
     'epc_egispecifikenergianvandning_calc': 38,
     'epc_egispecifikenergianvandning_eindex_calc': 38.0,
     'epc_egienergianvandning_calc': 6042,
     'epc_egitappvarmvattenperm2_calc': 8.050314465408805,
     'epc_egivarme_calc': 5500,
     'epc_egiuppvarmning_calc': 4220,
     'epc_egitappvarmvatten_calc': 1280,
     'epc_el_calc': 5976,
     'epc_elovr_calc': 476,
     'epc_versionorder_calc': 0,
     '01a_fnr': '010528602',
     '50a_deso': '0180C1240',
     '50a_husnridmerge': '010528602-1',
     '50a_uuid': '8fd266c0-56dd-489b-8e08-a0c08a93ec86',
     'epc_egenantalbolgh': None,
     'epc_egenantalkallarplan': None,
     'epc_egenantalplan': None,
     'epc_egenantaltrapphus': None,
     'epc_egenatemp': 159,
     'epc_egenatempbad': None,
     'epc_egenatempbostad': 100,
     'epc_egenatempbutik': None,
     'epc_egenatemphotell': None,
     'epc_egenatempkontor': None,
     'epc_egenatempkopcentrum': None,
     'epc_egenatemplivsmedel': None,
     'epc_egenatempovrig': None,
     'epc_egenatempovrigavad': None,
     'epc_egenatemprestaurang': None,
     'epc_egenatempskolor': None,
     'epc_egenatempsumma': 100,
     'epc_egenatempteater': None,
     'epc_egenatempvard': None,
     'epc_egenatempvarddag': None,
     'epc_egenavarmgarage': None,
     'epc_egenboa': None,
     'epc_egenbra': None,
     'epc_egenbta': None,
     'epc_egenbyggnadskat': 'En- och tvåbostadshus',
     'epc_egenbyggnadstyp': 'Friliggande',
     'epc_egengruppatemp': 'Mätt',
     'epc_egeninsteleffektstorre': 'Ja',
     'epc_egenkomplexitet': 'Enkel',
     'epc_egenloa': None,
     'epc_egennybyggar': 2016,
     'epc_egenprojventflode': None,
     'epc_egensarskiltvardefull': 'Nej',
     'epc_egenskyddadbyggnad': 'Nej',
     'epc_egenskyddadellervardefull': None,
     'epc_egensmalagenheter': 'Nej',
     'epc_egentypkod': '220',
     'epc_egentypkod_typ': '220 - Småhusenhet, bebyggd',
     'epc_egiberaknatvarde': 'Ja',
     'epc_egiberelproduktion': None,
     'epc_egiberengproduktion': None,
     'epc_egieldirekt': 0,
     'epc_egieldirektuppv': 0,
     'epc_egielluft': 0,
     'epc_egielluftuppv': 0,
     'epc_egielvatten': 0,
     'epc_egielvattenuppv': 0,
     'epc_egielvv': 1280,
     'epc_egienergianvandning': None,
     'epc_egienergiklass': 'B',
     'epc_egienergiprestanda': 38,
     'epc_egifastighet': 476,
     'epc_egifjarrkyla': 0,
     'epc_egifjarrvarme': 0,
     'epc_egifjarrvarmeuppv': 0,
     'epc_egifjarrvarmevv': 0,
     'epc_egiflis': 0,
     'epc_egiflisuppv': 0,
     'epc_egiflisvv': 0,
     'epc_egiforstaarmanad': None,
     'epc_egigas': 0,
     'epc_egigasuppv': 0,
     'epc_egigasvv': 0,
     'epc_egigruppeldirekt': None,
     'epc_egigruppelluft': None,
     'epc_egigruppelvatten': None,
     'epc_egigruppfastighet': None,
     'epc_egigruppfjarrkyla': None,
     'epc_egigruppfjarrvarme': None,
     'epc_egigruppflis': None,
     'epc_egigruppgas': None,
     'epc_egigrupphushall': None,
     'epc_egigruppkomfort': None,
     'epc_egigruppolja': None,
     'epc_egigruppovrbiobransle': None,
     'epc_egigrupppumpfranluft': None,
     'epc_egigrupppumpluftluft': None,
     'epc_egigrupppumpluftvatten': None,
     'epc_egigrupppumpmark': None,
     'epc_egigruppsolcell': 'Nej',
     'epc_egigruppsolvarme': 'Nej',
     'epc_egigruppved': None,
     'epc_egigruppverksamhet': None,
     'epc_egigruppvvbered': None,
     'epc_egihushall': 0,
     'epc_egikomfort': 0,
     'epc_egikomforttillagg': 0,
     'epc_eginormkorrei': None,
     'epc_eginormkorrgd': None,
     'epc_egiolja': 0,
     'epc_egioljauppv': 0,
     'epc_egioljavv': 0,
     'epc_egiovrbiobransle': 0,
     'epc_egiovrbiobransleuppv': 0,
     'epc_egiovrbiobranslevv': 0,
     'epc_egiprimarenergianvandning': None,
     'epc_egiprimarenergital': None,
     'epc_egipumpfranluft': 5500,
     'epc_egipumpfranluftuppv': 4220,
     'epc_egipumpluftluft': 0,

#### Redis manager test

In [1]:
from src.pipeline.agent_router import AgentRouter

INFO:src.agents.parse_intent_agent:Azure ChatCompletionsClient initialized for ParseIntentAgent.

dbo.buildingaddress(building_id integer PK, building_name text, address text PK)
dbo.buildings(building_id integer PK, numberOfApartments integer, numberOfTenullts integer, netAreaResidential integer, buildingName text, netAreaNonResidential integer, netAreaHeated integer, declaredEnergyClass text, EnergyClassKwhM2 integer)
dbo.electricity_enduses(id integer PK, electricity_used_for_property boolean, electricity_used_for_property_heating boolean, electricity_used_for_taphotwater boolean, electricity_used_for_apartments boolean, electricity_used_for_tenullts boolean, building_id integer, electricity_used_for_charging_station boolean)
dbo.hvac_systems(id integer PK, building_id integer, district_heating boolean, ground_source_heatpump_with_exhaust_air_recovery boolean, ground_source_heatpump_without_exahaust_air_recovery boolean, exhaust_air_recovery boolean, solar_thermal_panels boolean, district_cooling_production boolean, boiler_reserve boolean, cooling_production boolean, hvac_systems_installed_in_tenullts boolean)
dbo.meterings(uuid uuid PK, building_id integer, year integer, month text, electricity_use_property double precision, electricity_use_charging_station integer, electricity_use_lanudry_room double precision, electricity_use_water_heating_and_tap_hot_water double precision, electricity_use_apartments double precision, electricity_produced_pv double precision, electricity_excess_pv double precision, hot_water_produced_solar_thermal integer, electricity_purchased double precision, district_heating_purchased integer, district_cooling_purchased integer, electricity_sold integer)
dbo.normalization_values(id integer PK, building_id integer, indoor_temperature_sep_may double precision, hotwater_consumption_m3 integer, cold_water_consumption_m3 integer, scop_seasonal_coefficient_of_performance double precision, hotwater_source_for_towel_heater boolean, floor_heating_in_number_of_apartments integer)
dbo.results(building_id integer PK, year integer PK, deduction_household_heat_electricity double precision, deduction_household_heat_district_heating double precision, normal_household_eui double precision, tap_hotwater_m3 double precision, heating_constant_kwh_m3 double precision, energy_for_thw double precision, deduction_thw_district_heating double precision, total_property_energy_electricity double precision, deduction_pv double precision, deduction_electricity_indoor_temp double precision, energy_performance double precision, created_at timestamp, updated_at timestamp, deduction_thw_electricity double precision, primary_energy_district_cooling double precision, primary_energy_district_heating double precision, primary_energy_electricity double precision, total_deduction double precision, household_electricity_for_building_heat double precision, difference_household_heat_eui double precision, deduction_district_heating_indoor_temp double precision, deducted_property_district_heating_use double precision)
dbo.users(user_id integer PK, email text, password text, building_id integer)
[init] SpecializedSQLLayer initialized ✓
Connection to Vector Database established.
Connection to Vector Database established.
✅ VectorClient initialized and connected.
[init] VectorClient initialized ✓

INFO:src.agents.openai_agent:Initializing OpenAIResponseAgent.
INFO:src.agents.openai_agent:Prompt loaded successfully from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\openai_response_prompt.txt
INFO:src.agents.openai_agent:Azure OpenAI client initialized successfully for response agent.

[init] OpenAIResponseAgent initialized ✓
[init] Address list loaded: 42 entries

c:\Users\shada\Documents\spara-backend\src\database\hammarby_data.py:95: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('''select address from dbo.buildingaddress ; ''', conn,)['address'].to_list()
INFO:src.agents.router_agent:Router Model is gpt-4o-mini-2 and the api version is 2025-01-01-preview.
INFO:src.agents.router_agent:AzureOpenAI client for RouterAgent initialized successfully.

In [2]:
ag = AgentRouter()

INFO:src.agents.router_agent:Initializing RouterAgent.
INFO:src.agents.router_agent:RouterAgent prompt template loaded from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\classification_prompt.txt

Connection to Vector Database established.

INFO:src.agents.generic_agent:Successfully loaded prompt from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\generic_prompt.txt
INFO:src.agents.generic_agent:GenericAgent prompt template loaded from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\generic_prompt.txt
INFO:src.agents.generic_agent:Generic Model is gpt-4o-mini and the api version is 2025-01-01-preview.

Connection to Vector Database established.
✅ VectorClient initialized and connected.

INFO:src.agents.generic_agent:AzureOpenAI client initialized successfully.
INFO:src.agents.conversationalist_agent:Initializing ConversationalAgent.
INFO:src.agents.conversationalist_agent:Successfully loaded prompt from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\conversational_prompt.txt
INFO:src.agents.conversationalist_agent:ConversationalAgent prompt template loaded from: c:\Users\shada\Documents\spara-backend\src\agents\..\prompts\conversational_prompt.txt
INFO:src.agents.conversationalist_agent:Conversational Model is gpt-4-32k and the api version is 2025-01-01-preview.
INFO:src.agents.conversationalist_agent:AzureOpenAI client initialized successfully.

In [10]:
messages = [
    {
        'role' : 'user' , 
        'content' : 'what is the primary source of heat for my building'
    }
]
metadata = {
    'address' : 'Karin Larssons Väg 79'
}

In [32]:
messages.append({'role' : 'user' , 'content' : 'how can i imporve the energy class of my building?'})

In [33]:
value , metadata = ag.route_message(messages=messages , last_message=messages[-1]['content'] , 
                                    metadata = metadata , thread_id='ebpuetk.vtdyrjiz@kth.se:liuwbbwqc834svweyyw30cå45vm')

INFO:src.agents.router_agent:Classifying question: 'how can i imporve the energy class of my building?...'
INFO:src.agents.router_agent:Question classified successfully: 'building_specific' for message: 'how can i imporve the energy class of my building?...'

Classification Agent responded in 6.04436469078064 seconds
[build_graph] wiring graph ...
[understand_context] ENTER

INFO:src.agents.parse_intent_agent:LLM classification result: {"parsed_intent":"SQL database ; vector database","address":null,"ambigious":false}

[understand_context] parsed keys=['last_message', 'messages', 'context']
[understand_context] ctx keys before ensure=['parsed_intent', 'address', 'ambigious', 'intent_list']
[understand_context] parsed_intent='SQL database ; vector database' intent_list=['SQL database', 'vector database']
[understand_context] EXIT
[route_after_ambiguity] ENTER intents=['sql database', 'vector database'] addr=True single_filter=False ambiguous=False
[route_after_ambiguity] → maintain_history (ready)
[maintain_history] ENTER last_matches=True
[maintain_history] EXIT
[decision_router] ENTER intents_norm=['sql database', 'vector database']
[decision_router] EXIT → ['generic_sql_agent', 'vector_db_agent']
[generic_sql_agent] ENTER addr='Karin Larssons Väg 79'
[vector_db_agent] ENTER q.len=50 entities=0
[vector_db_agent] hits=5
[vector_db_agent] EXIT
[generic_sql_agent] building_by_address ok=True
[generic_sql_agent] SUCCESS rows=1
[generic_sql_agent] EXIT
[wait_for_replies] required=['done_generic_sql', 'done_vector'] missing=[]
[route_after_wait] required=['done_generic_sql', 'done_vector'] all_done=True → aggregator
[aggregator] ENTER
[aggregator] outputs=2 agent_answered=sql+vector
[aggregator] EXIT
[llm_summarizer] ENTER

WARNING:src.agents.openai_agent:Skipping malformed message: {'content': 'The primary heating system in your building is an air-source heat pump (in Swedish: “Pump från luft”). According to the latest EPC calculation:\n\n• Huvudsaklig uppvärmning: Pump från luft  \n• Primärenergiförbrukning för värme (epc_egipumpfranluft): 5 500 kWh/year  \n• Använd värmeenergi för uppvärmning (epc_egipumpfranluftuppv): 4 220 kWh/year  \n\nThis means that most of your space-heating demand is covered by an air-source heat pump.', 'classification': 'building_specific', 'agent_answered': 'sql', 'intent': None, 'agents_used': ['ODEN API'], 'vector_sources': []}
WARNING:src.agents.openai_agent:Skipping malformed message: {'content': 'That’s a building-specific question, and the system can help with that! Feel free to ask directly about your building, and we’ll guide you. 😊', 'classification': 'conversational', 'agent_answered': 'conversationalist', 'intent': None, 'agents_used': [], 'vector_sources': []}
WARNING:src.agents.openai_agent:Skipping malformed message: {'content': "To improve energy efficiency in your building (BRF EnERgIEFFEKTI v22), consider the following actionable steps:\n\n### Indoor Temperature Management\n- **Monitor Indoor Temperature**: Measure the indoor temperature in various apartments during the heating season to assess balance in the heating system.\n- **Adjust Temperature Settings**: Lower the indoor temperature by 1°C (e.g., from 22°C to 21°C) to potentially reduce heating costs by approximately 5%.\n- **Install Thermostat Valves**: Equip radiators with thermostat valves to optimize heating based on occupancy and solar gain.\n\n### Ventilation Improvements\n- **Assess Ventilation System**: Review the existing ventilation system to ensure it effectively removes moisture and odors while providing fresh air without drafts.\n- **Upgrade Ventilation**: Consider modernizing the ventilation system if it is outdated, as older systems may be less efficient.\n\n### Heating System Optimization\n- **Evaluate Heating Source**: Determine if the current heating source (e.g., Fjärrvärme, biofuels) is the most efficient option for your building.\n- **Consider Long-term Contracts**: If using biofuels, establish long-term agreements with reliable suppliers to ensure consistent quality and potentially lower costs.\n- **Explore Alternative Heating Systems**: Investigate the feasibility of switching to more efficient heating systems, such as heat pumps or improved biofuel systems.\n\n### Collaboration and Support\n- **Engage with Energy Advisors**: Contact your local energy advisor for free guidance on heating options and effective measures tailored to your building's needs.\n- **Collaborate with Other BRFs**: If possible, join forces with nearby housing associations to negotiate better fuel supply contracts or share best practices.\n\n### Continuous Monitoring and Improvement\n- **Track Energy Usage**: Regularly monitor energy consumption and costs to identify trends and areas for further improvement.\n- **Implement Feedback Loops**: Encourage residents to provide feedback on temperature comfort and energy usage to inform future adjustments.\n\nBy following these steps, your BRF can enhance energy efficiency, reduce costs, and contribute to a more sustainable environment.", 'classification': 'generic', 'agent_answered': 'generic', 'intent': None, 'agents_used': [], 'vector_sources': []}
WARNING:src.agents.openai_agent:Skipping malformed message: {'content': 'I don’t have enough information to look up your housing‐cooperative’s (BRF) name. To retrieve it I need at least one of the following:\n\n • The property address (street name, number and postcode)  \n • The official Swedish property designation (fastighetsbeteckning) or BBR-ID  \n • The EPC report or project ID previously issued for your building  \n\nOnce you provide one of those, I can query the register and tell you the exact name of your BRF.', 'classification': 'building_specific', 'agent_answered': 'sql', 'intent': None, 'agents_used': ['Hammarby dataset used'], 'vector_sources': []}
INFO:src.agents.openai_agent:Response generated in 9.30 seconds.

[llm_summarizer] generate_response ✓
[llm_summarizer] EXIT

In [34]:
messages.append(value)

In [36]:
value

{'content': 'Your building’s latest certified energy class (2020) is C (it was B in 2016), and the primary heat source is an air-source heat pump (“PumpFranluft”). To raise your energy class you can consider measures in three main areas:\n\n1. Improve the building envelope  \n   • Insulate or upgrade attic, exterior walls and basement/slab edges to reduce heat losses.  \n   • Replace single or older double-glazed windows with high-performance, triple-glazed units.  \n   • Seal air-leaks around windows, doors and service penetrations to improve airtightness.\n\n2. Upgrade ventilation and heating system efficiency  \n   • Install a balanced mechanical ventilation system with heat recovery (FTX) if you currently have exhaust-only or natural ventilation.  \n   • Service or replace your air-source heat pump with a modern inverter-driven model that has a higher Seasonal Coefficient of Performance (SCOP).  \n   • Consider a ground-source (geothermal) heat pump or hybrid system if feasible on your plot.\n\n3. Add on-site renewable and low-energy technologies  \n   • Fit photovoltaic (PV) panels on your roof or façades to produce electricity and reduce your grid consumption.  \n   • Explore solar thermal collectors for pre-heating domestic hot water.  \n   • Replace all lighting with high-efficiency LEDs and install smart thermostats or building-automation controls to optimise energy use.\n\nAdditional tips  \n   – Carry out an energy audit to prioritise measures based on cost-effectiveness.  \n   – Check for any available subsidies or low-interest loans for energy upgrades in Stockholm.  \n   – Monitor energy use (smart meters) and adjust heating schedules and thermostat setbacks.\n\nBy combining envelope upgrades, more efficient heating/ventilation equipment and renewable installations you will reduce your specific energy use, lower your EPC index and move towards an A or B rating.',
 'classification': 'building_specific',
 'agent_answered': 'sql+vector',
 'intent': None,
 'agents_used': ['ODEN API', 'Documents stored in Vector database used'],
 'vector_sources': []}